### ISSUE TITLE
How to implment dynamic data source like load more features.

### ISSUE THREAD

**Issue by mytc** [Flipkart/recyclerlistview#105]
I wonder if this can be used for dynamic data source, like the load more features. So far I see their are no methods on for scrolled event. Unlike flatlist, there are ` onRefresh` , `onEndReached` etc for this scenario. 

Is this feasible? If so, how?

**Comment by naqvitalha** [comment]
`onEndReached` is already there. Just use `cloneWithRows` with new data to get new data provider and pass it to the list. Check this link: https://github.com/Flipkart/recyclerlistview/blob/593b7636264a49eb17bf75f88513420b8f0c9b85/src/core/RecyclerListView.tsx#L478-L547 other than these most `ScrollView` props are also supported.

**Comment by mytc** [comment]
@naqvitalha, yes you are right!! It works!! Thanks.

For anyone interested, one thing need to take concern is , when you update your data, and want to concatenate the data, you need concatenate to "_data" of the previous result.

**Comment by AbdallaMohamed** [comment]
@mytc Is accessing `_data` a good idea though? I'd say using the array that you supplied RLV with would be a better option. You never know what the inside implementation of the library is and it could change. Making your code independent of the library's implementation is usually a good idea.

**Comment by naqvitalha** [comment]
@mytc I agree will @AbdallaMohamed here. Modifying private properties is never a good idea since they're always open to change. You however get a getAllData() method on the data provider to get the array back. The best way to do this is what Abdalla mentioned hold on the the original array.
