### ISSUE TITLE
Initial null dataprovider error only happened in some devices. 

### ISSUE THREAD

**Issue by mytc** [Flipkart/recyclerlistview#108]
I initially I want the state of data to be empty, so in my constructor:

```
constructor(args) {
    super(args);
    let { width } = Dimensions.get("window");
    this._layoutProvider = new LayoutProvider(
      index => {return 0 },
      (type, dim) => {
        dim.width = width;
        dim.height = 88;         
      }
    );
    this.dataProvider = new DataProvider((r1, r2) => {
        return r1 !== r2;
    });
   
    this._rowRenderer = this._rowRenderer.bind(this);
  
    this.state = {
      data: this.dataProvider.cloneWithRows([{}]),
      refreshing : false,
    };
  
  } 


  componentWillMount() {
    this.Loaddata();
  }

  Loaddata = () => {
    store.get('saved').then((res) =>{
        let row = this.dataProvider.cloneWithRows(res);
        this.setState({data: row})
    } )
  }
```
Problem is I got this error. 

> [Unhandled promise rejection: TypeError: null is not an object (evaluating 'newData.length')]
> - node_modules/recyclerlistview/dist/reactnative/core/dependencies/DataProvider.js:31:30 in cloneWithRows
> 

But this error only appear in one of my phone. Nexus 4 is fine ,but I got this error from Xiaomi Phone. 

ps:
I am using https://github.com/jasonmerino/react-native-simple-store for storing and retrieve the data , I got other screen which retrieve data from remote web api, work totally fine.  Thus, I doubt it is this AsyncStorage wrapper module that caused the problem. 

Any Idea?

**Comment by naqvitalha** [comment]
The issue is simple if you look at it, `res` being passed to `cloneWithRows()` is null. Now why that is happening is upto your implementation. I don't know how `react-native-simple-store` works. In any case this isn't related to RLV.

**Comment by mytc** [comment]
@naqvitalha , ok thanks for the explanation.
