### ISSUE TITLE
How can we work with dynamic height?

### ISSUE THREAD

**Issue by witalobenicio** [Flipkart/recyclerlistview#110]
If I have a component that some times shows just 1 line of text (short name) and some times 2 or 3 lines?

**Comment by naqvitalha** [comment]
`forceNonDeterministicRendering={true}` will do that. And over the last couple of release it has become very fast, nothing to lose really. Once you do this the values given by your layout provider are considered as estimates.

**Comment by naqvitalha** [comment]
Since the functionality is already present I'll be closing this.

**Comment by AnandKuhar** [comment]
when using forceNonDeterministicRendering={true} with RecyclerListView it gives error "You are setting the style '{top : ...}' as a prop. you should nest it in a style object.

**Comment by naqvitalha** [comment]
@AnandKuhar web or react-native? If web are you prioritizing .web.js files?

**Comment by naqvitalha** [comment]
Or RNW?

**Comment by muhammadwafa** [comment]
@naqvitalha 
the forceNonDeterministicRendering={true} never helped me.
I have a chat app, there is dynamic height for any messages item.

**Comment by lamlengend98** [comment]
@naqvitalha i set forceNonDeterministicRendering={true} and width of item starts to increase infinity
