### ISSUE TITLE
Left and right column

### ISSUE THREAD

**Issue by doublex** [Flipkart/recyclerlistview#111]
Is it possible to create two columns, like:

<img width="184" alt="nfqav" src="https://user-images.githubusercontent.com/274624/35116738-c8c32216-fc8c-11e7-87e5-3d54097bd025.png">

**Comment by naqvitalha** [comment]
Not possible out of the box. You'll have to write masonry layout manager. If you're up for it I can help you out.

**Comment by naqvitalha** [comment]
Let's track this in #76. Closing.

**Comment by zyestin** [comment]
> Is it possible to create two columns, like:
> 
> <img alt="nfqav" width="184" src="https://user-images.githubusercontent.com/274624/35116738-c8c32216-fc8c-11e7-87e5-3d54097bd025.png">

Hi~. Have you implemented the waterfall as shown in your picture ？I need your help. tks very much
