### ISSUE TITLE
How to disable scroll bar when using horizontal mode?

### ISSUE THREAD

**Issue by mytc** [Flipkart/recyclerlistview#112]
In scrollview we have this `showsHorizontalScrollIndicator` to disable it, but it does not work in recyclelistview.  I have use ` useWindowScroll = { false }` , but its still not working. 

Any idea?

**Comment by naqvitalha** [comment]
`showsHorizontalScrollIndicator` does work. Are you sure that you're doing it correctly? Also, this prop doesn't work on web.

**Comment by mytc** [comment]
Ok, thanks.
