### ISSUE TITLE
[Question] Is it possible to implement Tile View with RecyclerListView

### ISSUE THREAD

**Issue by Gr1ver** [Flipkart/recyclerlistview#113]
I wonder if it possible to use RecyclerListView for some sort of tile view. I want to render a set of images with predetermined count in horizontal and vertical dimensions, where all images has the same specific size. 
Also with ability to scroll at all directions like this
![c9b9cfec-ff60-11e5-827c-6a550dff97e6](https://user-images.githubusercontent.com/10825987/35266530-9efb5c18-0034-11e8-90a5-ca80067c77f3.gif)

**Comment by naqvitalha** [comment]
Doing tile layout is possible. Just give the relevant layout and see if it works for you. Scrolling in multiple directions is not supported right now. You can workaround it though. Try wrapping it in an fixed height horizontal ScrollView. Masonry is not supported.
