### ISSUE TITLE
calculate next view position

### ISSUE THREAD

**Issue by mytc** [Flipkart/recyclerlistview#115]
I am trying building swiping gallery with this package, it works like a charm when deal with swipe left or right gesture. However, I want to add another tap gesture to scroll left or right, this is not supported natively. 
So, here is my implementation. 
  ```
///render
<RecyclerListView 
          ref={(ref) => this.tapscroll = ref}
          layoutProvider={this._layoutProvider}
          dataProvider={this.state.data} 
          rowRenderer={this._rowRenderer}
          isHorizontal={true}
          onEndReached={this.handleLoadMore}
          renderFooter={this.Loadmore}
          snapToAlignment={"center"}
          decelerationRate= {0}
          showsHorizontalScrollIndicator = { false }
          pagingEnabled = { true }
          alwaysBounceHorizontal={false}
        automaticallyAdjustContentInsets={false}
        
          />

///renderitem
<View style={styles.imagecontainer}>
    
        <Image
        style={styles.image}
        source={ imgurl }
        indicator={Progress.Circle} 
        resizeMode = {'cover'}
        >
        <TouchableWithoutFeedback onPress={()=> this.tapGesture("prev")}>
      <View...></View>
     </TouchableWithoutFeedback>
     <TouchableWithoutFeedback onPress={()=> this.tapGesture("next")}>
          <View...></View>
     </TouchableWithoutFeedback>
        </Image>
     </View>

  tapGesture = (type) => {
   let offset = blab blah blah..//how to calculate the offset here?
     if(type == "nex"){
        this.tapscroll.scrollToOffset(offset, 0, true)
    } 
  }
```

The problem is how to I calculate the next position based on the current position?  I do have fixed width with the screen width.

**Comment by mytc** [comment]
I managed to figure it out. Turn out I can use `onScroll` to set the state of current width.

```
onScroll={event => { 
          this.setState({current:event.nativeEvent.contentOffset.x})
        
        }}
```

**Comment by naqvitalha** [comment]
Actually you have `onVisibleIndexesChanged` callback to do the same. Also, we already provide a `scrollToIndex` method so, you might not need to compute the offset.

**Comment by mytc** [comment]
really?  Will it better then my method in term of performance?  It's lack of documentation though.

**Comment by naqvitalha** [comment]
Yes, doing a `setState` on `scroll` event is not a good idea. If you can explain what exactly you're trying to do I might give you a better option.

**Comment by mytc** [comment]
Basically I am building a pictures gallery where the source is from a rest api server. 
I want to implement  a feature where when user tap on the both left and right edges (with certain width from the edge) , user able to navigate to left or right. 

Right now I am storing the current offset in state in the onScroll methods and use it for calculation when navigate. I am using fixed screen orientation, so I just use it to `+` or `-` the current x-offset.

**Comment by naqvitalha** [comment]
You don't really need to store it in `state`. Even a local variable will do, calling `setState` triggers component update which you can easily avoid.

**Comment by mytc** [comment]
Yes, you are right. Using accessing the local variable improved a lot. Thanks.

**Comment by naqvitalha** [comment]
Great. Closing.
