### ISSUE TITLE
recyclerlistview in web Support RefreshControl?

### ISSUE THREAD

**Issue by jf4444** [Flipkart/recyclerlistview#116]
recyclerlistview in web Support RefreshControl?

I'm current use it to react web, but I don't find anyway to support pullRefresh..

**Comment by naqvitalha** [comment]
Yeah I think react-native-web doesn't have it right now. Our ReactJS implementation also lacks it. But don't you think browser pull to refresh is enough anyway?

**Comment by jf4444** [comment]
@naqvitalha You mean let the user click on the browser refresh button to refresh?

**Comment by naqvitalha** [comment]
@jf4444 chrome and other browsers on mobile have pull to refresh by default. They reload the page though.

**Comment by nickofthyme** [comment]
@naqvitalha that is true for mobile web but not the case for native mobile with React Native.

**Comment by naqvitalha** [comment]
Assuming browser refresh is the way to go.
