### ISSUE TITLE
 textInput with recyclerListView

### ISSUE THREAD

**Issue by Fernando-Parise** [Flipkart/recyclerlistview#118]
[Jan 31 2018 1_02 PM.zip](https://github.com/Flipkart/recyclerlistview/files/1682132/Jan.31.2018.1_02.PM.zip)

Hello everyone, I'm seeing the operation of rescyclelistview, but I'm having a hard time.
My situation is as follows:
I have a great list of products. but in addition to each item I can add / decrease quantity or write in textinput. but when I click on the textinput the list does not get focused on textinput. when the virtual keyboard goes up, the list does not do the scrool to be appearing the item that I want to edit.

this is my source code: [Produtos.txt](https://github.com/Flipkart/recyclerlistview/files/1681891/Produtos.txt)

I put a video of what my situation would look like. To the right side has a common flatlist. it repositions the item for editing, and to the left is the recyclerListView, which does not reposition the item to show
![list](https://user-images.githubusercontent.com/36001209/35630449-9b8a1236-0688-11e8-9f76-eb664fd6d230.gif)

thank you

**Comment by AbdallaMohamed** [comment]
Did you try using a keyboard avoiding view?
 https://facebook.github.io/react-native/docs/keyboardavoidingview.html

**Comment by Fernando-Parise** [comment]
I am a beginner in reac-native development. I did not know that this process existed. I'll try to use it.
thank you.

**Comment by Fernando-Parise** [comment]
Thank you very much. Completely solved my problem.

I just put the following code:
         <KeyboardAvoidingView
              behavior = "padding"
            >

**Comment by kameswarans** [comment]
I'm using Recyclelistview with render item in horizantal each item i had a TextInput but KeyboardAvoidingView is not working 

Here is my code 
 <RecyclerListView 
                pagingEnabled={true}
                showsHorizontalScrollIndicator={false}
                initialRenderIndex={this.state.initial}
                isHorizontal ={true}
                layoutProvider={this._layoutProvider}
                dataProvider={this.state.dataProvider} 
                rowRenderer={this._rowRenderer} />

_rowRenderer(type, data) {
        return (
           <View style={{ backgroundColor: 'white' }}>
            <Loader loading={this.state.loading} /> 
            <ScrollView  keyboardDismissMode="on-drag" keyboardShouldPersistTaps={true} style={{ width:wp('100%')}}>
                <View style={{width:wp('100%')}}>
                  <View style={styles.topimagebox}>
                    <Image source={{ uri:users1[data].image }} style={styles.topimg} />                  
                  </View> 
                </View>  
                <View style={{width:wp('100%')}}>
                  <View style={{marginHorizontal:5,marginVertical:3}}>             
                    <Text style={{fontSize:16,fontWeight:'bold',alignItem:'justify'}}>{users1[data].title}</Text>
                  </View> 
                  <View style={{marginHorizontal:5,marginVertical:3,height:1,backgroundColor:'#cacaca'}}></View>                           
                </View>  
                <View style={{marginVertical:10,marginHorizontal:10}}>                                 
                  <HTML html={users1[data].desc} imagesMaxWidth={wp('95%')}  tagsStyles={{ p: { alignItem:'justify',fontSize:15,color:'#000000',lineHeight:25,paddingTop:15 },}}/> 
                </View>                
             
                 <KeyboardAvoidingView style={styles.container}  behavior="padding"    >
                     <View style={{backgroundColor:'#fff'}}>
                  <View style={styles.marginproptop}>
                    <TextInput style = {styles.input}
                       underlineColorAndroid = "transparent"
                       placeholder = "Name"
                       placeholderTextColor = "#000"
                       autoCapitalize = "none"
                       returnKeyType="next"  ref="1"  onSubmitEditing={this.onFocusChange}
                       onChangeText = {this.handleEmail}/>
                    
                    <TextInput style = {styles.textareainput}
                      multiline={true}
                      numberOfLines={4}
                      underlineColorAndroid = "transparent"
                      placeholder = "Your Comment"
                      placeholderTextColor = "#000"
                      autoCapitalize = "none"
                      returnKeyType="go"  ref="2" 
                      onChangeText = {this.handlePassword}/>  
                  </View>
                  <View style={styles.marginprop}>   
                    <TouchableOpacity style = {styles.submitButton}  onPress = {() => this.login(users1[data].id)}>
                       <Text style = {styles.submitButtonText}> Submit </Text>
                    </TouchableOpacity>
                  </View>
                </View>   
                </KeyboardAvoidingView>     
            </ScrollView>
            </View>
        );        
    }








Please Help me to solve this
