### ISSUE TITLE
Mock recyclerlistview

### ISSUE THREAD

**Issue by nghialt** [Flipkart/recyclerlistview#121]
Hi I'm new here. Has anybody succeeded in using mock with `recyclerlistview`? 
I have searched around but not found any solution yet.

**Comment by naqvitalha** [comment]
Can you give a bit more explanation about the use case? Haven't personally used mock.

**Comment by naqvitalha** [comment]
Inactive for a while. Closing.

**Comment by kalpeshsingh** [comment]
Hello @naqvitalha 
Here is possible use case: https://github.com/callstack/react-native-testing-library/discussions/788

**Short summary:**
There are functions such as onPress, onScroll etc. on component used on `rowRender`. I want to test them using `react-native-testing-library`.  Seems like mocking can be solution here though difficult to get mock of RLV.

**Alternate question**
How do you suggest to test internal methods such as onPress, onScroll from these callbacks? I thought I will grab them from Testing Library's `getByText` and perform `fireEvent.scroll` and cover test cases.
