### ISSUE TITLE
row not removing

### ISSUE THREAD

**Issue by HemrajLodha** [Flipkart/recyclerlistview#122]
I want to remove row from list. after splice item from state data, data provider not removing from list.

using this data provider
```
new DataProvider((r1, r2) => {
            return r1 === r2;
        })
```

**Comment by naqvitalha** [comment]
You need to create a new one with updated data and re-render. I think you're just changing the existing one.

**Comment by naqvitalha** [comment]
If you can please share the code I can help you. It's pretty straightforward.

**Comment by naqvitalha** [comment]
Closing, not activity.
