### ISSUE TITLE
Mobx Invariant failed

### ISSUE THREAD

**Issue by Ciberusps** [Flipkart/recyclerlistview#124]
Error: [mobx] Invariant failed: Side effects like changing state are not allowed at this point. Are you trying to modify state from, for example, the render function of a React component?

I try to pass clicked item id in _rowRender method like this:
```js
  _rowRender(type, data) {
    return (
      <ExampleItem
        onPress={() => {
          this.props.exampleStore.selectItem(data.item.id);
        }}
      />
    );
  }
```
How to use it right?

**Comment by naqvitalha** [comment]
Can you provide a sample to help us debug the issue? A snack or repo with repro will do.

**Comment by Ciberusps** [comment]
Sorry that so long. Delayed due to expo snack not support decorators. I used mobx observable variable to store data provider(to follow "best practices" of mobx - replace internal react component state) if u have same issue just dont do it use react react.

Thank u for reply u can close issue.
