### ISSUE TITLE
RecycleView needs to have a bounded size. currently height or, width is 0 

### ISSUE THREAD

**Issue by YogeshYo** [Flipkart/recyclerlistview#128]
I need to place recylerlistview inside scrollview  to develop required UI structure. When I place recylerlistview inside scroll view I get "RecycleView needs to have a bounded size. currently, height or, width is 0" . Any workaround? Thanks

**Comment by naqvitalha** [comment]
Nested scrolling doesn't even work in react-native. Why would you want this? You can give a height to RLV to make it work. But I won't recommend it.

**Comment by YogeshYo** [comment]
Thank You for your response. I found a workaround.

**Comment by naqvitalha** [comment]
Great. Closing.

**Comment by usman-afzal** [comment]
@YogeshYo I am getting the same error can you share your workaround?
