### ISSUE TITLE
Pixel 2 XL can't render multiple columns

### ISSUE THREAD

**Issue by aaemman** [Flipkart/recyclerlistview#133]
When trying to render a RLV on a Pixel 2 XL, all cells set to 50% width display as rows of 1 left aligned item, instead of being rows of 2 items, one left aligned and one right aligned.

Th is problem doesn't seem to occur when rendering the exact same code on a Samsung Galaxy S8 or an iPhone.

![screenshot_20180302-102950](https://user-images.githubusercontent.com/2026893/36906757-c5cd3954-1e04-11e8-8790-b1227b61055d.png)

This problem can even be recreated using the default RLV code provided in the readme

**Comment by aaemman** [comment]
UPDATE: It seems that this issue only happens if the children take up exactly 1/2 of the width, anything below 1/2 works as expected

**Comment by naqvitalha** [comment]
Yeah, just offset width by 0.0001 on one of the items yourself just to be safe. This does happen. Anyways, more kinds of LayoutManagers will be coming to RLV in the future.

**Comment by naqvitalha** [comment]
@aaemman I think the best solution is to round off the window width to 4 decimal places to avoid JS precision issues. Closing.
