### ISSUE TITLE
Horizontal RecyclerListView on iOS does not re-layout when deleting items

### ISSUE THREAD

**Issue by siebeprojects** [Flipkart/recyclerlistview#135]
Hi,

Given the included screenshots. 
RED Color is the RecyclerListView
BLUE Color is the contentContainerStyle inside the RecyclerListView.

The selected items in the vertical page are the same as the items in the bottom horizontal RecyclerListView.

The problem is this:
1. I scroll all the way to the last item in the horizontal RecyclerListView so that "Agentina" is visible.
2.  I deselect "Anguilla" in the vertical page which is the third last item. This will update the Redux states and execute the following code in the componentWillReceiveProps in my BottomToolbarComponent:

  componentWillReceiveProps(nextProps) {
    const equals = isEqual(this.props.selFilterQueue, nextProps.selFilterQueue);
    if (!equals) {
      const newData = this.createListMap(nextProps.routes, nextProps.selFilterQueue);
      this.setState({
        dataProvider: this.state.dataProvider.cloneWithRows(newData)
      });
    }
  }

render() {
    return (
      <View
          style = { localStyles.toolbarlist_layout } >

        <RecyclerListView
            ref = { ref => this.recyclerListView = ref }
            contentContainerStyle = { localStyles.toolbarlist_container }
            canChangeSize = { true }
            forceNonDeterministicRendering = { true }
            isHorizontal = { true }
            showsHorizontalScrollIndicator = { false }
            layoutProvider = { this.layoutProvider }
            dataProvider = { this.state.dataProvider }
            rowRenderer = { this.rowRenderer } />
      </View>
    );
  }

RESULT iOS
The result is that the contentContainer becomes smaller than the RecyclerListView and thus there is whitespace (blue) after the Argentina item. If I drag a little bit with my finger all of a sudden the items are now properly re-layout and the blue space is gone. 

EXPECTED iOS
The RecyclerListView should re-layout the remaining items so that there is no white space after the last element in the list. 

ANDROID
In Android it works correctly. 
When deselecting the Anguilla item, the RecyclerListView does a proper re-layout of the items and there is no white space (blue) after Argentina.

![1 scrolled to end](https://user-images.githubusercontent.com/2749406/37095254-9ef1ab8e-2215-11e8-8e05-220262a1f115.png)
![2 anguilla deleted](https://user-images.githubusercontent.com/2749406/37095787-21b7bb02-2217-11e8-9582-c385b3b17d95.png)

**Comment by naqvitalha** [comment]
It is actually a ScrollView bug in iOS and not related to RLV. @siddhantsoni can we fix this the way fixed offset issue in react-native? Check #77

**Comment by naqvitalha** [comment]
In future we are planning to include a scrollview of our own to take care of this. Since this has been inactive I'll close it.

**Comment by bryantee** [comment]
Looks like `contentContainerStyle` prop needs to be added to type def.
