### ISSUE TITLE
[SUGGESTIONS] Add Popular Use-case

### ISSUE THREAD

**Issue by LouisJS** [Flipkart/recyclerlistview#138]
Thanks for this library. It looks awesome, and is very useful in the current RN ecosystem.

Therefore, it would be nice to make available to new users common use-case needed in real-world apps.

For instance, it would be nice to have an example that loads data from an API (componentDidMount). Both example you provide are using generateData or Mockup Data.
As some logic takes place in the constructor itself, it is confusing how we can implement it.

Also, i haven't seen any trace of `pullToRefresh` or `onEndReached` feature which are really necessary and common user-case.

By doing so, it should probably be easier and clearer for new user to try this library out 😄 

Feel free to add any other relevant suggestions to improve the 'onboarding' to use this lib 👍

**Comment by naqvitalha** [comment]
I have shared the link to props btw. And they're well commented. Most people have been able to understand through those. https://github.com/Flipkart/recyclerlistview/blob/afd7d80c13bad68ddbb60849ccda47ccef3ecda2/src/core/RecyclerListView.tsx#L488-L566
I do understand the need for better documentation but I would really want the community to help me there. I need to finish my work here first, I have lot of plans :)

**Comment by pribeh** [comment]
@naqvitalha That's amazing. Thanks! I didn't realize that even though it's mentioned that all scrollview properties work in the readme. Maybe make a note about like "all scrollview properties like refreshcontrol, etc." work so that its obvious to dumbies like me.

**Comment by naqvitalha** [comment]
@pribeh I incorporated your suggesting. Thanks :)
New samples and perf guidelines added.
Closing.
