### ISSUE TITLE
Viewability feature events

### ISSUE THREAD

**Issue by asadallahi** [Flipkart/recyclerlistview#149]
How can I detect the **current item** is active in recyclerlistview (**visible on screen**)?

**Comment by naqvitalha** [comment]
Please check the `onVisibleIndexesChanged` callback. It gives you `all, now, notNow` all that you might need. Close if that's what you were looking for.

**Comment by asadallahi** [comment]
Thanks for quick reply!  

Can you please provide sample code for that?

**Comment by asadallahi** [comment]
I got that with: 
`<RecyclerListView onVisibleIndexesChanged={this.visibleLog.bind(this)} layoutProvider={this._layoutProvider} dataProvider={this.state.dataProvider} rowRenderer={this._rowRenderer} />`

thanks for your awesome library

**Comment by naqvitalha** [comment]
You method should be `visibleLog(all, now, notNow)` RLV will call it with right params (those are arrays btw). After having the right indexes you can do whatever you want. If you want data fetch from your `DataProvider` using the given indexes.

**Comment by asadallahi** [comment]
Kindly please tell me how can I update the items viewable to screen

**Comment by naqvitalha** [comment]
You need to update the data using those indexes and re-render. RLV will/cannot give you direct references.

**Comment by asadallahi** [comment]
Can you explain more about 
> using those indexes and re-render.

I couldn't find any document for re-render them
