### ISSUE TITLE
_layoutProvider with dynamic height

### ISSUE THREAD

**Issue by asadallahi** [Flipkart/recyclerlistview#150]
I have Recyclerview with **dynamic data** provider (with **different height for each item**) in it but when I want to render them recyclerview says:
`RecyclerListView needs to have a bounded size...`

How can I set it to work with dynamic height for each item?

**Comment by asadallahi** [comment]
based on your answer in [this issue](https://github.com/Flipkart/recyclerlistview/issues/110) I used `forceNonDeterministicRendering={true}` but still getting the same error

**Comment by naqvitalha** [comment]
Same as #144 #89 and #74 check if those answers clear it up for you.

**Comment by mallipurna03** [comment]
> forceNonDeterministicRendering={true}

Seems working fine for me, thanks...
