### ISSUE TITLE
LayoutProvider responsive width

### ISSUE THREAD

**Issue by TomPradat** [Flipkart/recyclerlistview#151]
It would be great to be able to set responsive width in the layoutProvider.

I'm trying to have a 100% width for example. I'm actually using window.innerWidth but the problem is that when resizing my browser window, the size is not recalculated.

**Comment by naqvitalha** [comment]
Set `canChangeSize` to true. That should do it.

**Comment by TomPradat** [comment]
I'll try it but it's specified that on web this only works with useWindowScroll to true and i'm using it without windowScroll.

**Comment by TomPradat** [comment]
As expected this doesn't work with the prop `useWindowScroll` to false.

**Comment by naqvitalha** [comment]
You can pass your own `ScrollView` which can raise `onSizeChanged` event.

**Comment by naqvitalha** [comment]
RLV computes layouts itself so these dynamic widths cannot work. There is a relayout logic in place but to trigger it you need to raise `onSizeChanged`. Why it cannot be automatically is because there is no performant way to observe resizes on a div. However passing your scrollview is not hard. Give it a try.

**Comment by TomPradat** [comment]
I tried to pass my own ScrollView and add a window resize event listener in `componentWillMount` even when `useWindowScroll` is set to false, but i can't figure out what to do then; i though calling `this.props.onSizeChanged({height: this._mainDivRef.clientHeight, width: this._mainDivRef.clientWidth});` would work but it doesn't

 I did fork your project and managed to get what i want
- https://github.com/TomPradat/recyclerlistview/commit/e677192764f93de9637eb4dc0d99d59c4964711d
- https://github.com/TomPradat/recyclerlistview/commit/3581e08b6d3499fdf983466d1da283fef5becbb4

I know this is not even close to the beginning of a PR but maybe you should get the idea. Now i can resize my window and have the container width and rows shrinking as expected.

**Comment by naqvitalha** [comment]
Did you make sure that you had set `canChangeSize` to true when you passed `externalScrollView`? 
What you're doing is not extensible, there is a reason why we don't accept "100%" as a dimension.

**Comment by TomPradat** [comment]
Yes i tried to pass an externalScrollView but i didn't figure out how to do it properly. Your solution works perfectly so far. Thanks for your time and for this great lib :)

**Comment by TomPradat** [comment]
First of all thank you for your help and time and for this great lib :) . Indeed your example works nice. However i still have the problem on my use case, check https://codesandbox.io/s/0qpozm32wl for more details. My problem appears when using flexbox layout, i'd expect the list to shrink and grow. That's why i need 100% width dimension.

**Comment by TomPradat** [comment]
Hey @naqvitalha, any news ? What do you think about my problem ? Do you think it would be valuable to have a boolean prop as discussed for width 100% ? I can work on a PR but i'd rather have your approval first.

**Comment by aryo** [comment]
A little unrelated, but is there a way to do dynamic heights?

**Comment by naqvitalha** [comment]
@TomPradat You can wrap the `ScrollViewer` in a `div` and then report the size of it instead to make it work your use case.
@aryo Yeah, just set `forceNonDeterministicRendering` to `true`

**Comment by TomPradat** [comment]
Alright, i did wrap the `ScrollViewer` in a div and this works fine.

I still think this is not optimal though, as javaScript window resizing is way slower than css 100% width.
If you agree, i'd be glad to work on a PR.

Btw thank you for your time and for this great lib 😄 🎉!

For anyone looking for a working example : https://codesandbox.io/s/0qpozm32wl

**Comment by naqvitalha** [comment]
@TomPradat  I'm glad it works for you. Regarding the resize event we are only listening to the event and acting on it. The actual resizing that RLV does will be slower, yes, but not significantly. The reason we need this is to enable recycling. RLV needs to know the size of its children to be able to recycle cells efficiently. Ff you use css RLV will eventually fall out of sync and you'll lose out on that optimisation. Hope this makes it clear. Closing this :)
