### ISSUE TITLE
Slow Rendering of List View

### ISSUE THREAD

**Issue by Louies89** [Flipkart/recyclerlistview#152]
@naqvitalha 
Hi,
I am using realm for my app. realm has zero copy mechanism, so it provides a object which shall point to the data present in the memory. And data at any time can be retrieved using the object (similar to json object array.)

I tried this library with below code, but it takes long time(usually 3/4 seconds) to update te next rows while scrolling.

Can you please suggest, what configuration changes I should make in the code to get smooth and faster list view shall be rendered.

```
import React, { Component } from "react";
import { View, Text, Dimensions } from "react-native";
import { RecyclerListView, DataProvider, LayoutProvider } from "recyclerlistview";

import * as RmCntact from './src/realm/RmCntcts'
import Cntact from './src/realm/RmCntcts'
let CntactRead = Cntact.objects('Contacts');

var data = [];
console.log(CntactRead[0]);
if(CntactRead && CntactRead.length){
    CntactRead.forEach((v)=>{
        // console.log(v);
        data.push({id:v.id,name:v.name});
    })
//   data = Array.from(CntactRead);
}
else{
  data = [{id:0,name:'Nothing to Show'}];
}

let { width } = Dimensions.get("window");

const ViewTypes = {
    FULL: 0,
    HALF_LEFT: 1,
    HALF_RIGHT: 2
};

let containerCount = 0;

class CellContainer extends React.Component {
    constructor(args) {
        super(args);
        this._containerId = containerCount++;
    }
    render() {
        return <View {...this.props}>{this.props.children}<Text>Cell Id: {this._containerId}</Text></View>;
    }
}

export default class RecycleTestComponent extends React.Component {
    constructor(args) {
        super(args);

        let dataProvider = new DataProvider((r1, r2) => {
            return r1 !== r2;
        });

        this._layoutProvider = new LayoutProvider(
            index => {
                    return ViewTypes.FULL;
            },
            (type, dim) => {
                    dim.width = width;
                    dim.height = 140;
            }
        );

        this._rowRenderer = this._rowRenderer.bind(this);

        this.state = {
            dataProvider: dataProvider.cloneWithRows(CntactRead)
        };
    }

    _rowRenderer(type, data) {
        return (
            <CellContainer style={styles.container}>
                <Text>Data: {data.name}</Text>
            </CellContainer>
        );
    }

    render() {
        return <RecyclerListView 
                layoutProvider={this._layoutProvider}
                dataProvider={this.state.dataProvider} 
                rowRenderer={this._rowRenderer} 
                renderAheadOffset = {2000}
            />;
    }
}
const styles = {
    container: {
        justifyContent: "space-around",
        alignItems: "center",
        flex: 1,
        backgroundColor: "white",
        borderWidth:1,
        borderColor:'gray',
        height:80
    },
};
```

Can you please provide some suggestions on what I should to get good performance and efficient loading of list view...?

**Comment by naqvitalha** [comment]
Things to watch out for:
1) Don't test perf on dev mode. Set dev to off and minify to true.
2) Component being returned in `rowRenderer` needs to have `shouldComponentUpdate` defined.
3) `rowHasChanged` should not be returning `true` all the time.

You can check the expo sample to get an idea of the performance. It should be very fast. Also, you don't need to set `renderAheadOffset` to such large value, default is fine in most cases.
Let me know if you need further help. An expo sample with the problem will help me check it out quickly.

**Comment by Louies89** [comment]
@naqvitalha 
As I am using realm as db, I cannot create a expo project.  

So can you please check the **1App.js** and **RealmCntcts.js** files from https://github.com/Louies89/TrialRealm

**Comment by Louies89** [comment]
@naqvitalha the 2nd point 
`Component being returned in rowRenderer needs to have shouldComponentUpdate defined.`

I am unable to understand and can please share the expo sample link..

**Comment by naqvitalha** [comment]
Straight hit for point 3. I would've appreciated if you would've checked it yourself. `r1!==r2` was true all the time. This method is there for a reason. I found a uid in your data as well. I changed the code to:

```js
	this._dataProvider = new DataProvider((r1, r2) => {
					return r1.uid !== r2.uid;
				}).cloneWithRows(CntactRead);
```
It works perfectly after that.

**Comment by Louies89** [comment]
@naqvitalha ooh... I didn't understand it before....
I will try this...

Thank you for your time... :)

**Comment by Louies89** [comment]
@naqvitalha there is not much difference still lagging...

**Comment by naqvitalha** [comment]
Are you sure it's not on `dev` mode? Majority of the times when people complained about something like this they were on `dev` mode on Android. On iOS there is not direct way to turn off `dev` other than making the release build.
@Flipkart we have much more complex templates and see no performance issue. You should be seeing no blanks or lags unless you have missed something in the mentioned pointers.
Check this: https://www.youtube.com/watch?v=6YqEqP3MmoU

**Comment by Louies89** [comment]
@naqvitalha 
After adding canChangeSize the images are getting loaded properly..

But I think there is a small bug in the library, and that is if i am adding `style={{flex: 1}}` for the element to be loaded in the list, the data and the starting position of the rows are not rendered properly.

Can you please give some hint how to add the spinner while loading the data...

**Comment by Louies89** [comment]
@naqvitalha 
Can you help me please?

**Comment by naqvitalha** [comment]
For the loader thing you can use the `renderFooter` prop.
For rest I would recommend you to try building something on expo to build the expertise first. I'll also be able to check the issues. I'm not free these days, cloning and running codebases is not feasible. I can look into anything available on expo.

**Comment by Louies89** [comment]
Ok, I will send expo links next time...
I know that i have to us the footer part, but when to show the footer and when to hide, that is not knowing...

If you have any example for footer part, can you please share ?

Thank you :)

**Comment by twistedfork88** [comment]
@naqvitalha I'm noticing issues arising out of performance but at the same time the components rendered do not have an SCU hook. I'm proposing can we add `console.warn` to such scenarios so that we don't have to reiterate over DEV mode or any other caveat???

**Comment by naqvitalha** [comment]
@twistedfork88 RN does itself give out a warning about DEV being true. I can add one to RLV context too. But this is one thing every developer should already know.
How do you think I can add warnings for point 2/3? Couldn't think of a way to infer if `rowHasChanged` will always be true.
