### ISSUE TITLE
React does not recognize the `XXX` prop on a DOM

### ISSUE THREAD

**Issue by maxfarseer** [Flipkart/recyclerlistview#153]
I'm using recyclerlistview with react-native-web, and have a lot of this warnings in development mode. How it's possible to get rid of it?

**Comment by naqvitalha** [comment]
@necolas Shouldn't RNW `ScrollView` filter out the props it doesn't understand? The `react-native` one does. Regardless, I plan to filter these out in RLV itself in a future revision.

**Comment by necolas** [comment]
Yeah I kind of hate how sloppy RN is about passing props down. It should be more explicit and not pass everything through.

**Comment by naqvitalha** [comment]
It does so before sending them down to the native views. So, it works out in this case. RNW isn't doing so. Although I plan to filter out at RLV level. But should we think about making RNW somewhat selective while choosing props to pass down to inner div?

**Comment by necolas** [comment]
Possibly, but filtering props isn't free and should really be taken care of in user land components. Passing invalid props to RN components should be prop warnings and flow errors. Like RN FlatList passes all it's props to scrollview even though they are not recognized :/

**Comment by cgav** [comment]
@naqvitalha @necolas any updates on this?
