### ISSUE TITLE
recyclerlistview save contentOffset after rerender with new dataProvider

### ISSUE THREAD

**Issue by damikdk** [Flipkart/recyclerlistview#156]
Thank you, your component is amazing! In some cases, even too much. I can't just refresh data in list, it save old offset, even if I set new dataProvider. Expo snack: (https://snack.expo.io/HkAA_KCoz)

```
<View style={styles.container}>
  <TouchableOpacity
    onPress={() => {
      let dataProvider = new DataProvider((r1, r2) => {
          return r1 !== r2;
      });
      
      this.setState({ dataProvider: dataProvider.cloneWithRows(this._generateArray(10)) })
    }}
  >
    <Text>Make it short</Text>
  </TouchableOpacity>
  <RecyclerListView
    initialOffset={800}
    layoutProvider={this._layoutProvider} 
    dataProvider={this.state.dataProvider} 
    rowRenderer={this._rowRenderer}
  />
</View>
```

**Comment by naqvitalha** [comment]
It should, shouldn't it? Think about when you add new data to the bottom of the list, that too is a `DataProvider` change. In this case however you can simply obtain the `ref` of RLV and call `scrollToOffset` with `y` as 0 to jump to top. e.g:

`this.setState({ dataProvider: dataProvider.cloneWithRows(this._generateArray(10)) }, ()=>{this._rlv.scrollToOffset(0,0,false)}})`

**Comment by damikdk** [comment]
Now I see, thanks! My [expo snack](https://snack.expo.io/rJjLhSJnM) now includes solution:

```
  onPress={() => {
    let dataProvider = new DataProvider((r1, r2) => {
        return r1 !== r2;
    });
    
    this.setState({ dataProvider: dataProvider.cloneWithRows(this._generateArray(10)) },
     ()=>{
       setTimeout(() => {
         this.listRef.scrollToOffset(0, 0, false);
       });
     });
  }}
```

Your code without setTimeout() works only if oldContentOffset < newContentSize. Thank you!

**Comment by naqvitalha** [comment]
Great! Closing.
