### ISSUE TITLE
scroll to specific index

### ISSUE THREAD

**Issue by asadallahi** [Flipkart/recyclerlistview#157]
Assume that the user is in middle of `recyclerlistview` and the app fetched new items from server and prepend them to the list and I want to **show a button** for _scroll to top_ to **view new items**.

How can I implement that?

**Comment by AbdallaMohamed** [comment]
Get a ref to RecyclerListView and call `scrollToIndex(0)`
https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L222

**Comment by mayconmesquita** [comment]
@AbdallaMohamed you save my day
