### ISSUE TITLE
组件不支持像Flatlist里面的renderHeader()吗？

### ISSUE THREAD

**Issue by xhun2015** [Flipkart/recyclerlistview#159]
我的界面上半部分是伦播图，下半部分是列表，需要实现整体可以滚动，该如何实现呢，我将伦播部分放到recyclerlistview中作为一个item,由于轮播图是flatlist实现的，此时伦播图不显示

**Comment by naqvitalha** [comment]
It would help if you can post this in English :) Don't know Chinese. I tried translating still couldn't get it.

**Comment by Bobwu1** [comment]
I think he's trying to implement the renderHeader and renderFooter functionality. Is there any way to do that or do we have to implement a "header" and "footer" type within LayoutProvider?

**Comment by naqvitalha** [comment]
There is a `renderFooter` prop available but no `renderHeader` as of now.

**Comment by tafelito** [comment]
@naqvitalha any plans to implement renderHeader? I might be able to give it a shot

**Comment by mrafei** [comment]
I tried doing this by adding a type if index is 0 in `layoutProvider` and prepending the header component to items list like this:
`let dataProvider = this.dataProvider.cloneWithRows([headerComponent].concat([itemsList]));`
problem is concatenating a large list is not efficient, also we would like to have the list header being rendered independently while `recyclerListView` renders them all together which results in bad user experience.
implementing this feature would be great! thanks.

**Comment by arunreddy-flipkart** [comment]
As suggested by @mrafei, The simplest approach would to be to use index 0 in layoutprovider as the header. If the header is supposed to be sticky, Sticky header feature has been added please refer to - https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/sticky. Closing in favour of #233
