### ISSUE TITLE
Using fetched data in DataProvider

### ISSUE THREAD

**Issue by Bobwu1** [Flipkart/recyclerlistview#160]
So far, your examples are using a static array for the DataProvider initiated in the constructor. What's the best way to use data fetched through an API? Some documentation on what DataProvider does (and why we have to use cloneWithRows) would be helpful.

**Comment by AbdallaMohamed** [comment]
I'd do that:
```
const newItems = await API.getNewItems();
this.setState(prevState => ({
  dataProvider: prevState.dataProvider.cloneWithRows(newItems)
}))
```

As far as I understood from the data provider class: 
https://github.com/Flipkart/recyclerlistview/blob/c23a1a2a6e9b521c5055c6c8b8a786064056b1b2/src/core/dependencies/DataProvider.ts#L31

It simply creates a new `DataProvider` with the same `rowHasChanged` function, and optimizes rows processing.
