### ISSUE TITLE
onScroll not triggering react native android

### ISSUE THREAD

**Issue by ashokkumar88** [Flipkart/recyclerlistview#161]
Hi,

I added onScroll event to `RecyclerListView` to implement collapsible navbar. Buth the `OnScroll` prop is not triggering. Below is the code

```
<RecyclerListView
         layoutProvider={this._layoutProvider} 
         dataProvider={this.state.dataProvider} 
         rowRenderer={this._rowRenderer} 
         onEndReached={() => this.handleLoadMore()}
         onEndReachedThreshold={0.1}
         renderFooter={this.renderFooter}
         refreshControl={<RefreshControl
         refreshing={this.state.refreshing}
         onRefresh={this._onRefresh.bind(this)}          
         showsVerticalScrollIndicator={false}  
         contentContainerStyle={{paddingTop: NAVBAR_HEIGHT}}         
         onscroll={Animated.event(
          [{nativeEvent: {contentOffset: {y: this.scroll}}}],
          {useNativeDriver: true},
)}
 
       />
```

**Comment by AbdallaMohamed** [comment]
Maybe change `onscroll` to `onScroll`?

Your onScroll function will be called with the following paramters.
`onScroll?: (rawEvent: ScrollEvent, offsetX: number, offsetY: number) => void;`

If you want to attach an Animated Value to the ScrollView though, you'd have to provide your own custom, I guess. Already tried that when I was experimenting with sticky headers. Maybe one of RLV's authors can help.

**Comment by ashokkumar88** [comment]
Yes i am using `onScroll'. But still it is not working. Can u please share how you have implemented

**Comment by naqvitalha** [comment]
@ashokkumar88 It does work, check this sample: https://snack.expo.io/BJ-0fM1TG
Close if it does it for you.

**Comment by ashokkumar88** [comment]
@naqvitalha  Yes, it is working fine now. Thanks

**Comment by LeProberto** [comment]
Hi, 
I have created collapsible header with these examples using react-native standard Animated library.
I want to switch to react-native-reanimated, but I'm facing a problem, that onEndReached is no longer triggering. My guess there is a conflict with reanimated's Animated.ScrollView, any tips in fixing/debugging this issue?

**Comment by SunskyXH** [comment]
Sorry to bother, but I'm facing the same issue with @pijusz . Any update there?
