### ISSUE TITLE
Scroll problems on device while using with React Native Web

### ISSUE THREAD

**Issue by antonKalinin** [Flipkart/recyclerlistview#167]
Hi, we are using Recyclerlistview with React Native Web and faced with the problem that on device, then the `initialOffset` or `initialRenderIndex ` prop is set (or you using contextProvider which internally sets initialOffset) the component stops to response to scroll (exactly touch event, wheel scroll continue to work). It looks like in this case ScrollView from React Native Web is using and maybe its not completely compatible with Recyclerlistview. (just my suggestion) Сould you advise what to do in such case?

**Comment by naqvitalha** [comment]
@antonKalinin I have tested this flow multiple times on RNW but never faced this issue. Try playing with the web sample https://codesandbox.io/s/k54j2zx977 and see if you can repro it on a fork. If you can, share it with me. 
What device/browser are you testing on?

**Comment by antonKalinin** [comment]
@naqvitalha I tested on iPhone (both device and emulator) in safari. Thanks for example, I will try to understand whats wrong with my case.

**Comment by antonKalinin** [comment]
@naqvitalha I can reproduce this issue by setting `initialOffset` prop in sandbox sample you sent me above. https://codesandbox.io/s/4rvmzyxj09 The strange thing that problem is occurs not from the first load but after several reloading (5-7 in my case) and after that it stable appears (scroll not working) I tested both on my iPhone and emulator, in Safari.

**Comment by naqvitalha** [comment]
@antonKalinin You are right, I checked on iPad. Try importing from "recyclerlistview/web" instead. That will use the `ScrollView` written for pure web. I will look into why RNW one is failing here, looks like window is taking control of the touch input.

**Comment by naqvitalha** [comment]
@necolas FYI

**Comment by antonKalinin** [comment]
@naqvitalha Thanks for advice, using RLV from `recyclerlistview/web` solves the problem.
