### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this._layouts[i].x')

### ISSUE THREAD

**Issue by peteroid** [Flipkart/recyclerlistview#168]
I got this error in my react native project. I have two RLV in two different screens. Do we need to check if the element exists before reading the `x` ?

Environment
- Platform: iOS
- RN: 0.49.5
- RLV: 1.3.4

**Comment by peteroid** [comment]
I don't have any function call to access that value. I am using the RLV as the example. This issue only occurred in this scenario. 

For example there is a component ScreenA, if the data provider gets more elements (removal doesn't cause this error) and the component is not updated due to the false `props.isFocused`. This error will occur when the `props.isFocused` is once changed back to `true`. 

```
// will cause error
class ScreenA extends Component {
  shouldComponentUpdate (props, state) {
    if (!props.isFocused) return false
    // other comparisons ... 
  }

  render () {
    return <RLV ... />
  } 
}
```

As I am not familiar with the implementation of RLV, I would say this error only occurs when the data provider adds more elements but the component is not rendered for that addition. Then, the RLV will cause the error in the next render.

I have managed to resolve this issue by modifying the `shouldComponentUpdate` as below.
```
class ScreenAFixed extends Component {
  shouldComponentUpdate (props, state) {
    if (/* state.dataProvider changed */) return true

    if (!props.isFocused) return false
    // other comparisons ... 
  }

  render () {
    return <RLV ... />
  } 
}
```

**Comment by naqvitalha** [comment]
Whenever you update `dataProvider` you have to render again. I think in your case you changed the array that you had passed to `dataProvider`. Make sure you keep them in sync.

**Comment by peteroid** [comment]
This error didn't show up anymore. Closing this issue.
