### ISSUE TITLE
RLV jitters when adding new items

### ISSUE THREAD

**Issue by hhunaid** [Flipkart/recyclerlistview#176]
I have implemented infinite scrolling but whenever I add rows to my dataset dynamically, view jitters. Its more prominent on lower end devices e.g. iPhone 5, Samsung S3.
I will try to capture a GIF to show what I mean. But it mostly feels like newly added items have a translation animation (top to bottom)

**Comment by naqvitalha** [comment]
Shouldn't be happening. Can you share your implementation? Also, read the performance guide.

**Comment by hhunaid** [comment]
I figured it out. I was using the wrong type of cells for my items
