### ISSUE TITLE
How to trigger a re-render on data change?

### ISSUE THREAD

**Issue by dancherb** [Flipkart/recyclerlistview#180]
I couldn't find an example of this in the sample code - at the moment I'm doing the following, which may not be ideal:

```
componentDidUpdate(prevProps) {
        if(prevProps.data !== this.props.data) {
            this.updateData()
        }
    }

    updateData() {
        this.setState(prevState => ({
            dataProvider: prevState.dataProvider.cloneWithRows(this.props.data)
        }))
    }
```

**Comment by maxfarseer** [comment]
@dancherb, use `componentWillReceiveProps` (for react < 16.3) or `getDerivedStateFromProps` (react 16.3+)

**Comment by naqvitalha** [comment]
Looks resolved. Thanks @maxfarseer for the help.
