### ISSUE TITLE
Getting blank page with no views

### ISSUE THREAD

**Issue by nehacs09** [Flipkart/recyclerlistview#183]
I have integrated this library using flag forceNonDeterministicRendering = true since, we don't know width and height of each element, but seeing whole page as blank sometimes.
`<RecyclerListView
                style={{ flex: 1 }}
                onVisibleIndexesChanged={this.onVisibleIndexesChanged.bind(this)}
                forceNonDeterministicRendering={true}
                layoutProvider={this.layoutProvider}
                dataProvider={this.state.dataProvider}
                rowRenderer={this._rowRenderer} />`

Layout provider code: 
`this.layoutProvider = new LayoutProvider(
            index => {
                return this.getDataSource()[index].widgetType
            },
            (type, dim) => {
                dim.width = width;
                dim.height = height;
            }
        );`
Please help me getting this resolved

**Comment by naqvitalha** [comment]
Are you sure that the issue isn't actually with the data source itself. Also, are the estimated dimensions close to the actual ones?
Also read the perf guide: https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/performance

**Comment by ashokkumar88** [comment]
@nehacurefit  I was having same issue when `forceNonDeterministicRendering={true}`. After removing this prop it works fine.

**Comment by yuvaraj119** [comment]
yes, the same issue am too getting first two row is visible after that its blank page just keeps scrolling till data ends.
current version : "recyclerlistview": "^1.4.0-beta.4", and even in stable version same issue

**Comment by nehacurefit** [comment]
@naqvitalha : We dont know the dimensions for items in the list as those  are variable height items, so i have defined width and height as window width and height in LayoutProvider.

**Comment by naqvitalha** [comment]
@nehacurefit It is important that the given values are close estimates. It is very important for good perf. You don't have to know exact values, just close approximations.
@yuvaraj119 Are you sure there were no JS errors in your code?

**Comment by yuvaraj119** [comment]
@naqvitalha yes no JS error in the code.
part of the code which i am using for showing gridView with 3 columns
this.state = {
            dataProvider: new DataProvider((r1, r2) => {
                return r1 !== r2;
            }).cloneWithRows(FlightData),
            layoutProvider: LayoutUtil.getLayoutProvider(6, 6),
            count: FlightData.length
        };

_renderRow = ({ item }) => (
        <GridImageView imageUrl='https://avatars0.githubusercontent.com/u/22407074?s=400&v=4' />
    )

{this.state.count > 0
                        ?
                        <RecyclerListView
                            style={{ flex: 1 }}
                            contentContainerStyle={{ margin: 1, backgroundColor: 'white', }}
                            dataProvider={this.state.dataProvider}
                            layoutProvider={this.state.layoutProvider}
                            rowRenderer={this._renderRow}
                        />

                        : <Text style={{ textAlign: 'center', alignItems: 'center', margin: 5 }}>No Data</Text>}

**Comment by naqvitalha** [comment]
@yuvaraj119 Can you provide a repro on expo? I can then quickly check. Most likely it's a bug in your implementation.

**Comment by yuvaraj119** [comment]
expo link: https://snack.expo.io/Hy8WSjc1m
In expo, I am getting the error.

**Comment by AbdallaMohamed** [comment]
@yuvaraj119 If that's the error you're talking about

![image](https://user-images.githubusercontent.com/10912145/40655114-9afa9074-6340-11e8-8e4f-91c4db5c9fc9.png)

It happens because you forgot to export your `GridImageView` class as the default export.

**Comment by nehacurefit** [comment]
This issue has been resolved for me . Thanks @naqvitalha foe help

**Comment by yuvaraj119** [comment]
@AbdallaMohamed 
ah in this i forgot to export the GridImageView and but in my main code now i fixed the issue of showing only the first two rows with other blank pages this happened because i was using recyclerview within the scrollview. i remove scrollview it worked.

Thanks @naqvitalha for instant support.
