### ISSUE TITLE
How to define dynamic LayoutProvider

### ISSUE THREAD

**Issue by nehacurefit** [Flipkart/recyclerlistview#184]
I am trying to define layout provider where type is basically coming in data source, so how can i define layout provider to take layout type when data source is updated. Sample code of my requirement is: 
`this.layoutProvider = new LayoutProvider(
            index => {
                return this.getDataSource()[index].widgetType
            },
            (type, dim) => {
                dim.width = width;
                dim.height = height;
            }
        );`

**Comment by maxfarseer** [comment]
@nehacurefit when you receive new Data, you can access to it inside componentWillReceiveProps (or getDerivedPropsFromState). After - you can setup new layout provider, and after you can setup new data provider. Is it works for you?

**Comment by nehacurefit** [comment]
Thanks @maxfarseer for help

**Comment by maxakak1998** [comment]
Hello, there is not LayoutProvider in the first place so i am wondering will it work ?

**Comment by jdpagley** [comment]
@maxfarseer THANK YOU SO MUCH FOR THIS Example!!!! I know this is from 2018 but this just helped me solve a problem that I've been wracking my brain over.. You're the man! 🦾 😁 👍🏽

**Comment by maxfarseer** [comment]
@jdpagley happy new 2021 👯
