### ISSUE TITLE
how to pass index or position of item to row render component

### ISSUE THREAD

**Issue by yuvaraj119** [Flipkart/recyclerlistview#186]
I tried this sample project but nowhere can see the way to pass the index or position to render component.
https://snack.expo.io/@naqvitalha/rlv-demo

`rowRenderer = (type, data) => {
    //We have only one view type so not checks are needed here
    return <ImageRenderer imageUrl={data} />;
  };`

i tried like this didnt work: 
`rowRenderer={({item, index}) => (
        this.rowRenderer(index)
      )} />`

any way to pass the index or position to rowRenderer.

**Comment by Jyrno42** [comment]
Check the third argument for rowRenderer:

`rowRenderer: (type: string | number, data: any, index: number) => JSX.Element | JSX.Element[] | null;`

https://github.com/Flipkart/recyclerlistview/blob/1.3.4/src/core/RecyclerListView.tsx#L81
