### ISSUE TITLE
Delayed scroll after update

### ISSUE THREAD

**Issue by Jyrno42** [Flipkart/recyclerlistview#188]
Would be nice if there would be an API to schedule delayed scrolls after updating dataProvider. Currently i am using a timer but that does not seem too solid. 

Note: I am using the beta version.

Some code as well:

```js
class MyComponent extends Component {
    constructor(props) {
        super(props);

        this.dataProvider = new DataProvider((r1, r2) => r1 !== r2);
        this.layoutProvider = getLayoutProvider(props);

        this.state = {
            dataProvider: this.dataProvider.cloneWithRows(props.items),
        };
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.items !== this.props.items) {
            const items = nextProps.items;

            this.layoutProvider = getLayoutProvider(nextProps);
            this.setState({
                dataProvider: this.dataProvider.cloneWithRows(items),
            });

           const scrollToLast = () => {
               this.listNode.scrollToIndex(items.length - 1);
           };

            // would like something this.listNode.postUpdateOnce(scrollToLast); or smth
            setTimeout(scrollToLast, 500); // in the real world i should manage clearing of this
        }
    }

    render() {
        return (
            <RecyclerListView
                layoutProvider={this.layoutProvider}
                dataProvider={this.state.dataProvider}
                rowRenderer={() => <Text>... omitted ...</Text>}

                initialRenderIndex={this.props.items.length- 1}

                ref={c => { this.listNode = c; }}
            />
        );
    }
}
```

**Comment by naqvitalha** [comment]
Why not do it in `componentDidUpdate`? By that time RLV would have completed its rendering.

**Comment by Jyrno42** [comment]
Doesn't RLV render multiple times? If I am not wrong, what would i use as an indicator to figure out that RLV is done w/ it's render cycle?

**Comment by jjhampton** [comment]
@Jyrno42 I am attempting to do something similar. Adding logic in `componentDidUpdate` to move RLV to a specific scroll index, however only currently able to get it working with a manual timeout. Same concern as you noted in your original post. 

Were you ever able to find a solution to this, to always call the `scrollToIndex` after you could ensure that RLV was finished with its initial renders (which appear to be multiple) ? Thanks.

**Comment by Jyrno42** [comment]
@jjhampton Nope I did not find a good soution so I just ended calling multiple times with a timeout. This worked but wasn't very elegant.
