### ISSUE TITLE
Search not supported ? 

### ISSUE THREAD

**Issue by cihangulx** [Flipkart/recyclerlistview#206]
I am trying filter items with lodash but nothing happen

**Comment by naqvitalha** [comment]
Please provide more info on the use case.

**Comment by ValentinBlokhin** [comment]
same here, when I try to search, the main data set filters and then I got 'No layout found for index #'. That's because I've already scrolled down few data and those data exists no more. I've tried to scroll to top at first, but it didn't help.

**Comment by sksin28** [comment]
@ValentinBlokhin Are you getting the same error as https://github.com/Flipkart/recyclerlistview/issues/234? Did you find any solution?

**Comment by ValentinBlokhin** [comment]
Yes, I had. 
I had been rendering list inside a function, when I moved rendering into separate component, the issue had gone

**Comment by kabus202** [comment]
Did you guys also experience a memory leak on iOS when implementing search?

@naqvitalha Is there some kind of search repo available? Or what's the best way to implement search?

**Comment by arunreddy-flipkart** [comment]
Assuming this to be resolved. Closing
