### ISSUE TITLE
Manual control over VirtualRenderer._checkAndChangeLayouts using refreshWithAnchor/refresh

### ISSUE THREAD

**Issue by Jyrno42** [Flipkart/recyclerlistview#209]
If one replaces their LayoutProvider when adding new items RLV always uses `refreshWithAnchor`. This messes up logic for people who want to control their scroll position manually.

(in my case i am creating a chat screen and want to scroll to the latest message in some cases)

Would it be possible to manually control which of the methods is used?

**Comment by naqvitalha** [comment]
LayoutProvider can dictate that. This can be incorporated. But is there a real use case of changing the LayoutProvider while adding data. Shouldn't you know the types upfront?
I'm open to adding it in the next release. It would help if you can raise a PR

**Comment by naqvitalha** [comment]
Please check `1.4.0-beta.10`. In that particular version you can unset a value on your layoutprovider e.g, `this._layoutProvider.shouldRefreshWithAnchoring=false;`

Please note that you'll need to do this on the new instance.

**Comment by Jyrno42** [comment]
:ok_hand: Nice

Thanks for the awesome library by the way.
