### ISSUE TITLE
Laggy scroll experience due to image fetch

### ISSUE THREAD

**Issue by markhomoki** [Flipkart/recyclerlistview#218]
Hello,

I have a weird issue related to refreshing images. This library made a scrolling much nicer however I cannot push production until I fix the following issue. Spending couple of hours everyday to fix with no luck so I hope one of you can help me out. :)

I have a listing with the following setup:

Item.js // 100% wide, 140px tall blocks with image background and text on it
CachedImage.js // storing images on the device using react-native-fs

I tried several things to make the scrolling smooth but it's not there yet. Implemented shouldComponentUpdate methods as well to reduce unnecessary rendering.

1. If I remove the images the scrolling is perfect
2. If I remove CachedImage and replace with normal Image component sending the actual CDN URL the scrolling is perfect, although there is a flash when refreshing the images (this is not ideal as there are a lot of images in my app and would eat the mobile bandwidth in a second)
3. If I increase renderAheadOffset to a very high number it works perfectly, because there is no rerender

I do think the issue is with the async getCachedPath() function, which returns the cached path based on the url.

**CachedImage.js**
```

constructor(props) {
	super(props);

	this.fetchImage = this.fetchImage.bind(this);

	this.state = {
		imagePath: null,
	};
}

componentDidMount() {
	this.fetchImage(this.props);
}

componentWillReceiveProps(nextProps) {
	if (this.props.source && nextProps.source &&
		!_.isEqual(this.props.source, nextProps.source)
	) {
		this.fetchImage(nextProps);
	}
}

shouldComponentUpdate(nextProps, nextState) {
	return this.state.imagePath !== nextState.imagePath;
}

async fetchImage(props) {
	const imagePath = await getCachedPath(props.source.uri);
	this.setState({ imagePath });
}

render() {
	const { imagePath } = this.state;
	return <Image source={{ uri: imagePath }} />;
}
```

**getCachedPath** (when I'm testing images are cached already so the only async command is await RNFS.exists(path) by that point)
```
const getCachedPath = async (uri: string): Promise<{ path: string }> => {

	// check if url is valid
	if (uri.indexOf('http://') === -1 && uri.indexOf('https://') === -1) {
		return uri;
	}

	const origFileName = uri.substring(uri.lastIndexOf('/'), uri.indexOf('?') === -1 ? uri.length : uri.indexOf('?'));
	const ext = origFileName.indexOf('.') === -1 ? '.jpg' : origFileName.substring(origFileName.lastIndexOf('.'));
	const pathPrefix = Platform.OS === 'android' ? 'file:' : '';
	const fileName = `${SHA1(uri)}${ext}`;
	const path = `${BASE_DIR}${fileName}`;
	const returnPath = `${pathPrefix}${path}`;

	const isExist = await RNFS.exists(path);

	// check if file exists
	if (isExist) {
		return returnPath;
	}

	// TODO: maybe we don't have to do this every time
	try {
		await RNFS.mkdir(BASE_DIR, { NSURLIsExcludedFromBackupKey: true });
	} catch (err) {
		fn.notify('CacheManager:CreateDir', err);
	}

	const downloadOptions = {
		fromUrl: uri,
		toFile: path,
	};

	try {
		const fileRes = await RNFS.downloadFile(downloadOptions).promise;

		if (fileRes.statusCode === 200) {
			return returnPath;
		}
	} catch (err) {
		console.log('err', err
	}
};
```

**RecyclerListView.js**
```
constructor(props) {
	super(props);

	this.dataProvider = new DataProvider((r1, r2) => r1 !== r2);

	this.layoutProvider = new LayoutProvider(
		index => 'Event',
		(type, dim) => {
			dim.width = width;
			dim.height = 140;
		}
	);

	this.state = {
		dataProvider: this.dataProvider.cloneWithRows(this.props.data),
	};
}

render() {
	return (
		<RecyclerListView
			dataProvider={this.state.dataProvider}
			layoutProvider={this.layoutProvider}
			rowRenderer={this.rowRenderer}
		/>
	);
}

```

**Comment by naqvitalha** [comment]
During scroll I/O operations can be highly detrimental to performance given the implementation. There is a lot happening here including the extra setState getting triggered. Also, why aren't you relying on Fresco's built in image caching?

**Comment by markhomoki** [comment]
Thank you for your reply. Since I wrote the original post I've changed my code a bit.

Now rather than setting the state on every render I set the cached URL during the redux action, so when there are new items fetched updates each item and replaces the CDN url to the cached local url. 

This way the renderItem is stateless and has a much better performance than before, but still when scrolling through the list of images it looks like the position of the grid jumps couple pixel up and down, although item height is set to 140px and the images are positioned absolute.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/8550329/43307683-db6d9250-9176-11e8-985c-06f29b7a657f.png">

I have 140 items at the moment using images less than 200kb. At start it loads 20 and every time user reaches the end loads another 20.

I haven't tested the built-in image cache as I've seen people wasn't 100% happy with it so I thought might be easier to write custom and have more control what and when to cache. I will try out the built-in one but I am not sure if it will perform better because now the cached URL stored in redux for each item so CachedImage.js has no fetchImage() method anymore.

**Comment by markhomoki** [comment]
I found a solution to fix my issue. Hopefully sharing it will help someone.

The issue was with the default <Image /> component that comes with react-native. The images were cached and when scrolling through the items I was just passing the local cached url of the image. Seems like the default <Image /> component is not fast enough with local images and it blocks the main thread until the requested images load synchronously causing jumps in the scroll experience.

My solution was to remove the caching function I wrote and only rely on react-native-fast-image library which caches and loads the cached url much faster. With this solution there are no more jumps and it has a constant 60fps.

I am closing this issue, thanks for your help.

**Comment by nehacurefit** [comment]
@markhomoki  - I am facing issue using react-native-fast-image library with recyclerlistview, sometimes my images are not renering with correct aspect ratio while doing scroll (with recycling). Can you please help if you have faced this issue too
