### ISSUE TITLE
Scroll doesn't work in physical devices

### ISSUE THREAD

**Issue by jackmatrix** [Flipkart/recyclerlistview#221]
I'm trying to scroll on my app running with `Expo` . Unfortunately, scrolling only works on emulator but not on physical devices. 

Are some people encountered the same issue ?

**Comment by naqvitalha** [comment]
Can you share the expo link? This issue in unheard of.

**Comment by jackmatrix** [comment]
Problem solved. The issue was caused because i 've wrapped my app under a `<DismissKeyboard></DismissKeyBoard>`Component. I removed this wrapper and all is working now.

Thanks.
