### ISSUE TITLE
[feature request] Listview with sticky headers like the Android contact page

### ISSUE THREAD

**Issue by gaodeng** [Flipkart/recyclerlistview#224]
https://github.com/renefloor/side_header_list_view

![example](https://user-images.githubusercontent.com/1118249/43648512-2d71d5ec-976d-11e8-8be6-5f09ddec2d1b.gif)

**Comment by naqvitalha** [comment]
This is not so difficult to build if you use the `onScroll` event and `onVisibleIndexesChanged` callback. Why don't you build a reusable utility and help all of us :)

**Comment by gaodeng** [comment]
@naqvitalha  
Hi, I have tried to implement this. but I  encountered some issue.
1.sticky headers need a higher z-Index, currently, every list row view is wrapped inside a view by recycler list,so I can't easily change the z-Index of the section header.
2.currently, recycler list manages the row render and reuse, but sticky headers need some API to mark it not be resued.

**Comment by naqvitalha** [comment]
You can use a custom `ItemAnimator` to change the zIndex. To prevent recycling just assign a unique type to each sticky row.

**Comment by arunreddy-flipkart** [comment]
Sticky headers have been added as a part of the latest release. Please go through the following guide on how to use them - https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/sticky
