### ISSUE TITLE
How would you specify flexible row heights

### ISSUE THREAD

**Issue by lingxiao** [Flipkart/recyclerlistview#226]
I am designing a comments section on react-native, similar to those found on instagram or twitter. Each row in the RecyclerListView must be flexible in height since I would like the full length of the content to be displayed. Is this possible? It would be difficult to define the height in `LayoutProvider`. Unless I precompute how many lines the comments are, for example here: https://www.npmjs.com/package/react-native-measure-text. However the function in this library is asyncronous, so I cannot use it inside the code block here, ie:

```
       this.layoutProvider = new LayoutProvider(

            idx => {
                const ht = await MeasureText.measure({
                      'hello world'
                    , width
                    , 16
                })
          }
```

**Comment by naqvitalha** [comment]
Just use `forceNonDeterministicRendering` mode. Just set it to `true`. Check the docs for more info.
