### ISSUE TITLE
DataGrid with Fixed Column.

### ISSUE THREAD

**Issue by max-zu** [Flipkart/recyclerlistview#227]
Is it possible to create table with fixed first column, and horizontally scrollable other columns. I tried different solutions with FlatList, and with two synchronized Flatlist. But it still wotks incorrectly.

**Comment by naqvitalha** [comment]
I don't why it can't be done. It is like sticky headers horizontally. You will need to write custom implementation. Not available out of the box.

**Comment by arunreddy-flipkart** [comment]
Sticky headers have been added as a part of the latest release. Please go through the following guide on how to use them - https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/sticky
