### ISSUE TITLE
styles are not applied when using useWindowScroll={true}

### ISSUE THREAD

**Issue by tafelito** [Flipkart/recyclerlistview#230]
when using `useWindowScroll={true}` the style prop is not passed down to the div container [here](https://github.com/Flipkart/recyclerlistview/blob/3a25674e3b3b7cfdcaabd0436b663db1f17bbc10/src/platform/web/scrollcomponent/ScrollViewer.tsx#L70). Is that intended?

**Comment by naqvitalha** [comment]
You can raise a PR. I think we missed it.
