### ISSUE TITLE
How to keep same scroll position, upon unknown number of RecyclerView data changes ?

### ISSUE THREAD

**Issue by Kimotn** [Flipkart/recyclerlistview#232]
Any solution same this problem in React native Recyclerlistview
https://stackoverflow.com/questions/47458429/how-to-visually-stay-on-same-scroll-position-upon-unknown-number-of-recyclervie

**Comment by naqvitalha** [comment]
Not possible out of the box. We will solve it in the future. It will take sometime.

**Comment by arunreddy-flipkart** [comment]
Closing in favour of #127
