### ISSUE TITLE
webview inside item of recyclerlistview

### ISSUE THREAD

**Issue by truongluuxuan** [Flipkart/recyclerlistview#236]
how to insert a webview to item of recyclerlistview? example code 
  `render() {
        return(
        <View  style={styles.outerContainer}>
            <View style={styles.container}>
                <Image style={styles.image} source={{uri: this.props.data.values.imgUrl}}/>
                <TimeWidget data={this.props.data.values}/>
				<Webview source={{baseUrl: '',html:"<h1>Hello</h1>"}}/>
                <Text style={styles.finalPriceText}>{this.props.data.values.cost}</Text>
            </View>
            <View style={styles.line}></View>
        </View>);
    }
}` 
 It not doing. Please help me, thank all bro

**Comment by naqvitalha** [comment]
It does work. Not getting your sample. Can you provide an expo snack to help me look into it?

**Comment by truongluuxuan** [comment]
In example of Lib : https://github.com/naqvitalha/travelMate/blob/sample/src/flights/FlightCard.js. I repleace `<Text style={styles.finalPriceText}>{this.props.data.values.cost}</Text>` by `<Webview source={{baseUrl: '',html:"<h1>Hello</h1>"}}/>`
It not run, you can try.

**Comment by arunreddy-flipkart** [comment]
Using static HTML requires the WebView property originWhiteList to ['*']. Please refer to the following link - https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#source
