### ISSUE TITLE
Render Dynamic components without setting disableRecycling=true

### ISSUE THREAD

**Issue by lingxiao** [Flipkart/recyclerlistview#239]
I am creating a RecyclerListView where the Items have a dynamic price ticker, so that on user event, the price ticker increments up. Currently the logic for a `FeedItem.js` is more or less:

	import AnimateNumber   from 'react-native-countup'

	export default class FeedItem extends Component {

		state = {
	          walletValue      : 0
	        , prevWalletValue  : 0
		}

		componentWillMount(){

			const walletValue = this.props.walletValue;
	        this.setState({ 
	              prevWalletValue : walletValue
	            , walletValue     : walletValue
	        })
		}

		invest = async () => {

			const update = await this.props.invest()

	        if (!update)
	            return false;

	        if (update.hasOwnProperty('walletValue')){
	            this.setState({ 
	                  prevWalletValue: this.state.walletValue
	                , walletValue    : update.walletValue 
	            });
	        }

		}

		renderTag = () => 
			<AnimateNumber 
				initial   = {this.state.prevWalletValue}
				value     = {this.state.walletValue}
				countBy   = {0.05}
			/>

		render = () => 
			<View>
				{this.renderTag()}
				<Button onPress = {this.invest} />
			</View>

	}

Note there is a local state within each `FeedItem` that increments on user action.  If I do not set `disableRecycling=true`, then the tag gets recycled when I scroll down and more `FeedItem`s are loaded on refresh,  this is concerning because the list is essentially rendering the first `FeedItem`'s price tag over and over again, and it's only when the user presses the button, does the `AnimatedNumber` update to the new `walletValue`.  Is there a way to prevent this behavior without setting `disableRecycling=true` and thus compromising performance?

**Comment by tomLadder** [comment]
have the same issue.

**Comment by mayconmesquita** [comment]
i have this problem too, i prefer state than props to handle component data

**Comment by arunreddy-flipkart** [comment]
Local states will cause issues with recycling because when a component is recycled, it is not unmounted but instead only updated with the new data. The older state will therefore persist in the new item and lead to unpredictable behavior. You could use a local store or the extendedState prop but make a note to not change extendedState too frequently for performance reasons.

**Comment by EhsanSarshar** [comment]
what about using context api. I haven't tested that but may work
