### ISSUE TITLE
Paging feature

### ISSUE THREAD

**Issue by khat33b** [Flipkart/recyclerlistview#240]
Is there a way to enable paging? Can this feature be implemented?

**Comment by haipengz** [comment]
There is a demo showing the feature of paging and infinite loading.
Infinite Loading/View Change (Expo): https://snack.expo.io/@naqvitalha/rlv-demo
You could check that out and try it yourself.

**Comment by khat33b** [comment]
I meant like the `ScrollView`'s `pagingEnabled` feature. [https://facebook.github.io/react-native/docs/scrollview#pagingenabled](url)

**Comment by naqvitalha** [comment]
You can just set `pagingEnabled={true}` on `recyclerlistview` and it'll work.

**Comment by khat33b** [comment]
`pagingEnabled` does not work on Android. See: https://github.com/facebook/react-native/pull/10999

**Comment by naqvitalha** [comment]
It does work on the horizontal one. Do you want it on the vertical one?

**Comment by khat33b** [comment]
Yes, I want for vertical.

**Comment by lauridskern** [comment]
How do I get it to work vertical?
