### ISSUE TITLE
How to provide dynamic data / data that changes over time

### ISSUE THREAD

**Issue by wmonecke** [Flipkart/recyclerlistview#243]
Hello!

I have a very basic question and that is: How do I provide new data? 

The list starts with an array of data of jobs that are nearby. However, these change once new jobs are added, thus the 'jobs' props change constantly. How do I update the component?

Do I do a new `this.setState({  dataProvider: dataProvider.cloneWithRows(myArrayWithNewData) })`?

Thanks!

**Comment by naqvitalha** [comment]
Yes, you need to create new `DataProvider` preferably by cloning just like you mentioned.
