### ISSUE TITLE
Scrolling fast causes images to mix up

### ISSUE THREAD

**Issue by CarterBland** [Flipkart/recyclerlistview#244]
I noticed that scrolling extremely fast causes images to get mixed up. Also loading new images in causes the next image to briefly be mixed up as well, not sure if this is an optimization issue on my side. Setting renderAheadOffset to like 5000 fixes the scrolling issue but not loading in new images and the text data looks to be correct just the images get mixed briefly.

**Comment by CarterBland** [comment]
That was it, thanks!

**Comment by tomball123** [comment]
Hi @naqvitalha, enjoying recyclerlistview so far. I've implemented what happens in ImageRenderer.js in your snack example, but it's not giving the smooth fade animation. Am I missing something obvious? I've pretty much done a direct copy of the behaviour in ImageRenderer.

**Comment by lovetofail** [comment]
Seems to be related to this issue https://github.com/facebook/react-native/issues/9195
