### ISSUE TITLE
recycling of interactive list items

### ISSUE THREAD

**Issue by artyorsh** [Flipkart/recyclerlistview#246]
Hi, great lib! Need help:

Trying to build fast-scrolling calendar view, but found out, that starting from some list item (month), list is trying to reuse some of previous month, so the item view is built incorrect.

**Actual behavior:**
As you can see on screenshots below, list is reusing January's view for June's view.

![image](https://user-images.githubusercontent.com/10753921/45485276-a9012200-b75f-11e8-8a45-e4b70d3316df.png)

![image](https://user-images.githubusercontent.com/10753921/45485293-b8806b00-b75f-11e8-9c23-e655e16c13c4.png)

By the way, I build this component using FlatList, so I'm sure that in core of component it works correct.

Can I achieve correct behavior using some magic of 'renderAheadOffset' prop or something?

**Comment by naqvitalha** [comment]
RecyclerListView tried to optimize perf by reusing both JS and Native component memory. You should just fix your `shouldComponentUpdate` and `rowHasChanged`. If you don't want recycling then you can set `disableRecycling={true}`. If you disable recycling perf will degrade severely.

**Comment by artyorsh** [comment]
@naqvitalha thanks for reply.

I think you should update guides. For my case the problem was that LayoutProvider's getLayoutTypeForIndex returned the same value for each month. Somewhere it looks like a true way, because the view of month is closely the same for each item.
So, if I understand correct, your list is recycling items that have the same item type. And in my case, to support correct days position for each month, I had to use a bit different logic for calculating item type.

**Comment by naqvitalha** [comment]
You can and should still do recycling. It is just about how you model your views to make them more recycling friendly. I had done a similar project sometime back, it isn't complete but will give you an idea: https://github.com/naqvitalha/CalendarDemo

**Comment by shubhamk1997** [comment]
> You can and should still do recycling. It is just about how you model your views to make them more recycling friendly. I had done a similar project sometime back, it isn't complete but will give you an idea: https://github.com/naqvitalha/CalendarDemo

In this project you are using getDataForIndex function form the _datProvider, I am not able to see that function. Is not implemented yet ?
