### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by JinHoSo** [Flipkart/recyclerlistview#250]
<img width="1021" alt="2018-09-28 2 34 20" src="https://user-images.githubusercontent.com/31269303/46189866-cc18fd80-c32b-11e8-9c5f-1ede9c17b923.png">

Hi, I've noticed the Recyclerlistview has memory leak issue, even unmounted items in this list view are still on js context as you can see the screenshot of js memory.
I guess the garbage collection isn't working for this list view.
Is it possible to remove all of the unmounted items from memory?

**Comment by naqvitalha** [comment]
It doesn't unmount everything. Eventually it will but this is an optimization. Unmount listview to see if there are external leaks.

**Comment by Place1** [comment]
@naqvitalha this is not an optimization. navigating in and out of a screen with a RecyclerListView will cause the app to crash once it consumes too much (leaked) memory.

**Comment by rmit-s3539777-abgier-avraha** [comment]
This library only works if you never plan to unmount the list. If you put this through a profile you can see just the memory consumed is never freed when the the list is unmounted.

**Comment by naqvitalha** [comment]
@Place1 What you are mentioning is different from issue raised here. The issue mentions items within the same list. Is this on web or RN? I can check this.

**Comment by tkforce** [comment]
@naqvitalha I'm currently experiencing this issue on React web project.

We use RecyclerListView in a react component that render <RecyclerListView/> conditionally, and when the first time (and only the first time) the condition turns from rendering <RecyclerListView/> to not rendering <RecyclerListView/>, we'll have a memory leak warning in browser console:
![image](https://user-images.githubusercontent.com/7017984/82776102-5ce70a00-9e7c-11ea-915f-41348044a935.png)

Dose it have something to do with RecyclerListView not unmounting everything after the parent component has already been unmounted?

**Comment by b15h0y** [comment]
any updates on this memory leak? I am facing the same issue here!

**Comment by AlenToma** [comment]
Im facing it to

**Comment by haibert** [comment]
guys has there been any fix provided to the memory leaks ?

**Comment by arsae** [comment]
same there..
any solution?

**Comment by alwyntan** [comment]
Still happening, much worse when the recyclerlistview is populated with videos

**Comment by naqvitalha** [comment]
Can you folks try version 3.2.0-beta.4 and let me know if these issues still exist?

**Comment by haibert** [comment]
@naqvitalha can you let us know by any chance if this library is being maintained and if there are plans to continue maintenance ?

**Comment by rizkhal** [comment]
`3.2.0-beta.4` solved for me, thanks a ton sir 🥂 

```json
{
    "recyclerlistview": "3.2.0-beta.4",
    "react-native": "0.65.0",
}
```
