### ISSUE TITLE
layoutProvider support width or height percentage?

### ISSUE THREAD

**Issue by tomleader** [Flipkart/recyclerlistview#251]
In the sample we can set the dim param w&h like
```
dim.width = 100;
dim.height = 80;
```
But when I set dim.width='100%' and it shows like the real width is 0

So the LayoutProvider really support width or height percentage?

**Comment by naqvitalha** [comment]
Check this: https://github.com/muskeinsingh/recyclerlistview-gridlayoutprovider
It might help you.

**Comment by muskeinsingh** [comment]
LayoutProvider would need actual dimensions here. 
@tomleader
