### ISSUE TITLE
incorrect first visible index

### ISSUE THREAD

**Issue by tafelito** [Flipkart/recyclerlistview#260]
Basically what's happening is when the list loads for the first time, I want to know if the first item of the list is visible on screen. The way I tried to check this was to find the first index with `findApproxFirstVisibleIndex` and then get the offset of that. 
The issue is that it's returning as the first visible index the last one instead of the actual first. The list uses forceNonDeterministicRendering={true} but I put an estimated height on the layout provider. 
If I increase the height to a higher number, then the first index is correct

You can see the example here

https://codesandbox.io/s/yq30j43lrx

**Comment by naqvitalha** [comment]
The problem is that binary search is used to accomplish this for perf reasons in very large lists. You can always do a linear search. Should be very easy. Let me know if you need help.

**Comment by tafelito** [comment]
Where would you do that exactly? 

What I'm trying to do is basically an inverted infinite load. Because the inverted is not yet implemented, I'm handling it on the scroll event, so when you get to the first position, trigger the load more.

If you know a better way of doing that, please let me know

**Comment by arunreddy-flipkart** [comment]
The method _findFirstVisibleIndexUsingBS can be changed to _findFirstVisibleIndexLinearly in the following line. https://github.com/Flipkart/recyclerlistview/blob/master/src/core/ViewabilityTracker.ts#L108
