### ISSUE TITLE
Skeleton screens (interface previews)

### ISSUE THREAD

**Issue by Fanda36** [Flipkart/recyclerlistview#263]
Hi,
is it possible to predefine static list item (skeleton preview), which will be (super fast because it will be static and cached) render until current item will be render?

Something like this:
![image](https://user-images.githubusercontent.com/3972954/47016127-16351800-d14f-11e8-9de9-aec743480cea.png)

Thank you.

**Comment by Fanda36** [comment]
I have big list (1000+ items) and if I scroll fast then is there white screen. I tried render dummy data, but it still waited when will be rendered date before (so result was same). But I moved from React Native to native, because it is possible limitation of React Native.

**Comment by stanislavgalin** [comment]
The same for me.
I copied the sample code and when scrolling really fast, I can see a lot of blanks and it makes an impression of blinking which is a bad UX.

Is there any solution now ?

**Comment by kabus202** [comment]
Yes, same here. Is there any workaround?

**Comment by VenomApps** [comment]
Anything been waiting on this for a while. The blinking between scrolling fast really takes away from the experience

**Comment by arunreddy-flipkart** [comment]
Hii Please go through the performance guide. In particular, Please make sure dev=false and minify=true before you start your benchmarking.
