### ISSUE TITLE
Update view with state update when the state is kept by the class rendering RecyclerListView

### ISSUE THREAD

**Issue by lingxiao** [Flipkart/recyclerlistview#267]
I have a list of items and I would like the pressed item to "light up" when pressed, and "darken" when another item is pressed. Each item can change state when the state is persisted inside the item, ie:

```
     class Item extends Component {
         state = { activated : false }
        onPress = () => this.setState({ activated : true })
        render = () => <View/>
     }
```

However I would like to keep the state in the parent class containing the `RecyclerListView` instance, ie:

````
    class Feed extends Component {
        state = { activatedItem : false }
       render = () =>
             <RecyclerListView renderItem ={(key,data) => <Item data={data} activated ={this.state.activatedItem === data}/>} ... />
    }
````
However as written the items do not update when `state = { activatedItem:false}` is updated, presumably because the RecyclerListView is handling the state? Note the same code with regular ListView updates as expected.

**Comment by naqvitalha** [comment]
Look into the `extendedState` prop to get this done. You can pass this to the children for them to figure out whether they light up or not. Be careful not to update `extendedState` too frequently to avoid performance issues.

**Comment by arunreddy-flipkart** [comment]
Please refer to the example for using the extendedState prop in the following expo - https://snack.expo.io/@arunreddy10/rlv-extendedstate-demo. Closing
