### ISSUE TITLE
Change scrolling sensitivity

### ISSUE THREAD

**Issue by Yarkhan** [Flipkart/recyclerlistview#268]
I have a list of touchables that take the user to another screen when pressed. However, sometimes taps into the list are making the list scroll instead firing `onPress` events. Is there a prop or a way to give priority to the onPress events instead scrolling? 

Thanks for this awesome library

**Comment by naqvitalha** [comment]
Is this on web on react native?

**Comment by Yarkhan** [comment]
Native. But the issue I was having has since gone from my app. I'm closing this.
Thank you!
