### ISSUE TITLE
Keep scroll position at top

### ISSUE THREAD

**Issue by miladrasooli** [Flipkart/recyclerlistview#271]
Hi , 
I'm using RLV to display users messages and I'm using `ScaleY:-1` so everything is reversed , everything is working fine until I replace whole new messages in the list and I want the list to keep the scroll position at top of the list but after loading it loads from bottom of the list, is there any solution to this issue?

**Comment by naqvitalha** [comment]
You can always manually call `scrollToOffset` with 0 offset.

**Comment by miladrasooli** [comment]
Thanks for the reply but it's jumpy and not very elegant :(

**Comment by z98361** [comment]
same #44 and not yet :(

**Comment by arunreddy-flipkart** [comment]
Closing in favour of #44.
