### ISSUE TITLE
Allow types for Scrollview properties

### ISSUE THREAD

**Issue by cmcaboy** [Flipkart/recyclerlistview#278]
I am using RecyclerListView with Typescript, but I am running into Typescript errors while trying to use refreshControl, but Typescript says it is invalid. Is it possible to add types onto RecyclerListView's inherited scrollview properties?

<img width="414" alt="recyclerlistview_refreshcontrol" src="https://user-images.githubusercontent.com/1489169/49347726-db3f6300-f66e-11e8-9c93-43bcfee17510.png">

**Comment by naqvitalha** [comment]
Use the latest beta version. There you have a new prop `scrollViewProps` which can be used to pass the object to internal ScrollView.

**Comment by cmcaboy** [comment]
Looks like that fixed my issue. Thanks!

![image](https://user-images.githubusercontent.com/1489169/49584301-da395a80-f928-11e8-8a51-6edcc63cef96.png)
