### ISSUE TITLE
Add support for sticky headers

### ISSUE THREAD

**Issue by smkhalsa** [Flipkart/recyclerlistview#28]

**Comment by naqvitalha** [comment]
Can you provide more details on what you're expecting. Sticky headers?

**Comment by joonhocho** [comment]
@naqvitalha I think he means sticky headers and I think it will be a great addition too.

**Comment by smkhalsa** [comment]
@naqvitalha yes, that's what I meant. I've adjusted the title accordingly.

**Comment by naqvitalha** [comment]
We plan on adding add remove animations first. Post that we'll try to pick this up. No good use case has come up yet @Flipkart

**Comment by sm2017** [comment]
@naqvitalha I want to implement a simple version for my use case
How can I detect that which item is top and which is coming in view report and which is go out?

**Comment by AbdallaMohamed** [comment]
I'll be closely keeping an eye on this issue.

**Comment by AbdallaMohamed** [comment]
@sm2017 You can use the `onVisibleIndexesChanged` callback, which return the type `TOnItemStatusChanged`. This is exactly what you're looking for.

`export declare type TOnItemStatusChanged = ((all: number[], now: number[], notNow: number[]) => void);`

**Comment by sm2017** [comment]
@AbdallaMohamed Thanks

**Comment by naqvitalha** [comment]
We'll continue tracking this in #72. Closing.
