### ISSUE TITLE
Re-Rending Wrong Postion

### ISSUE THREAD

**Issue by leifermendez** [Flipkart/recyclerlistview#284]
<img width="489" alt="screen shot 2018-12-11 at 19 27 20" src="https://user-images.githubusercontent.com/15802366/49821467-cbb0d000-fd7a-11e8-801d-1b0531945a4a.png">
Hello again and thanks for the excellent component. I have another problem I'm using FireBase Database to get the data from a small list. But I have a problem when I scroll and return to the place I notice that the component of List of likes has been rendered in the following row and not in the one that really belongs. Thank you
Video: https://youtu.be/VUeRcu_9hqg
Sorry Bad English

**Comment by arunreddy-flipkart** [comment]
Could you provide us an expo snack to reproduce the issue.
