### ISSUE TITLE
animateWillMount not trigger

### ISSUE THREAD

**Issue by iamiota** [Flipkart/recyclerlistview#288]
Thanks for the library, it's really cool.
I am working on a list of react native 3D cards that need to be implemented with zIndex, I used itemAnimator and encountered some problems:
1. The return in animateWillMount does not take effect.
2. animateWillMount will not fire after some index, this index depends on the height set in LayoutProvider.

https://codesandbox.io/embed/2v3jywq9q0

I didn't find an example of using itemAnimator, so I'm not sure if this is a bug.
Sorry for my poor English, thank you.

**Comment by arunreddy-flipkart** [comment]
The animateWillMount method of the itemAnimator is called before the list item is mounted. Once the initial items are mounted, the views which have gone outside the viewport after scrolling are reused to render the new items. Therefore for the these items which are being rendered using the recycled views, mounting will not occur and therefore animateWillMount would not be fired.
