### ISSUE TITLE
[forceNonDeterministicRendering] how to remove animation of items moving to their initial position?

### ISSUE THREAD

**Issue by mmamoyco** [Flipkart/recyclerlistview#292]
There is need to remove animation of items moving to their initial position while first time rendering ( when forceNonDeterministicRendering set to true)

**Comment by RichardFevrier** [comment]
Any suggestions @naqvitalha ? Using BaseItemAnimator() as itemAnimator does not change anything and I could not see any reference about Animated or LayoutAnimation related to this issue =/

**Comment by askarhu** [comment]
I have this same issue and it's really really slow to animate, would rather not animate. I don't know what that itemAnimator takes to set this to ignore animations.

**Comment by singhmuskein** [comment]
https://github.com/Flipkart/recyclerlistview/blob/3b4db861d0cae5da7ce5f330d21cec91f191add8/src/core/RecyclerListView.tsx#L679

Check this out.

**Comment by arunreddy-flipkart** [comment]
Please pass an empty Item Animator to disable all animations. Refer to https://github.com/Flipkart/recyclerlistview/blob/3b4db861d0cae5da7ce5f330d21cec91f191add8/src/core/RecyclerListView.tsx#L679

<img width="739" alt="Screenshot 2019-10-15 at 3 24 22 PM" src="https://user-images.githubusercontent.com/56394019/66821490-20efdc00-ef60-11e9-9caa-87d14ab598b2.png">

**Comment by siddharth-kt** [comment]
any solution guys ?

**Comment by siddharth-kt** [comment]
Hi @naqvitalha,
Can you do something about this when forceNonDeterministicRendering set to true and sizes provided in LayoutProvider are not correct then its takes time to get back to its real size and is visible to user. Is there any way to completely dismiss animation since passing new BaseItemAnimator() does not improve anything.

Thanks
