### ISSUE TITLE
How to use extendedState of prop

### ISSUE THREAD

**Issue by leoxiaoping** [Flipkart/recyclerlistview#293]
Is there a demo to show how to use extendedState of prop？
I found it‘s different with flatlist‘s extraData.

**Comment by johnlim5847** [comment]
Hey did you manage to find out how to use `extendedState` as props?

**Comment by arunreddy-flipkart** [comment]
Hi,

Please refer to the following expo on how to use the extendedState prop - https://github.com/Flipkart/recyclerlistview/issues/293. Be careful not to update extendedState too frequently to prevent performance issues.

**Comment by pavermakov** [comment]
@arunreddy10 thank you so much!
