### ISSUE TITLE
How can I use dynamic height for layout provider?

### ISSUE THREAD

**Issue by ErHarinderSingh** [Flipkart/recyclerlistview#295]
I want to be height of the list-item dynamic.
In layout provider I set it to 50 but when the I increase font size text overlapped with next line. It is because list item height remains 50 because it is set by layout provider.

How can I made list item height dynamic??
Any alternative to forceNonDeterministicRendering=true ?

Please help asap.

**Comment by kabus202** [comment]
I was also wondering if this is possible

**Comment by muskeinsingh** [comment]
If you can somehow compute the exact height your text element will take post rendering, you can set forceNonDeterministicRendering as false (do check getDataForIndex() functionality that can be used within a layout provider). But if you are not really sure about the exact height and it's quite variable, I would suggest to let RecyclerListView take care of it and set non deterministic rendering as true. That, obviously, comes with a little performance hit when compared with the deterministic approach. 

@naqvitalha please add if I missed something here!

**Comment by ErHarinderSingh** [comment]
forceNonDeterministicRendering={true} shows next line in same line. And Lines are animating on first load.

Means If second line has 4 characters only, It automatically adjust in first line and animating.
Any help please!! 

It can be possible if state change can also change the height of the layout provider. How can I achieve this?

Or any other way?

**Comment by naqvitalha** [comment]
@ErHarinderSingh In the first render pass your estimates are considered for item placement and then actuals are used. One quick hack could be to disable animation and hide the list view for 1-2 frames. Not that I recommend it :)

**Comment by VictorQueiroz** [comment]
I could not find a way to render rows vertically when using `forceNonDeterministicRendering` as true. Any help?

**Comment by arunreddy-flipkart** [comment]
@VictorQueiroz Could you provide a snack expo for us look at? Ideally the rows should render irrespective of whether forceNonDeterministicRendering is set to true or not
