### ISSUE TITLE
How to find index of item by screen coordinates?

### ISSUE THREAD

**Issue by Komeyl94** [Flipkart/recyclerlistview#302]
I have a PanResponder on a button on every item of the list (A news feed kind of list), and I need to have the pressed item's index inside PanResponder and since I cant pass params to it, I need to find the index of pressed item by the screen coordinate.
I have the screen coordinate and the scroll offset I can calculate item's position relative to the top.
So is there any way to get the info of the calculated heights of rendered items? Or maybe their positions?
Btw I've tried putting it all inside a component and it works! but it slows down the whole list by a lot, so I'm trying to put it all together inside the RowRenderer without using any external components.

**Comment by arunreddy-flipkart** [comment]
Hi,

The heights and positions of the rendered items can be obtained from the layoutmanager. You could create a ref to the RLV and then call ref._virtualRenderer.getLayoutManager().getLayouts[] to get the layouts of all indexes. Each Layout consists of its positions x and y and the height and width of the layout.
