### ISSUE TITLE
Export StickyContainer

### ISSUE THREAD

**Issue by osdnk** [Flipkart/recyclerlistview#308]
StickyContainer is not exported in main index.js. I consider it a bit dirty to import some internal files (Although it's still beta)

**Comment by ananyachandra14** [comment]
Yup missed it! Will be adding it.

**Comment by arunreddy-flipkart** [comment]
StickyContainer is currently not supported for web and is therefore exported separately. Exporting it in the main index.js would lead to an overhead of maintaining separate platform based index.js files.
