### ISSUE TITLE
No Solid Example For Stable IDs

### ISSUE THREAD

**Issue by VenomApps** [Flipkart/recyclerlistview#312]
Hey, I was looking over all available documentation and no concrete example for how to use stable IDs was provided. For my scenario I push a lot of changes to a list so. List 1 has 1, 2, 3, 4 but after I change data the new list may be 0, 1, 2, 3, 4, 5 where one item was added and one was deleted. I am looking for a concrete example of how to implement stable ids for this given this operation happens frequently and my items all have unique ids.

**Comment by naqvitalha** [comment]
All you have to do is return the id associated with an index. You will ideally infer this from your data.
Simple example (pseudo code):

```js
getStableId(index) {
     let data = getDataForIndex(data);
     return data.id;
}
```

Pass this to the data provider. That's all you need to do. Behind the scenes RLV will optimise container selection based on this new info. I understand documentation scarcity. We are working to ramp it up.

**Comment by VenomApps** [comment]
My current dataProvider looks like:
this.dataProvider = new DataProvider((r1, r2) => {
    return r1.id !== r2.id;
 });
Not sure what you mean by pass it to the data provider.

**Comment by naqvitalha** [comment]
You can pass `getStableId` as second argument to dataProvider constructor.

**Comment by VenomApps** [comment]
I need a complete example of how to implement stable ids for my list. Currently I have a list of roughly 75 items that changes as new data comes in pushing 1 item to the top of the list and popping the oldest item. I need to implement stable id's so every single of the below 74 items are not re-rendered.

**Comment by DaveLomber** [comment]
@naqvitalha would be great to have a complete example in a README along with others existing information. Thanks

**Comment by thekevinbrown** [comment]
Is this out of beta? It looks like the `DataProvider` implementation in 1.3.4 only takes one argument:

https://unpkg.com/recyclerlistview@1.3.4/src/core/dependencies/DataProvider.ts

**Comment by arunreddy-flipkart** [comment]
@thekevinbrown DataProvider takes two arguments with the second being optional in the latest release. Please refer to the following expo provided in the readme for an example of the getStableID parameter of the dataprovider - https://snack.expo.io/@arunreddy10/19bb8e.

**Comment by paddy57** [comment]
@arunreddy10 I'm removing an item from the recycler list and when I do that it gives me two warning
1.Encounter two children with the same key 
2.possible stable id collision. 
I have 2nd argument of stable id to data provider as given in the snack  https://snack.expo.io/@arunreddy10/19bb8e 
What can be done here ?

**Comment by thekevinbrown** [comment]
@paddy57 I'd suggest that your stable IDs should be stable, in that two items never share the same ID. The ID should come from the data, not from an array index.

**Comment by ehsan6sha** [comment]
> @arunreddy10 I'm removing an item from the recycler list and when I do that it gives me two warning
> 1.Encounter two children with the same key
> 2.possible stable id collision.
> I have 2nd argument of stable id to data provider as given in the snack https://snack.expo.io/@arunreddy10/19bb8e
> What can be done here?
> 
> If I remove the 2 nd argument of stable id to data provider, I don't get any of the warnings

Can you please share the piece of code for removing an item? I am trying to achieve the same but item does not get removed from the list.
