### ISSUE TITLE
Spelling mistake: "onEndReachThreshold" should be "onEndReachedThreshold"

### ISSUE THREAD

**Issue by holgersindbaek** [Flipkart/recyclerlistview#317]
"onEndReachThreshold" should be "onEndReachedThreshold" in the props section of the Readme.

**Comment by holgersindbaek** [comment]
Another spelling mistake:

"renderAheadOfOffset" should be "renderAheadOffset".

**Comment by naqvitalha** [comment]
This happened in a recent PR. Fixed now.
