### ISSUE TITLE
Please bring back renderFooter

### ISSUE THREAD

**Issue by Frekansapp** [Flipkart/recyclerlistview#319]
renderFooter props should be come back it's so easy to use. Is there any chance to come back ? we could use stickyfooter and renderfooter both

**Comment by naqvitalha** [comment]
It's already there. What's the issue? Do you see regression somewhere?

**Comment by Frekansapp** [comment]
> 
> 
> It's already there. What's the issue? Do you see regression somewhere?

renderfooter was running in version 1.3.4, but it doesn't work after switching to Version 2.0.0-beta.3.there is no renderFooter property
![ekran alintisi](https://user-images.githubusercontent.com/43651689/53942501-01d8c400-40cc-11e9-86e1-edfa35e93d9d.PNG)
![ekran alintisi2](https://user-images.githubusercontent.com/43651689/53942502-01d8c400-40cc-11e9-89a9-0c39f6624fe6.PNG)

**Comment by naqvitalha** [comment]
Check this: https://snack.expo.io/@naqvitalha/footer-test
I can render footer in `2.0.0-beta.4`
