### ISSUE TITLE
How to update only the changed row ?

### ISSUE THREAD

**Issue by iOSUser110** [Flipkart/recyclerlistview#323]
I hve tried with 
  dataProvider: new DataProvider((r1, r2) => {
                // Console.log(r1.isFav)
                // Console.log(r2.isFav)
                return r1 !== r2
            }).cloneWithRows(this.props.values.data)

but it never returns true , it always show data for both r1 and r2 changed , even if the new data arrives, old data not maintain

**Comment by iOSUser110** [comment]
ad extendedState={this.state} is for rendering the all cells right ?
i want to render only cell those are changed not all

**Comment by sikeeoh** [comment]
I think it's an issue caused by shallow copying.
I used this.
`import cloneDeep from 'lodash/cloneDeep';`
`
let result = cloneDeep(providerList);
      result.forEach(data => {
          data.liked = true
      });

this.setState({
        dataProvider: this.dataProvider.cloneWithRows(result)
      });
`

**Comment by naqvitalha** [comment]
@sikeeoh Correct. References are actually not changing, dataProvider will not clone the array itself. 
@iOSUser110  Btw if the data item is not changing why do you want re-render?

**Comment by sathishu37** [comment]
@iOSUser110 did you figure it out this issue? I have same issue

**Comment by mayconmesquita** [comment]
I also have this problem.

**Comment by arunreddy-flipkart** [comment]
The rowHasChanged parameter passed to the dataProvider is doing a shallow comparison of the references and therefore returns false if the reference is the same. Deep copying would solve the issue or you could have a different rowHasChanged method which checks more than just the references such as r1.id !== r2.id.
