### ISSUE TITLE
How can we reverse the nature of RecyclerListView in React-Native ?

### ISSUE THREAD

**Issue by iAmLakshya** [Flipkart/recyclerlistview#325]
I am trying to make chat UI using RecyclerViewList in React Native. I am not able to figure out how to reverse the RecyclerViewList. By reverse I mean, user scrolls from bottom to top (to view old messages) and when new data is dynamically inserted at the bottom, it automatically keeps the scroll to the end.

**Comment by naqvitalha** [comment]
Easiest way is to apply a `ScaleY: -1` transform on RLV and each item inside it.

**Comment by DaveLomber** [comment]
Is there a way to do the same for Web?
