### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by murtraja** [Flipkart/recyclerlistview#326]
Hello,

I am not able to see any output while using recyclerlistview on Firefox, but I am able to see the correct output in Chrome, Android & iOS.

I wasn't able to get any errors on the console, so I was hoping someone could help me where I can keep some logs to debug this issue

I am using 1.3.4

**Comment by murtraja** [comment]
Well, if I take the list out of the Modal, then it works on Firefox as well, but I need to display the list inside the modal

**Comment by muskeinsingh** [comment]
Could you help us with a snack or a repro to debug this?

**Comment by murtraja** [comment]
code sanbox link [here](https://codesandbox.io/embed/zroy0lr02m)
direct link [here](https://zroy0lr02m.codesandbox.io/)

Works in Chrome Version 69.0.3497.100 (Official Build) unknown (64-bit)
DOESN'T work in Firefox 66.0.1 (64-bit)

**Comment by murtraja** [comment]
Please click on "Tap to change view type" to open the modal and then check the behaviour on both, Chrome and FF.
Also note that when the list is outside the modal, everything works fine

**Comment by murtraja** [comment]
I think, this is mostly some styling issue where the list is not getting proper height/width, but I would love to hear your thoughts on this or if there are any FF specific workarounds

**Comment by murtraja** [comment]
@muskeinsingh, did you get a chance to look at this issue?

**Comment by arunreddy-flipkart** [comment]
The issue appears to be with either react native web or the library being used for the model - modal-enhanced-react-native-web. It is working fine in the current version of Firefox.
