### ISSUE TITLE
How to update single element rather then update all items in dataProvider?

### ISSUE THREAD

**Issue by sathishu37** [Flipkart/recyclerlistview#336]
Hi I have an array of object in dataProvider like
`[{item:"A",count:0},{item:"B",count:0}...{item:"Z",count:0}]`.
I have changed one element count to 1 now,  I want to render only one item rather than re-rendering all items.
'extendedState' renders all items it causes slow rendering.

**Comment by naqvitalha** [comment]
If the change is at row level data then you should have the right check inside rowHasChanged method.

**Comment by muhammadwafa** [comment]
@sathishu37 Hi bro, did you find any help for this ?
