### ISSUE TITLE
 lagging on iPhone SE on initial scroll

### ISSUE THREAD

**Issue by jennykortina** [Flipkart/recyclerlistview#337]
On an iPhone SE (not sure if this happens on other iPhones, this was just the type I have and tested on) the TestFlight build of my app list view the initial scroll is noticeably laggy and then subsequent scrolls there is no lag.  I've been working on trying to fix this for a week now and can't seem to get it scroll smooth and it's driving me nuts.  Here's a [video](https://youtu.be/Fg3-42Ko9DM)

I'm using Expo.  Since it only happens on initial scroll, I thought the images might be the issue so I've tried[ pre-caching the images ](https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets/)and[ bundling the assets with build](assetBundlePatterns) but neither of those helped improve performance.

Here's:

- [app.json](https://gist.github.com/jennykortina/702d936aa8b2af0cba2673f150e22c82)
- the [component](https://gist.github.com/jennykortina/a2571bb062b1845c974240993492c29b) calling recyclerlistview
- and my data is an array with 68 items structured like this:

```
export const deck = [
  {
    english: "Bharadvaja's Twist",
    sanskrit: 'Bharadvajasana I',
    translation: {
      Bharadvaja: 'one of seven legendary seers, who composed  hymns collected in the Vedas',
    },
    sanskritPronunciation: 'bah-ROD-va-JAHS-anna',
    img: require('../../assets/img/poses/bharadvajasana_1.png'),
    icon: require('../../assets/img/pose_icons/bharadvajasana_1.png'),
    audio: {
      sanskrit: require('../../assets/audio/san_bharadvajasana_1.mp3'),
    },
  }
]
```

any help would be greatly appreciated

**Comment by naqvitalha** [comment]
The output of _renderRow has a key defined. Please try after removing that. Also, you could've read the perf guide it is mentioned there.

**Comment by jennykortina** [comment]
@naqvitalha thanks!  I did read the perf guide serval times but I guess I obviously overlooked not having `key` defined on `_renderRow` I've removed the `key` and it is more performant but still choppy/laggy on first scroll.  Is there anything else you would recommend?

Thanks so much!

**Comment by naqvitalha** [comment]
Can you check perf monitor to see if you're dropping JS frames or just UI frames? Can you try creating the same template in expo so that I can debug? This doesn't look like a RLV problem.

**Comment by jennykortina** [comment]
Hi, 

I ended up getting this working as expected.  [the component updated component](https://gist.github.com/jennykortina/ce6a69823675a3f9b94504bd07d6d30d)

Thanks for the help!
