### ISSUE TITLE
onEndReached not triggered within viewport

### ISSUE THREAD

**Issue by abhinavrastogi-harness** [Flipkart/recyclerlistview#338]
We are using RecyclerListView for both infinite-scrolling and recycling.

When we render a small number of items, `onEndReached` is not getting triggered even if there is space to render more items.

Expectation:  `onEndReached` should keep getting called if there is space to render more items.
Actual Behaviour: `onEndReached` is only called once when there are zero items.

Reproducible example: https://codesandbox.io/s/kk5qo9kj67

**Comment by naqvitalha** [comment]
It seems to be failing with `useWindowScroll={true}`. I am looking into it.

**Comment by naqvitalha** [comment]
@abhinavrastogi-harness Use `recyclerlistview@2.0.1-alpha.1`. I have released a quick patch.

**Comment by abhinavrastogi-harness** [comment]
@naqvitalha this works! thanks! how soon can we get this merged?

**Comment by naqvitalha** [comment]
PR is raised already. Should be done today.

**Comment by abhinavrastogi-harness** [comment]
@naqvitalha Was this merged and released?

**Comment by naqvitalha** [comment]
Change is in master and is part of the 2.0 beta.

**Comment by arunreddy-flipkart** [comment]
Assuming this to be resolved. Closing.
