### ISSUE TITLE
How to integrate with GraphQL?

### ISSUE THREAD

**Issue by manzoorwanijk** [Flipkart/recyclerlistview#343]
I use `graphql()` and `<Query>` from [react-apollo](https://github.com/apollographql/react-apollo). I tried a few options but couldn't succeed in feeding the data to RLV. Can you please give me an example with data from GraphQL?

**Comment by jariwalabhavesh** [comment]
@manzoorwanijk : How finally do that can you provide example code.??

**Comment by jariwalabhavesh** [comment]
I found this https://codesandbox.io/s/m5rv8 which explain how we can use graphql with recyclerlistview
