### ISSUE TITLE
Use ViewPagerAndroid as 'ScrollView'

### ISSUE THREAD

**Issue by jwhscholten** [Flipkart/recyclerlistview#344]
Would it be possible to use React Native's ViewPagerAndroid as pager component with RecyclerListview virtualization?

**Comment by naqvitalha** [comment]
Can't you just use `ScrollView` with `pagingEnabled`? Are you facing any issues with that?

**Comment by jwhscholten** [comment]
I'm using that solution now. Problem is I'm using a gestureResponder inside each 'page' (swipe, pinch, doubletap etc.). The swipe to next page event is captured by my gestureResponder, this way the recyclerListview only responds to quick swipes. Delegation of touch events works perfect when using a viewPagerAndroid.

**Comment by arunreddy-flipkart** [comment]
We are not considering taking this up in the near future. We would be happy to pull in a PR
