### ISSUE TITLE
What is the best way to show an empty screen if the data provider is empty

### ISSUE THREAD

**Issue by Yasir5247** [Flipkart/recyclerlistview#352]
```
_rowRenderer = (type, data) => {
     console.log(data);
     if (this.props.friendsNoti.getSize()) {
             return <UserLikedRow
                    data={data}
                    showProduct={this.props.onProductHandle}
             />
      } else {
            return <EmptyScreen
                   title={'No Liked Products'}
             />
      }
};
```

1- I can't console log data inside the "_rowRenderer" function
2- having (this.props.friendsNoti) as the dataProvider. here i am trying to see if there is data. if not i show empty view else i show actual data. 
But this does't work
What is the best way to handle this?

**Comment by mayconmesquita** [comment]
I'm using this to achieve that:

```javascript
{ !this.state.listEmpty &&
    <RecyclerListView
        dataProvider={this.state.dataProvider}
        rowRenderer={this._rowRenderer}
    />
}
```

**Comment by meatspincom** [comment]
@mayconmesquita 

Its awful for your performance 😬. It will trigger reinitialize RecyclerListView every time when listEmpty changes ... Also you can use data.length === 0 to check if your data is empty instead of declaring a new state field

**Comment by mayconmesquita** [comment]
@meatspincom it's a provisional solution and the pull to refresh works completely.
Do you have some tip to avoid RecyclerListView reinitializing?

**Comment by mayconmesquita** [comment]
@meatspincom it's a provisional solution. Do you have some tip to avoid RecyclerListView reinitializing?

**Comment by meatspincom** [comment]
@mayconmesquita Unfortunately, I have no idea how to avoid RecyclerListView reinitializing and display save ability to show empty screen. That's why i'm here..

**Comment by meatspincom** [comment]
Maybe you can do like

```jsx
< RecyclerListView
        ...
        renderFooter={!data ? render(<Text>Ничего не найдено</Text>) : render(null)}
        ...
/>
```

But I don't know what's about perfomance.. Will in initialize list or not?

**Comment by arunreddy-flipkart** [comment]
Thanks @dan-maximov for the example. Currently, this is the best way to show an empty component if the data provider is empty. Keep in mind, the pull to refresh functionality would not be available as the footer is outside the scrollview. Closing in favour of #204.

**Comment by weinixuehao** [comment]
@arunreddy10 but footer not fit full height?
