### ISSUE TITLE
Is there any exported android demo such as apk or released app in google play?

### ISSUE THREAD

**Issue by kharazi** [Flipkart/recyclerlistview#355]
Hi, 
Many thanks for your library. I got an error when I trying to run [this demo](https://snack.expo.io/B1GYad52b) on Expo. the [basic infinite loading example](https://snack.expo.io/@naqvitalha/rlv-demo) works but it's not fairly complicated enough to make sense about performance. 

Here is my traceback when I trying to run the demo: (duplicate of https://github.com/Flipkart/recyclerlistview/issues/100)
![drag](https://user-images.githubusercontent.com/1734380/59146955-fae28a00-8a09-11e9-89c5-155d4fc77f72.jpg)

**Comment by naqvitalha** [comment]
Try search on Flipkart app: https://play.google.com/store/apps/details?id=com.flipkart.android&hl=en_IN

**Comment by arunreddy-flipkart** [comment]
Closing.
