### ISSUE TITLE
Getting rowRenderer x and y values

### ISSUE THREAD

**Issue by Badri2107P** [Flipkart/recyclerlistview#356]
I am developing a react-native app in which i need to implement videos, texts, images in recyclerlistview. I need to autoplay the video once the video reaches the current index. i used onVisibleIndexesChanged to find the current index to do that, but as the app contains multiple content heights, it is not returning current index as i scroll some time. 
So i am thinking of getting the x and y positions of rowRenderer and updating the video player once the scroll position reaches certain y position, i am able to get the scroll position use scroll native event. But i couldn't get x and y positions of rowRenderer even though i am able to view those props on react-native-debugger. I tried viewing the props and passing down it as props but no luck.
![capture1](https://user-images.githubusercontent.com/19424571/59199733-4cc71380-8bb4-11e9-9c55-7cae5c6dea16.PNG)
The rowRenderer contains y value but i don't know how to get that any help would be appreciated.

**Comment by naqvitalha** [comment]
You can query for actual layout info using `getLayout` method on RLV. The method returns value in constant time and thus is safe to call inside `onScroll`

**Comment by AshishMohan89** [comment]
> 

did you find any solution to this?
