### ISSUE TITLE
about animation

### ISSUE THREAD

**Issue by WynnLin** [Flipkart/recyclerlistview#358]
can you provide a demo with itemAnimator props

**Comment by osdnk** [comment]
take a look? https://github.com/rainbow-me/rainbow/pull/108/files

**Comment by arunreddy-flipkart** [comment]
Please refer to the following expo provided in the readme regarding the itemAnimator lifecycle.

**Comment by ehsan6sha** [comment]
> Please refer to the following expo provided in the readme regarding how to use the itemAnimator
> and its lifecycle - https://snack.expo.io/@arunreddy10/19bb8e.

Not sure why this is referred to as an example of itemAnimator. when running it there is no animation happening and the cycles are not called neither. can you elaborate?
