### ISSUE TITLE
Freezing/Breaking on iPhone X

### ISSUE THREAD

**Issue by dancherb** [Flipkart/recyclerlistview#359]
After scrolling down a certain amount, items stop loading and you're scrolling through white space, and the app itself freezes (other buttons on the javascript side are no longer responsive, though scrolling is still possible because this is on the native side I believe). This only affects iPhone X on both the simulator and hardware, other platforms (Android; iPhone 5S; iPhone 8+) are all good.

Tested on both 1.3.4 and the latest 2.0.0 beta, same issue.

**Comment by dancherb** [comment]
I noticed in another part of the app, where I'd added support for renderHeader via the recyclerlistview source code and added a significant header, this freezing did not occur. Copying this component over but making it invisible now seems to fix the issue where it was happening - just leaving a big white gap and no idea what's actually going on.

Note that the issue persists without the edit on the source code, and the header component only "solves" the issue in certain cases (e.g. using a fixed height or height of 0 breaks it again, changing the component too much breaks it again). No idea what's going on, anyone?

**Comment by popbee** [comment]
Can you make a very simple project that repro this?  Else I suspect you won't get any help.

**Comment by naqvitalha** [comment]
Please provide a repro and then reopen. I can't help without it.
