### ISSUE TITLE
i need wipe stacks when i change items on dataprovider

### ISSUE THREAD

**Issue by brasrox** [Flipkart/recyclerlistview#360]
i need wipe stacks of the list when i change items on dataprovider, because i cant access the .measure of an object when it was filtered on dataprovider

no success

 let dp = new DataProvider((r1, r2) => {
      return r1.processo !== r2.processo
    }).cloneWithRows(dados);

let rlv = this.refs['rlv'];
    // rlv.setState({ renderStack: {} });
    rlv._virtualRenderer._engagedIndexes = {};
    rlv._virtualRenderer._renderStack = {};
    rlv._virtualRenderer._stableIdToRenderKeyMap = {};
    rlv._virtualRenderer._recyclePool.clearAll();
    rlv._virtualRenderer._markDirty = true;
    rlv._virtualRenderer.refresh();
    rlv._virtualRenderer.handleDataSetChange(dp, true);

    dp._requiresDataChangeHandling = true;

    this.setState({
      isLoading: false, loaded: true, refreshing: false,
      filtered: dados.length
      , dataProvider: dp
    });

**Comment by naqvitalha** [comment]
Do you mean that you want list to start fresh? Can't understand the problem.

**Comment by brasrox** [comment]
> you mean that you want list to start fresh

yes, restart fresh and clean the stacks in pool if the list have less objects after the DataProvider was updated

**Comment by arunreddy-flipkart** [comment]
@brasrox You can remount the entire recyclerlistview component with the new Dataprovider if the idea is to start fresh again but it would have performance implications.
