### ISSUE TITLE
Ability to force row to re-render

### ISSUE THREAD

**Issue by sbearben** [Flipkart/recyclerlistview#361]
I have a component that uses RecyclerListView, and one of the component's props is called `selectedIndex`, which gives us the current selected index for rendering a highlighted border in the row that is currently selected.

However, when the prop is updated there is no row re-render, and thus the highlighted border does not move to the correct item. Prior to a prop update I'm also calling `scrollToIndex` on the recyclerListView in order to bring the selected row in view. Is there anyway to get a row to re-render either when the prop updates, or after a call to `scrollToIndex`?

I also do not want to hold a boolean on the data items that I'm passing into the DataProvider as that requires me mapping a whole bunch of objects to new items before feeding to the list.

**Comment by matanume** [comment]
@sbearben I'm on the same scenario. I want to remove highlight of previous selected row. I try extendedState but not working. How could I do it?

**Comment by noctivityinc** [comment]
@sbearben or @matanume either of your figure this out?
