### ISSUE TITLE
React Native 0.60 Deprecation Warning

### ISSUE THREAD

**Issue by ignitebhdeveloper** [Flipkart/recyclerlistview#370]
Kindly look into this.

```
W/ReactNativeJS: Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
    
    Please update the following components: RecyclerListView
    
    Learn more about this warning here:
    https://fb.me/react-async-component-lifecycle-hooks
2019-07-15 11:43:30.722 1119-1220/com.sts W/ReactNativeJS: Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.
    
    Please update the following components: RecyclerListView
    
    Learn more about this warning here:https://fb.me/react-async-component-lifecycle-hooks
```

React Native Version 0.60
Recyclerlistview Version 1.3.4/ Version 2.0.0-beta.3

**Comment by naqvitalha** [comment]
This will be fixed very soon. It's in progress.

**Comment by shanekoss** [comment]
> This will be fixed very soon. It's in progress.

Any updates on this?  Thanks!

**Comment by mayconmesquita** [comment]
Did you try the new v2.0.12?
https://github.com/Flipkart/recyclerlistview/releases/tag/2.0.12

**Comment by ignitebhdeveloper** [comment]
> Did you try the new v2.0.12?
> https://github.com/Flipkart/recyclerlistview/releases/tag/2.0.12

yes, the warning still persists.

**Comment by naqvitalha** [comment]
The change is merged to master. Have not published it yet. If you want to try you can build master directly.

**Comment by DaveLomber** [comment]
@naqvitalha are you going to get rid of 'componentWillReceiveProps' as well?

**Comment by naqvitalha** [comment]
@DaveLomber Yes, that has been removed as well. Try building from master.

**Comment by shanekoss** [comment]
> The change is merged to master. Have not published it yet. If you want to try you can build master directly.

Unfortunately this doesn't seem to fix the issue.

**Comment by naqvitalha** [comment]
I've published 2.0.13-alpha.1 from master. There are no warning in this one. Once this is release I'll close the issue.

**Comment by shanekoss** [comment]
> I've published 2.0.13-alpha.1 from master. There are no warning in this one. Once this is release I'll close the issue.

That works! Many thanks.

**Comment by manzoorwanijk** [comment]
@naqvitalha, still have warnings in `2.0.13-alpha.1`.

**Comment by gsunsnackv** [comment]
2.0.13-alpha.1 got rid of the warning for me. Hope it officially come out soon

**Comment by manzoorwanijk** [comment]
Never mind, had to clear the cache to make it work
`npm cache clean -f`

**Comment by mehmetbeyHZ** [comment]
Same issue! still have warnings in 2.0.13-alpha.1.

**Comment by gsunsnackv** [comment]
When will 2.0.13 come out?

**Comment by OrLevy23** [comment]
any updates on when a version will be released?

**Comment by MakhouT** [comment]
Is there an estimation when the next release will be out? Eagerly waiting for this.

**Comment by koenzi132** [comment]
@naqvitalha Hi there ! Do you have any plan to release new version which has no deprecation warning of RN 0.60? Not the alpha one! Btw, Happy new year :)

**Comment by naqvitalha** [comment]
We will be releasing this in the last week of Jan along with a bunch of other features :)

**Comment by OrLevy23** [comment]
any updates here? really looking forward not seeing this warning again

**Comment by naqvitalha** [comment]
Switch to v3.0. This is fixed.
