### ISSUE TITLE
rowRenderer not working

### ISSUE THREAD

**Issue by Crazypancakexd** [Flipkart/recyclerlistview#372]
I've debugged my app with RecyclerListView and nothing renders to the screen,
so I added a console.log to the rowRenderer function and I realized it's not calling the function.
I've tried things like removing my redux wrapper and my react-navigation wrapper,
or reinstalling the app and nothing works.
Here's my code:
`rowRenderer = (type, data) => {
               console.log('entered rowRenderer')
       return (
         <View style={{flex: 1, justifyContent: 
   'center'}}>
             <Text>This is a row :)</Text>
         </View>
       )
     }

  render() {
    return (
      <View style={styles.container}>
        <RecyclerListView
          style={{flex: 1}}
          rowRenderer={this.rowRenderer}
          dataProvider={this.state.list}
          layoutProvider={this.layoutProvider}
        />
      </View>
    );
  }
}`

**Comment by kaushal9678** [comment]
try to call **this.rowRenderer** in following two ways and 

> while using RecyclerListView you have to use DataProvider because it worked on the concept of ListView instead of FlatList

.

> **//Cell code**
```
rowRenderer=(index, item)=>{
    return(
        <View><Text>{item.title}</Text></View>
    )
}
```
 **RecyclerListView code**
```
   <RecyclerListView
      layoutProvider={this._layoutProvider}
        dataProvider={this.state.dataProvider}
        extendedState={this.state} //-> used to refresh list when state changes
        useWindowScroll
        forceNonDeterministicRendering
        keyExtractor={this._keyExtractorFeeds}//-> it is not required 
        rowRenderer={(type, data, index) => this._renderRow(index, data)} //-> type is for rendering specific cell type
        onEndReached={this.loadMoreData}
        onEndReachedThreshold={0.5}
        />
```

> **DataProvider in state definition**
```
dataProvider: new DataProvider((r1, r2) => {
        return r1 !== r2;
      }),

```


> **Setting DatProvide from API**
  ```
this.setState({
        dataProvider: this.state.dataProvider.cloneWithRows(yourData),
      });
```



> **Layout Provider Code**
  ```
this._layoutProvider = new LayoutProvider(
            index => {
                if (index % 4 === 0) {
                    return ViewTypes.FULL;
                } else if (index % 4 === 1) {
                    return ViewTypes.HALF_LEFT;
                } else {
                    return ViewTypes.HALF_RIGHT;
                }
            },
            (type, dim) => {
                switch (type) {
                    case ViewTypes.HALF_LEFT:
                        dim.width = width / 2;
                        dim.height = 160;
                        break;
                    case ViewTypes.HALF_RIGHT:
                        dim.width = width / 2;
                        dim.height = 160;
                        break;
                    case ViewTypes.FULL:
                        dim.width = width;
                        dim.height = 140;
                        break;
                    default:
                        dim.width = 0;
                        dim.height = 0;
                }
            }
        );
```

> **ViewTypes**
```
const ViewTypes = {
  FULL: 0,
  HALF_LEFT: 1,
  HALF_RIGHT: 2
};

```

Hope it works for you!

**Comment by Crazypancakexd** [comment]
Thanks for the response.
I realized where was my mistake.
Nothing was rendered to my screen because I defined
const { SCREEN_WIDTH, SCREEN_HEIGHT } = Dimensions.get("window");
While the correct form is:
const SCREEN_WIDTH = Dimensions.get("window").width;
const SCREEN_HEIGHT = Dimensions.get("window").height;
Thanks anyways :)
