### ISSUE TITLE
Can support for numColumns be added?

### ISSUE THREAD

**Issue by hannigand** [Flipkart/recyclerlistview#388]
I am using RecyclerListView as a direct replacement for FlatList.

However, I am trying to render a Grid. For the purpose of this issue, I am trying to render a 3x3 (non-scrollable) grid.

FlatList supports `numColumns` which provides assistance when rendering a Grid. After searching, I see that this library uses a ScrollView and `numColumns`, being a FlatList specific prop, does not work.

If supporting such prop is not feasible, is there a work around?

My thoughts were I could render 3 `RecyclerListView`s but this would be the worst case scenario.

**Comment by naqvitalha** [comment]
Checkout this plugin: https://github.com/muskeinsingh/recyclerlistview-gridlayoutprovider
