### ISSUE TITLE
Type with variable size

### ISSUE THREAD

**Issue by nastareater** [Flipkart/recyclerlistview#392]
RLV requires us to define type with fixed height and width while in my current case I only have 1 type but each row varies in length (depending on the content size), I cannot provide close estimate size since each item really varies in size. Do you know a good workarounds for this?

**Comment by Yarkhan** [comment]
Use the [prop `forceNonDeterministicRendering` ](https://github.com/Flipkart/recyclerlistview#why).

**Comment by nastareater** [comment]
totally aware of that prop, it's just using that alone will give constant row resizing and adjustment while also leave so noticeable blank area when scrolling

**Comment by Yarkhan** [comment]
Unfortunately, these type of lists (like a chat screen), are currently a big hassle on React Native, due bridge traffic. This is going to change very soon with the new architecture (Fabric, JSI and TurboModules).

The only option for this use case (besides flatlist) is going full native in the screens where performance is critical.

**Comment by arunreddy-flipkart** [comment]
@nastareater  The only way to render recyclerlistview when the layout size of each list item cannot be estimated accurately is to set the prop forceNonDeterministicRendering to true. We are aware of the resizing and adjustment issues and exploring solutions to try and fix this.
