### ISSUE TITLE
App gets slow in release mode.

### ISSUE THREAD

**Issue by appify-waheed** [Flipkart/recyclerlistview#394]
I was integrated the recyclerlistview in and it was woking fine on dev mode FPS of UI and JS were good and also memory consumption was reasonably good but when i runs that code in release mode on IOS (Not tested on android) list gets empty some times and also feeling slow rendering of items and even when press on some item it also takes more delay as compare to dev mode in dev its fast and working good but when i  runs into release it gets slow.

**Comment by naqvitalha** [comment]
Most likely this will have nothing to do with the list, in our tests it always becomes faster in release mode. Can some other configuration in your build cause this?

**Comment by appify-waheed** [comment]
@naqvitalha then how it is good is dev mode? i don't have any specific configurations for release or dev mode and i also seen on android slow rendering even in dev mode it renders first 3 to 4 items after a delay and then again takes 4, to 4 seconds to load others.

**Comment by naqvitalha** [comment]
Same as #396
