### ISSUE TITLE
how to use this library?

### ISSUE THREAD

**Issue by anuragversatile** [Flipkart/recyclerlistview#395]
can somebody guide me as to how to use this library if building netflix like app which is fetching data from various apis and has both vertical and horizontal scrolling ?
<img width="415" alt="netflix_like_view" src="https://user-images.githubusercontent.com/22766641/62836410-0d827500-bc80-11e9-9b87-c2e12dfc2adb.png">

**Comment by naqvitalha** [comment]
Please create multiple horizontal ones inside a vertical one.
