### ISSUE TITLE
ItemSeparatorComponent props

### ISSUE THREAD

**Issue by anhtuank7c** [Flipkart/recyclerlistview#406]
Do we have `ItemSeparatorComponent` **props** to render separator component just like `FlatList`?

**Comment by arunreddy-flipkart** [comment]
No, It is not currently supported, but you can wrap you list item inside a view along with a separator as follows.

<img width="168" alt="Screenshot 2019-10-21 at 2 19 30 PM" src="https://user-images.githubusercontent.com/56394019/67190609-de217e80-f40d-11e9-8ad6-d9e8f99b04a0.png">
