### ISSUE TITLE
Can I use this cool library to make horizontal carousel list for my Large data set?

### ISSUE THREAD

**Issue by kirtishjain9** [Flipkart/recyclerlistview#408]
Hi,

Thanks a lot for a great library.

I'm wondering if I can use it to make a horizontal carousel with a large data set (say - 2000).
I want an item card for each of my carousel item which spreads over almost entire screen space with some horizontal and vertical padding and then each time user scrolls item in either direction single item should be scrolled.

For example: 

![Simulator Screen Shot - iPhone Xʀ - 2019-09-06 at 20 41 11](https://user-images.githubusercontent.com/1879928/64439626-049e8b00-d0e8-11e9-8cd8-a490d77c12f7.jpg)

In attached screen shot, 'Overview, Marketing, Medias' are 3 buttons and when I click on any button then corresponding details should be visible in below area which is scroll-able in vertical direction if content is large and when content is scrolled vertical then the header view should be animated like below screen shot:

![Simulator Screen Shot - iPhone Xʀ - 2019-09-06 at 20 56 18](https://user-images.githubusercontent.com/1879928/64610427-d6bd8d00-d3ec-11e9-9548-0db8ceeb7ac4.jpg)

Please help me to get his with this library. Its quite urgent.

Please let me know if you need any more details?

Thanks in advance.

**Comment by naqvitalha** [comment]
I don't see a reason why you can't.

**Comment by thekevinbrown** [comment]
I just did this and so far it's working great.

**Comment by maxakak1998** [comment]
https://github.com/Flipkart/recyclerlistview/issues/421

Please look at my prolem. I need help !

**Comment by arunreddy-flipkart** [comment]
Assuming to be resolved. Closing
