### ISSUE TITLE
Optimize 'componentWillReceiveProps'

### ISSUE THREAD

**Issue by DaveLomber** [Flipkart/recyclerlistview#410]
Hi there,

I had time analyzing the src code of RecyclerListView.tsx
and found the implementation of 'componentWillReceiveProps'
https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L170 

According to React docs, sometimes a 'componentWillReceiveProps' can be called, but props are not changed 
https://reactjs.org/blog/2016/01/08/A-implies-B-does-not-imply-B-implies-A.html

and I debugged the src code and it's true - sometimes a 'componentWillReceiveProps' is called, but all props are the same ('===')

```
          let thisProps = this.props
          for(var key in nextProps) {
            if (nextProps[key] !== thisProps[key]) {
              console.log(`[RecyclerListView][componentWillReceiveProps]'${key}' prop changed`, thisProps[key], '~>', nextProps[key])
            }
          }
```

so nothing printed here 

I have a proposal to optimize the implementation of 'componentWillReceiveProps' and ignore its logic if props are no changed 

Please provide your feedback 
or maybe there is a case do keep it as is

**Comment by arunreddy-flipkart** [comment]
Hi,

The major logic in the componentWillReceiveProps comes from checkAndChangeLayouts method - https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L376. The checkAndChangeLayouts method is use the update the layout manager and its logic is only triggered when the props have changed.
