### ISSUE TITLE
adding numColumn 

### ISSUE THREAD

**Issue by Navidhp** [Flipkart/recyclerlistview#412]
hi , this feature very useful for multi column , you are say use recyclerlistviewGrid but not professional use 2 libery for list please add this feature thank you

**Comment by naqvitalha** [comment]
We've consciously kept RLV modular such that different kind of layoutproviders can be developed and plugged in. Having everything internally will bloat it up. Using gridlayoutprovider gives you what you need only when YOU need it: https://github.com/muskeinsingh/recyclerlistview-gridlayoutprovider
