### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView in recyclerlistview?

### ISSUE THREAD

**Issue by esdotzed** [Flipkart/recyclerlistview#414]
Dear Developer,

We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

grep -r UIWebView node_modules/*

node_modules/recyclerlistview/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/recyclerlistview/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView

**Comment by naqvitalha** [comment]
We don't have a dependency on UIWebView. Did anyone else get this warning?

**Comment by arunreddy-flipkart** [comment]
The warning may have occurred because the term UIWebView is present as a comment in the above files in the node module fbjs. There is no dependency on UIWebView.
