### ISSUE TITLE
Optimal way to update a row in list having 10k records

### ISSUE THREAD

**Issue by saggiyogesh** [Flipkart/recyclerlistview#418]
Hi,
What's the best way to update a row in recyclerlistview. 
My data in a row keeps changing in realtime. 

Dataprovider looks like 
```
dataProvider: new DataProvider((r1, r2) => {
    return r1 !== r2;
  })
```

Whenever any change is there, perform these steps
- search for that row in data array stored in the state
- deep clone the data
- update the cloned data
- push in the same index in the data array 
- finally, update the data provider

```
setDataProvider(dataProvider.cloneWithRows(data));
```
Is this the optimal way ?

**Comment by fariya12** [comment]
having the same issue any solution found ???

**Comment by saggiyogesh** [comment]
@fariya12 
Yes created a small component over `recyclerlistview` to support update & insert new record.

You can check https://github.com/saggiyogesh/rlv
Demo Snack: https://snack.expo.io/@saggiyogesh/rlv-test

**Comment by arunreddy-flipkart** [comment]
@saggiyogesh Yes, That is one way to update a row. The way to do it without deep cloning would be to modify the rowHasChanged parameter being passed to the dataProvider so that RLV can know correctly if the data has changed.
