### ISSUE TITLE
Rendering issue on clickable items on a list

### ISSUE THREAD

**Issue by drinikol** [Flipkart/recyclerlistview#419]
I am trying to practice to use Recyclerlist view an app similar to instagram, where in there is a Like button, the problem is when you toggle the Button, the image for Like changes, but some of the data in the list renders is affected as well. It is like every after two Data in the List the Like would be rendered.

**Comment by arunreddy-flipkart** [comment]
Hi,

It appears you may be storing the like status of the list item (liked or not liked) at the component's local state level which is not advisable in recyclerlistview as it recycles the items. You could store such data at a data store level or use the extendedState prop. Please refer to the following expo for an extendedState prop example - https://snack.expo.io/@arunreddy10/rlv-extendedstate-demo. Be careful not to change extendedState too frequently to avoid performance issues.
