### ISSUE TITLE
Change color the specific cell in layout

### ISSUE THREAD

**Issue by maxakak1998** [Flipkart/recyclerlistview#421]
I am creating my top bar like the horizontal list, when user clicks on the cell, they will change cell's background. I have run into trouble with rowRenderer not re-renders, so the props cant not be delivered to my component.

This is my RCLV:
![image](https://user-images.githubusercontent.com/50696626/66197626-fa5eb500-e6c4-11e9-943c-98f08d9a8cc5.png)

This is my rowRenderer
![image](https://user-images.githubusercontent.com/50696626/66197713-3265f800-e6c5-11e9-8a0e-47ebdeece3e9.png)

So as you can see, i want to send some props to my components when user clicks so i can change my component background. But it seems this reRenderer just runs one time.

Here is my app:
![image](https://user-images.githubusercontent.com/50696626/66197938-8ffa4480-e6c5-11e9-982c-3e41fd14a73e.png)

Please help me ! Thanks

**Comment by arunreddy-flipkart** [comment]
Hii, Could you provide a demo to reproduce this issue?

**Comment by maxakak1998** [comment]
I did it. Please close my topic, thanks
