### ISSUE TITLE
Confused with LayoutProvider

### ISSUE THREAD

**Issue by Kris-Lee-SH** [Flipkart/recyclerlistview#426]
After reading the document and demos, I'm quite confused with the `LayoutProvider`.

According to the doc, `LayoutProvider` is a **Constructor function that defines the layout (height / width) of each element**. It only receives index of each row and generate a layout with it. If we have a complex data that the layout size of some rows must be determined with data in it, what should we do? Accessing data in state with index?

Here is the situation: A page with 3 sections like a category entrance with several box items (1 or 2 rows with 5 columns which depends on the category data), a price filter and sorter row, and a list of goods.
In this situation, we have to put goods in `RecycleListView` but not all of them.

It seems like our `RecycleListView` is a good solution for some simple lists like flight list mentioned in the doc. But when the list, especially when it comes with the cell or row 's layout depends on its data, the data flow or the provider will be un-pure and that might cause some issue.

**Comment by naqvitalha** [comment]
You can always access your data inside layout provider. We do it all the time. The contract is such that you can cache this info independent of data, if required. Extend and pass data to it as well.
