### ISSUE TITLE
context provider in the web

### ISSUE THREAD

**Issue by hazzems123** [Flipkart/recyclerlistview#428]
Hello ,

i am trying to create a context provider for the web version , is it applicable , the steps i followed ;

1- imported context provider from receyclerlistview 
2- create a class component extending the imported module. {constructing a unique value , container object and methods which is get , save and delete }.

3- create a new instance for the class component .inside a variable .
4- add contextProvider prop in the Receyclerlistview component and assigned it the  variable which contain the instance of the context provider.

**Comment by naqvitalha** [comment]
Yes, it works on web. Can you share sample code to look into? Most likely your saved instance is getting lost because of your implementation.

**Comment by hazzems123** [comment]
https://codesandbox.io/s/hazofasho-6c3vm    FRONTTIMELINE FOLDER the BELOW TIMELINE

**Comment by hazzems123** [comment]
i am sorry if i provided the whole code here is the sample code for the program below :-


import { ContextProvider } from "recyclerlistview";

export default class ContextHelper extends ContextProvider {
  constructor(uniqueKey) {
    super();
    this._contextStore = {};
    this._uniqueKey = uniqueKey;
  }

  getUniqueKey() {
    return this._uniqueKey;
  }

  save(key, value) {
    this._contextStore[key] = value;
  }

  get(key) {
    return this._contextStore[key];
  }

  remove(key) {
    delete this._contextStore[key];
  }
}



export default class App extends Component {
  

  constructor(props) {
  
    super(props);
    this.state = {
      dataProvider: new DataProvider((r1, r2) => {
        return r1 !== r2;
      }),
      layoutProvider: LayoutUtil.getLayoutProvider(1),
      images: [],
      count: 0,
      viewType: 1
    };

    this.inProgressNetworkReq = false;
    this.ContextProvider = new ContextHelper("PARENT");
  }
  componentWillMount() {
    this.fetchMoreData();
  }

  componentDidMount() {
    const width = window.innerWidth;
    if (width < 800 && width > 700) {
      this.viewChangeHandler(2);
    } else if (width < 550) {
      this.viewChangeHandler(3);
    }
  }

  async fetchMoreData() {
    
    if (!this.inProgressNetworkReq) {
      //To prevent redundant fetch requests. Needed because cases of quick up/down scroll can trigger onEndReached
      //more than once
      this.inProgressNetworkReq = true;
      const images = await DataCall.get(this.state.count, 20);
      this.inProgressNetworkReq = false;
      this.setState({
        dataProvider: this.state.dataProvider.cloneWithRows(
          this.state.images.concat(images)
        ),
        images: this.state.images.concat(images),
        count: this.state.count + 20
      });
    }
  }
  rowRenderer = (type, data) => {
    //We have only one view type so not checks are needed here
    return <ImageRenderer imageUrl={data} />;
  };
  viewChangeHandler = viewType => {
    //We will create a new layout provider which will trigger context preservation maintaining the first visible index
    this.setState({
      layoutProvider: LayoutUtil.getLayoutProvider(viewType),
      viewType: viewType
    });
  };
  handleListEnd = () => {
    this.fetchMoreData();

    //This is necessary to ensure that activity indicator inside footer gets rendered. This is required given the implementation I have done in this sample
    this.setState({});
  };
  renderFooter = () => {
    //Second view makes sure we don't unnecessarily change height of the list on this event. That might cause indicator to remain invisible
    //The empty view can be removed once you've fetched all the data
    return this.inProgressNetworkReq ? (
      <ActivityIndicator style={{ margin: 10 }} size="large" color={"black"} />
    ) : (
      <View style={{ height: 60 }} />
    );
  };

  onResize = () => {
    const width = window.innerWidth;

    if (width < 1000 && width > 650) {
      this.viewChangeHandler(2);
    } else if (width < 650) {
      this.viewChangeHandler(3);
    } else {
      this.viewChangeHandler(1);
    }
  };

  render() {
    //Only render RLV once you have the data
    return (
      <div>
        <View style={styles.container}>
          <ReactResizeDetector
            handleWidth
            handleHeight
            onResize={this.onResize}
          />

          {this.state.count > 0 ? (
            <RecyclerListView
              style={{ flex: 1 }}
              contentContainerStyle={{ margin: 3 }}
              onEndReached={this.handleListEnd}
              dataProvider={this.state.dataProvider}
              layoutProvider={this.state.layoutProvider}
              rowRenderer={this.rowRenderer}
              renderFooter={this.renderFooter}
              canChangeSize={true}
              useWindowScroll={true}
              contextProvider={this.ContextProvider}
            />
          ) : null}
        </View>
      </div>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "space-between"
  }
});

**Comment by hazzems123** [comment]
sorry i fixed it like u said  saved instance is getting lost because of your implementation.
