### ISSUE TITLE
An internal state persists within the list items that are similar or can be recycled. 

### ISSUE THREAD

**Issue by Wraith722** [Flipkart/recyclerlistview#437]
I have a list RLV of cards, so I have a post card that you can like and comment on, but if there is something on index 1 and something on index 4 and they both are recycled cards, then on liking index 1 card, the index 4 card automatically gets liked just because it was reused and the state persisted from the index 1 card. 

So to tackle that I went around the issues list and found a closed issue that almost worked for me, By changing the data of the data provider I am able to set the attribute of like on one card at the desired index but the problem I am facing is that, the change (**_the liked status of the card_**) is only reflected after the scroll up or down twice, just as much such that the card gets recycled, so me touching the button expecting the button to like the post doesn't like the post, it takes not time, but scrolls so that the change occurs in the rendering of the card.

My code is pasted right here: https://github.com/Flipkart/recyclerlistview/issues/432#issuecomment-564865896

Please look into this issue, and please advice/

**Comment by arunreddy-flipkart** [comment]
Please refer to #432 , the solution has been provided. This expo could help with your use case - https://snack.expo.io/@arunreddy10/36f8f1
