### ISSUE TITLE
Change values of layoutProvider at run time outside constructor.

### ISSUE THREAD

**Issue by cgt-training** [Flipkart/recyclerlistview#441]
According to the definition layoutProvider should be inside the constructor. But in my case i want to increase / decrease the height of a row on the onPressEvent inside the RecyclerView. So, How i can change the layoutProvider inside a TouchableOpacity click like in given code. Values are changing in layoutProvider but not reflecting on the list until a new row render which will come when i scroll down in the list. I want Collapse / expand functionality in the list so it should reflect imediately. 
 <TouchableOpacity style={{ backgroundColor: "#B82240" }} 
onPress={
            () => {
                if(collapseIndexes.includes(index)){
                    collapseIndexes.splice( collapseIndexes.indexOf(index), 1 );
                } else{
                    collapseIndexes.push(index);    
                }
                // ._lastLayoutManager
                console.log(_parentRLVLayoutProvider);
                _parentRLVLayoutProvider = new LayoutProvider(
                    index => {
                        // console.log(this.state.parentRLVDataProvider._data[index].title)
                        // console.log(this.state.parentRLVDataProvider._data[index].data.length)
                        if(collapseIndexes.includes(index)){
                            console.log("parentRLVDataProvider._data[index].data.length");
                            return 0; 
                        }
                        return 0; 
                        // return parentRLVDataProvider._data[index].data.length;
                    },
                    (length, dim) => {
                        dim.height = length * 100 + 30;
                        dim.width = width;
                });
                console.log(_parentRLVLayoutProvider);
            }}>
            <Text style = {{fontFamily: "HelveticaNeue-Bold", fontSize: size(18), paddingHorizontal: size(17.5), color: "white", paddingVertical: size(5)}}>
                {(titleTrim == null || titleTrim == undefined || titleTrim == "null" || titleTrim == "") ? "N/A" : title}
            </Text>
        </TouchableOpacity>

i already done the part in constructor. 

_parentRLVLayoutProvider = new LayoutProvider(
            index => {
                // console.log(this.state.parentRLVDataProvider._data[index].title)
                // console.log(this.state.parentRLVDataProvider._data[index].data.length)
                if(collapseIndexes.includes(index)){
                    return 0; 
                }
                return parentRLVDataProvider._data[index].data.length;
            },
            (length, dim) => {
                dim.height = length * 100 + 30;
                dim.width = width;
            });

**Comment by arunreddy-flipkart** [comment]
So, It appears you want to update the layout provider dynamically based on user activity. You can simply create a new layout provider with the new constraints and trigger a setState causing the recyclerlistview to render again with the new layout provider in the onPressEvent.

**Comment by cgt-training** [comment]
Yeah i did that using extended state.
Closing the issue now

**Comment by UsmanJ** [comment]
@cgt-training how did you get this working? I am trying to update my `layoutProvider` and then updating state to rerender but it doesn't seem to be working. I feel like I'm missing something but struggling to figure out what.
