### ISSUE TITLE
Crashes on android with a big list

### ISSUE THREAD

**Issue by popo63301** [Flipkart/recyclerlistview#444]
Hello !

I have a big list of items that I render using RecyclerListView (around 2000+ items). The thing is when I filter the data and I would get to 10 items, the app crashes on android and I have no idea why. On iOS, it works fine. On android emulator it works fine as well. 

The problem is when I create an unrelased APK and I test the app on real device, I don't see any error message so I have no idea how to fix this problem.

Any idea?

**Comment by arunreddy-flipkart** [comment]
Could you provide an expo to help us reproduce the issue?

**Comment by popo63301** [comment]
This is a client project so I can't share the code unfortunately ...

**Comment by thinklinux** [comment]
@popo63301 have you fixed you issue?

**Comment by popo63301** [comment]
@thinklinux  Yes I solved it ! Thanks to ask. 

It wasn't an issue with the original FlatList component. It was a problem with the Array.filter function.

What I did is just move the work to the backend and make a request everytime I need to filter the list and put the new data to the list.

This workaround suits perfectly my situation.

**Comment by thinklinux** [comment]
Thanks for pointing this out :) So this issue should be closed then :)

**Comment by popo63301** [comment]
Sure
