### ISSUE TITLE
No layout available for index: 233

### ISSUE THREAD

**Issue by jekcom** [Flipkart/recyclerlistview#446]
If you change the data it throws an exeption 
See in this snack https://snack.expo.io/SJY6NU00B
Instructions to reproduce:

1. Scroll to the bottom
2. Type letter 'A' in the TextInput

**Result** :

`No layout available for index: 233
LayoutUnavailableException: No layout available for index: 233
    at new e (module://recyclerlistview.js:3:1527)
    at e.getOffsetForIndex (module://recyclerlistview.js:3:5917)
    at t.refreshWithAnchor (module://recyclerlistview.js:3:26794)
    at e._checkAndChangeLayouts (module://recyclerlistview.js:3:16117)
    at e.componentWillReceiveProps (module://recyclerlistview.js:3:11983)
    at Hi ([snack internals]
    at ha ([snack internals]
    at Js ([snack internals]
    at js ([snack internals]
    at Ps (https://s3.us-west-1.amazonaws.com/snack-web-player/36/static/js/2.d51b9d02.chunk.js:1:1086639)`

**Comment by Jalson1982** [comment]
Same issue :(. If use search it breaks.

**Comment by jekcom** [comment]
@aarshaw I've commented out the lines where it throws exception and it works flawlessly now
in LayoutManager.js

`WrapGridLayoutManager.prototype.getOffsetForIndex = function (index) {
        if (this._layouts.length > index) {
            return { x: this._layouts[index].x, y: this._layouts[index].y };
        }
        else {
            return { x: 0, y: 0};
            // throw new CustomError_1.default({
            //     message: "No layout available for index: " + index,
            //     type: "LayoutUnavailableException",
            // });
        }
    };`

**Comment by eae-christian** [comment]
> @aarshaw I've commented out the lines where it throws exception and it works flawlessly now
> in LayoutManager.js lines: 64-67
> and instead return return { x: 0, y: 0};
> 
> ```js
> WrapGridLayoutManager.prototype.getOffsetForIndex = function (index) {
>         if (this._layouts.length > index) {
>             return { x: this._layouts[index].x, y: this._layouts[index].y };
>         }
>         else {
>             return { x: 0, y: 0};
>             // throw new CustomError_1.default({
>             //     message: "No layout available for index: " + index,
>             //     type: "LayoutUnavailableException",
>             // });
>         }
>     };`
> ```

this solution doesn't work for me

@naqvitalha can you help? any idea about that?
thanks

**Comment by jekcom** [comment]
Looks like it has been fixed in version 3.0.0

**Comment by KrisLau** [comment]
Still having this issue in v4.2.1
