### ISSUE TITLE
Scrolls to top onEndReached with functional component

### ISSUE THREAD

**Issue by oste** [Flipkart/recyclerlistview#449]
I am hopeful that this is not a bug but wanted to cross-post here just in case. Please see SO below.

https://stackoverflow.com/questions/59573435/recyclerlistview-scrolls-to-top-onendreached-with-functional-component

**Comment by oste** [comment]
UPDATE: I can confirm that the class-based version works with no issues using redux connect. Leaning towards this being some kind of incompatibility with the library. Interesting nonetheless.


    class App extends React.Component {
      constructor(props) {
        let { width } = Dimensions.get('window');
    
        super(props);
        this.state = {
          dataProvider: new DataProvider((r1, r2) => {
            return r1 !== r2;
          }),
          layoutProvider: new LayoutProvider(
            index => 0,
            (type, dim) => {
              dim.width = width;
              dim.height = 240;
            },
          ),
          count: 0,
        };
      }
    
      componentDidUpdate(prevProps) {
        if (this.props.data.length !== prevProps.data.length) {
          this.setState({
            dataProvider: this.state.dataProvider.cloneWithRows(this.props.data),
            count: this.props.data.length
          });
        }
      }
    
      componentWillMount() {
        this.props.loadData();
      }
    
      async fetchMoreData() {
        this.props.loadData();
      }
    
      rowRenderer = (type, data) => {
        //We have only one view type so not checks are needed here
        return <CellContainer />;
      };
      
      handleListEnd = () => {
        this.fetchMoreData();
        //This is necessary to ensure that activity indicator inside footer gets rendered. This is required given the implementation I have done in this sample
        this.setState({});
      };
    
      render() {
        //Only render RLV once you have the data
        return (
          <View style={styles.container}>
            {this.state.count > 0 ? (
            <RecyclerListView
              style={{ flex: 1 }}
              contentContainerStyle={{ margin: 3 }}
              onEndReached={this.handleListEnd}
              dataProvider={this.state.dataProvider}
              layoutProvider={this.state.layoutProvider}
              renderAheadOffset={0}
              rowRenderer={this.rowRenderer}
            />
            ) : null}
          </View>
        );
      }
    }
    
    export default connect(
      state => ({
        data: selectData(state),
      }),
      dispatch => bindActionCreators({ loadData }, dispatch),
    )(App);

And here is the functional version for reference
    import React, { useCallback } from 'react';
    import { View, Text, Dimensions } from 'react-native';
    import { useSelector, useDispatch } from 'react-redux';
    import { RecyclerListView, DataProvider, LayoutProvider } from 'recyclerlistview/web';
    import { createSelector } from 'reselect';
    
    import { loadData } from '../actions';
    
    const selectData = createSelector(
      state => state.data,
      data => Object.values(data),
    );
    
    let containerCount = 0;
    class CellContainer extends React.Component {
      constructor(args) {
        super(args);
        this._containerId = containerCount++;
      }
      render() {
        return (
          <View {...this.props}>
            {this.props.children}
            <Text>Cell Id: {this._containerId}</Text>
          </View>
        );
      }
    }
    
    const List = ({ isServer }) => {
      let { width } = Dimensions.get('window');
    
      const dispatch = useDispatch();
    
      const data = useSelector(selectData);
    
      const dataDataProvider = new DataProvider((r1, r2) => {
        return r1 !== r2;
      }).cloneWithRows(data);
    
      const onEndReached = useCallback(() => dispatch(loadData()), [dispatch]);
    
      const layoutProvider = new LayoutProvider(
        () => 0,
        (type, dim) => {
          dim.width = width;
          dim.height = 240;
        },
      );
    
      const rowRenderer = (type, data) => {
        return <CellContainer />;
      };
    
      return (
        <View
          style={{
            display: "flex",
            flex: 1,
            width: "100vw",
            height: "100vh"
          }}
        >
          <RecyclerListView
            layoutProvider={layoutProvider}
            dataProvider={dataDataProvider}
            onEndReached={onEndReached}
            rowRenderer={rowRenderer}
          />
        </View>
      );
    };
    
    export default List;

**Comment by TadsDad** [comment]
I also have this problem

**Comment by shuvamDunzo** [comment]
Any solution/updates to this problem?

**Comment by shuvam07** [comment]
Any solution/updates to this problem?

Ps: even in class component i am facing the same issue.

**Comment by afrinsulthana1** [comment]
Was anyone able to resolve this using a functional component?

**Comment by immortalx** [comment]
Also experiencing this issue with functional components.

**Comment by immortalx** [comment]
So i got it fixed, at least on my use case with apollo client. What was missing was setting layoutProvider as a state:
```javascript
  const [layoutProvider] = React.useState(
    new LayoutProvider(
      (index) => 1,
      (type, dim) => {
        dim.width = ITEM_HEIGHT
        dim.height = ITEM_HEIGHT
      }
    )
  )
```

This made the scroll to top when new data is fetched disappear.

Here's the full code:
```javascript

export const GridList: React.FC = ({
  data,
  onEndReached,
  refetch,
  networkStatus,
  loading
}) => {
  const { width } = Dimensions.get('window')
  const ITEM_HEIGHT = width / 3
  const [dataProvider, setDataProvider] = React.useState(
    new DataProvider((r1, r2) => {
      return r1 !== r2
    })
  )
  const [layoutProvider] = React.useState(
    new LayoutProvider(
      (index) => 1,
      (type, dim) => {
        dim.width = ITEM_HEIGHT
        dim.height = ITEM_HEIGHT
      }
    )
  )
  React.useEffect(() => {
    setDataProvider((prevState) => prevState.cloneWithRows(data))
  }, [data])

  const renderFooter = () => {
    return loading ? (
      <ActivityIndicator style={{ margin: 10 }} size="large" color={'black'} />
    ) : (
      <View style={{ height: 60 }} />
    )
  }

  const rowRenderer = (type, { node }, index) => {
    return (
      <PhotoItem
        id={node.id}
        mediaThumbUrl={node.mediaThumbUrl}
        size={ITEM_HEIGHT}
        index={index}
      />
    )
  }

  return (
    <RecyclerListView
      style={{ flex: 1 }}
      layoutProvider={layoutProvider}
      dataProvider={dataProvider}
      rowRenderer={rowRenderer}
      onEndReached={onEndReached}
      onEndReachedThreshold={25}
      renderFooter={renderFooter}
      renderAheadOffset={0}
      scrollViewProps={{
        refreshControl: (
          <RefreshControl
            refreshing={networkStatus === 4}
            onRefresh={() => refetch()}
          />
        )
      }}
    />
  )
}
```

**Comment by mayconmesquita** [comment]
@immortalx Thanks for the example! It works good!

**Comment by oste** [comment]
I can also confirm that functional components seem to be working solid with hooks. Thanks!

**Comment by oste** [comment]
I take it back, for me, it is not recycling items. It calculates the height and renders the first items but doesn't do anything more on scroll 🤔

**Comment by Elabar** [comment]
I follow @immortalx example, it works fine as long as the layoutProvider do not depends on the data's type.
If the layoutProvider does depend on the data's type, you can still update the list, but the 'forceNonDeterministicRendering' is not working as expected.

I try to write the exact same thing in class component style, it works just fine.
Here's the snack I created, you can comment or uncomment these component in App.js to see what's wrong
```
 <ListWrapper /> (written in class component style) 
 <FullFunctional /> (written in functional component style)
```
https://snack.expo.io/@elabar/recyclerlistview-sample

Am I doing anything wrong here?

**Comment by dzpt** [comment]
@immortalx inside the LayoutProvider, i can't use `dataProvider.getDataForIndex(index)` to access to item data to set layout

**Comment by c-info** [comment]
How can i use dataProvider.getDataForIndex(index) with use state in layoutProvider ?

**Comment by GiordanoMenezes** [comment]
> Was anyone able to resolve this using a functional component?

https://github.com/GiordanoMenezes/Functional-RecyclerListView

**Comment by MohannadBakkar** [comment]
> > Was anyone able to resolve this using a functional component?
> 
> https://github.com/GiordanoMenezes/Functional-RecyclerListView

Are there any documents on how to use it?
