### ISSUE TITLE
"type" in layoutProvider URGENT!

### ISSUE THREAD

**Issue by aceallen17** [Flipkart/recyclerlistview#454]
Hi, I followed this tutorial to implement infinite scrolling using paging.
https://www.youtube.com/watch?v=32ZM72CKtTE

I can't use "type" in layoutProvider, as the Data is fetched from web service and Data(fetched) doesn't have a "type" key nor can't add it right now.  how can I integrate it?!

**Comment by arunreddy-flipkart** [comment]
Hi, You need all the list items to have a layout type to enable recycling on basis of the type of the item. If all the items have the same layout then a single default layout type would be enough.

**Comment by aceallen17** [comment]
I can't use "type" in layoutProvider, as the Data is fetched from web service and Data(fetched) doesn't have a "type" key nor can't add it right now. Is it possible to integrate it with "type"  in layoutProvider?!

**Comment by thinklinux** [comment]
@aceallen17 `type` does not have to come with your data. Is a layout type to you can set. For example if you know that you have 3 types of sizes you should give them to the view so it would know how to recycle them. If you have only one type just return `0` for the index, set width and height and you are ready to go. Keep in mind that the list does not support dynamic layouts. Hope this helps.

**Comment by naqvitalha** [comment]
Closing this.
