### ISSUE TITLE
setNativeProps is not working

### ISSUE THREAD

**Issue by cgt-training** [Flipkart/recyclerlistview#457]
Hello all,
I am facing a major issue.
<RecyclerListView
  		    style = {{ 
            flex: 1
          }}
          ref = { 
            (RecyclerListView) => this.childRLVRef = RecyclerListView
          }
          initialOffset = { 1 }
          // scrollEnabled = { this.state.enableScroll }
          scrollEnabled = { true }
          onScroll={ this.onScrollCallback }
          dataProvider = { this._childDataProvider }
          layoutProvider = { this._childRLVLayoutProvider }
          rowRenderer = { this._childRowRenderer }
          showsVerticalScrollIndicator={ true }
/>

i want to change scrollEnable to false and i am using this.childRLVRef.setNativeProps({ scrollEnabled: false }); for this purpose but i am getting error.

this.childRLVRef.setNativeProps is not a function.

**Comment by naqvitalha** [comment]
You can pass it as scrollViewProps={{scrollEnabled: true}}
