### ISSUE TITLE
Mixed ViewTypes doesn't work on OnePlus devices

### ISSUE THREAD

**Issue by rohitkum28** [Flipkart/recyclerlistview#461]
I am trying the Mixed ViewTypes example shared in the [demo](https://github.com/Flipkart/recyclerlistview#demo) section. It works on most of the devices I tried on, but the view doesn't load properly on OnePlus devices. I have tried it on OnePlus 6T and 5T. Here is the difference between Expected and Actual.

**Expected:**

<img width="252" alt="flipkart" src="https://user-images.githubusercontent.com/11205673/73815643-97189700-480c-11ea-9dd3-dbb5927f49bc.png">

**Actual:**

![Screenshot_20200205-112708](https://user-images.githubusercontent.com/11205673/73815667-a861a380-480c-11ea-801b-77ca7cac0694.jpg)

**Reproducible Demo:**

https://snack.expo.io/H1KBG4WM8

**Environment:**
React: 16.9.0
React native: 0.61.2
recyclerlistview: ^2.0.12

**Device Details:**
Name: OnePlus 6T
Android Version: 9
Model: ONEPLUS A6010

**Comment by naqvitalha** [comment]
This is a precision issue. Please use: https://github.com/muskeinsingh/recyclerlistview-gridlayoutprovider Soon it'll be default in RLV.
Alternatively, you can decrease the given width by 1px and it'll fit. But given it's not clean I'll suggest gridlayoutprovider.
