### ISSUE TITLE
First item of list cut

### ISSUE THREAD

**Issue by AlexandreMaistret** [Flipkart/recyclerlistview#463]
Hi !

I have switch to this library because of react-native's Flatlist bad performance, so I am trying first with a really easy list, but the first item of the list is always cut and I don't understand why. At the end of the list, there is also a small white space. It seems all my list is a little bit shift.

However, all the items after the first item are correctly sized without any problem and they are all the same size.

On the picture below, I am at the very top of my list and as you can see the first item is cut. 
![image](https://user-images.githubusercontent.com/14938428/73895971-ad146f00-4881-11ea-83b3-3044500fadc0.png)

The item's height is the same as the one passed in the LayoutProvider, so I don't have any clue on how to solve this problem. If someone has a solution... 

Here is my code below:

    constructor(props) {
      super(props);
      this.layoutProvider = new LayoutProvider(
        index => {
          return index;
        }, (type, dim) => {
          dim.height = ListItemHeight;
          dim.width = SCREEN_WIDTH;
        }
      );
    }

    state = {
      dataProvider: new DataProvider((r1, r2) => {
        return r1 !== r2;
      }),
    };

    componentDidMount() {
      const dataProvider = this.state.dataProvider.cloneWithRows(phone_number_prefixes_alphabetic);
      this.setState({
        dataProvider: dataProvider,
      });
    }

    renderItem = (type, item) => {
      return (
        <CountryPrefixeItem
          country_prefixe={item}
          onPress={this.onPressCountryPrefixeSelected}
        />
      );
    }

    render() {
        return (
          <RecyclerListView
            style={{ flex: 1 }}
            dataProvider={this.state.dataProvider}
            layoutProvider={this.layoutProvider}
            rowRenderer={this.renderItem}
          />
        )
    }

**Comment by AlexandreMaistret** [comment]
Problem solved.

The recycle list didn't like a flex: 1 in the item's render whereas for Falitlist it wasn't a problem.

**Comment by geroale** [comment]
I am having the same issue but without using flex in the rows
