### ISSUE TITLE
Why key is undefined or "0_rlv_c"all the time!? 

### ISSUE THREAD

**Issue by pavanMude** [Flipkart/recyclerlistview#468]
Why key is 0 all the time! I have around 12 indexes, on every index it should generate a key, but in the beta version it is giving "#0_rlv_c" as result and making key as undefined! Can somebody help me with this issue!

**Comment by naqvitalha** [comment]
Are you using stableIds? You might have returned duplicated id somewhere. Share a repro for me to check.
