### ISSUE TITLE
did not support SectionList?

### ISSUE THREAD

**Issue by weinixuehao** [Flipkart/recyclerlistview#472]
did not support SectionList?

**Comment by arunreddy-flipkart** [comment]
A wrapper for section list can easily be written on top of recyclerlistview by adding the list headers as part of the list and specifying their layout sizes in the layout provider

**Comment by germanp173** [comment]
@weinixuehao check out this helpful [example](https://github.com/Insomaniacgamer/React-Native-recyclerlistview-demo) for how to build sections using `RecycleListView`
