### ISSUE TITLE
Possible to use RecycleListView as SectionList?

### ISSUE THREAD

**Issue by kulpubekov** [Flipkart/recyclerlistview#473]
Hi, i want to use RecycleListView as SectionList, i have big json data, where the scructure is like SectionList) When i use SectionList i have problems with performance. Can you give me advice? Thank you

**Comment by arunreddy-flipkart** [comment]
Yes it should be possible to do that. A wrapper for section list can easily be written on top of recyclerlistview by adding the list headers as part of the list and specifying their layout sizes in the layout provider.

**Comment by kulpubekov** [comment]
@arunreddy-flipkart, can you give little example ?

**Comment by arunreddy10** [comment]
Hi,

You can create a LayoutProvider with two types - one header type and one data type views. The data array can be processed into a single array consisting of items each with their type and corresponding data. This data can be passed to the DataProvider. so the date array would look something like.

const data = [
{
type: 'Header',
data: 'Main dishes'
},
{
type: 'Data',
data: 'Pizza'
},
{
type: 'Data',
data: 'Burger'
}
]

You can refer to this sample for project for more details regarding dataProvider and layoutProvider - https://github.com/naqvitalha/travelMate

**Comment by KingAmo** [comment]
i think it is a common case to mock a  `SectionList `  use `RecycleListView`,  could you guys share more detail on this use case ?

**Comment by germanp173** [comment]
@KingAmo check out this helpful [example](https://github.com/Insomaniacgamer/React-Native-recyclerlistview-demo) for how to build sections using `RecycleListView`
