### ISSUE TITLE
How to scroll to the top of RecyclerListView

### ISSUE THREAD

**Issue by sillybilly12** [Flipkart/recyclerlistview#475]
Hi, Im using recyclerlistview for rendering our collection list. Now I have a toggle button which fetches different set of data than the existing one, but the scroll position doesn't change when I toggle. I want the RecyclerList to scroll to the top whenever the data changes. How do I achieve this?

Im using a function component and whenever I add a ref, Im getting the following error. 

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by arunreddy10** [comment]
Hi, You can set the initialOffset prop to zero when the data has changed, so that the list renders from the top
