### ISSUE TITLE
How can i use RLV with react-native-reanimated?

### ISSUE THREAD

**Issue by SunskyXH** [Flipkart/recyclerlistview#482]
Hi, I've using RLV for a while, and it is incredible! But recently, I'm blocked on combining RLV and `react-native-reanimated` while trying to handle scroll events with reanimated's API.
The reanimated offers its own `Animated.ScrollView` and provides a different `onScroll` event with react-native's `Animated.ScrollView`.
I tried the `externalScrollView` props but didn't make it. Is this any other way to combine RLV with `react-native-reanimated` ?

**Comment by SunskyXH** [comment]
Updates:
I tried `createdAnimatedComponent` method from `react-native-reanimated`, and it seems to work as for now. See [source code of createdAnimatedComponent](https://github.com/software-mansion/react-native-reanimated/blob/master/src/createAnimatedComponent.js)

**Comment by Terfender** [comment]
@SunskyXH  can you please share the skeleton of your approach? I am trying to use RLV and reanimated.

**Comment by mrousavy** [comment]
Are the `onScroll` events actually dispatched on the UI thread using your approach @SunskyXH ?

**Comment by likern** [comment]
> Are the `onScroll` events actually dispatched on the UI thread using your approach @SunskyXH ?

Have you figured that out?
