### ISSUE TITLE
Not support like FlatList'ListEmptyComponent,ListHeaderComponent

### ISSUE THREAD

**Issue by yibingxiong** [Flipkart/recyclerlistview#491]
- I' want to ask if this component support like FlatList'ListEmptyComponent and ListHeaderComponent or not? I can't find these futures in the docs.
- if not support, how should I realize  the ListHeaderComponent?

the reference link is  [https://react-native.org/doc/flatlist.html](https://react-native.org/doc/flatlist.html)

Thank you!

**Comment by yibingxiong** [comment]
I found the answer in another [issue](https://github.com/Flipkart/recyclerlistview/issues/458).
Thank you for develope such a good component.

**Comment by Sarvarr** [comment]
some issue, could you give an example @yibingxiong

**Comment by Satyajeetsinh-9** [comment]
@algokano what he is mentioning is Flatlist provides a method called ListEmptyComponent which handled empty component automatically when list gets's empty. We don;t need to manually put anycondition for rendering flatlist if list is empty.

I have same case as when I am searching through list if no search exists then the recycler displays blank white space where as flatlist using ListEmptyComponent displayed an empty render component...
