### ISSUE TITLE
How to implement horizontal scroll left from first index to last

### ISSUE THREAD

**Issue by nathanburgess** [Flipkart/recyclerlistview#492]
I have a hero rotator with 5 items that scrolls horizontally. I can scroll infinitely to the right (when reaching the end just wrap to the beginning) but I'm having trouble getting scrolling to the left to work. When the list is at the first index, scrolling left doesn't provide any kind of scroll event.

Has anyone been successful in implementing this?

**Comment by naqvitalha** [comment]
You can model your data like  `0 1 2 3 4 0 1 2 3 4 0`. Every time you reach 0 you reset to the middle. Could be one quick way to implement given RLV will take care of rendering them optimally.
