### ISSUE TITLE
Scroll to the top when list data changes.

### ISSUE THREAD

**Issue by black7375** [Flipkart/recyclerlistview#493]
I'm trying to make an example because this library is attractive.(performance is good :+1: )
But something unexpected happened.

Click **item8** to update the state.
![todo1](https://user-images.githubusercontent.com/25581533/80893961-4fe45a00-8cc6-11ea-8092-180b8056fcc7.png)

Scrolls up to the top.
![todo2](https://user-images.githubusercontent.com/25581533/80893965-51ae1d80-8cc6-11ea-8ed3-0b2685721798.png)

Is there a separate way to fix the scroll when updating the status?

This is my code(RecyclerListView/Web).
```tsx
const TodoList = ({ todos, onRemove, onToggle }: TodoListProps) => {
  const width = window.innerWidth;

  const renderData = new DataProvider((r1: TodoItemT, r2: TodoItemT) => {
    return r1 !== r2;
  }).cloneWithRows(todos);

  const [dataProvider, setDataProvider] = useState(renderData);
  useEffect(() => {
    setDataProvider((dataProvider) => dataProvider.cloneWithRows(todos));
  }, [todos]);

  const layoutProvider = new LayoutProvider(
    (index) => { return ListViewType.TODOLISTITEMS },
    (type, dim) => {
      switch(type) {
        case ListViewType.TODOLISTITEMS: {
          dim.width  = width; // 630.4 584
          dim.height = 55; // 55.2  54.4
          break;
        }
        default:
          dim.width  = 0;
          dim.height = 0;
      }
    }
  );

  const rowRenderer = (viewType: React.ReactText, todo: TodoItemT) => {
    switch (viewType) {
      case ListViewType.TODOLISTITEMS: {
        return (<TodoListItem todo={todo} key={todo.id}
                              onRemove={onRemove} onToggle={onToggle} />);
      }
      default:
        return null;
    }
  }

  return (
    <div className={cx('TodoList')}>
      <RecyclerListView dataProvider={dataProvider} layoutProvider={layoutProvider}
                        rowRenderer={rowRenderer} />
    </div>
  );
};
```

**Comment by sarunathan** [comment]
I had similar issues before.

Don't create dataProvider instance multiple times during re-rendering.
Also don't create LayoutProvider instance multiple times. 

Try doing " dataProvider = dataProvider.cloneWithRows(dataFromProp);" Only this in useEffect when ever the data changess you need to update.

Sample code

`let [dataProvider, setDataProvider] = useState(
        ()=> {
            let dp = new DataProvider((r1, r2) => r1.id !== r2.id);
            return dp.cloneWithRows(dataFromProp);
        }
    );

const [layoutProvider, setLayoutProvider] = useState(new LayoutProvider(
            i => get(dataProvider.getDataForIndex(i), 'widget.type', 'default'),
            (type, dim) => {
                dim.width = width || windowWidth;
                dim.height = widgetHeights[type] || DEFAULT_WIDGET_HEIGHT;
            },
        ));

useEffect(
        () => {
            dataProvider = dataProvider.cloneWithRows(dataFromProp);
            setDataProvider(dataProvider);
        },
        [dataFromProp.length],
    );

`

See if this helps.

**Comment by black7375** [comment]
@sarunathan Thank you!
I'll follow this example.

**Comment by black7375** [comment]
I've found out why this happened!!
I used the high order component to mark it as "loading.." during the initial data loading. 
When it updated the status, it seems that the rerendering occurred in the container.

+.
Thank you for your good advice. :smiley_cat:
