### ISSUE TITLE
How to implement layoutSize?

### ISSUE THREAD

**Issue by wmonecke** [Flipkart/recyclerlistview#494]
The first render of `RecyclerListView` is blank and takes a couple (but noticeable) milliseconds to render. How can I implement `layoutSize` to improve the first render? I can't find any kind of documentation or example.

Thank you very much!

**Comment by naqvitalha** [comment]
You can just pass a `Dimension` object. It is just an object with `height` and `width`. This is what RLV will assume its size to be. If you want it to be corrected once stuff if rendered set `canChangeSize` to true.
