### ISSUE TITLE
LayoutProvider given height & width, but items in ScrollView add extra spacing

### ISSUE THREAD

**Issue by peacechen** [Flipkart/recyclerlistview#497]
RecyclerListView is a great improvement over ScrollView and FlatList.  Thank you for creating such a great library.

I'm adding a scrollable feature to `react-native-calendar-strip` and this library looks like it's The One.  I have a question about the LayoutProvider behavior that I can't track down looking through the RecyclerListView source code.

The items in CalendarStrip are all exactly the same dimensions.  This is the LayoutProvider:
```
    this.layoutProvider = new LayoutProvider(
      index => 0, // ViewType.FULL
      (type, dim) => {
        dim.width = this.props.itemHeight;  // Square, so width = height
        dim.height = this.props.itemHeight;
      }
    );
```

The render function passed to `rowRenderer` creates an item of those exact dimensions.  I'm certain of that because when I pass those in to a RN ScrollView, the days are directly against each other with no spacing.  However RLV adds extra spacing between the items:
![image](https://user-images.githubusercontent.com/6295083/82235823-dae56700-98f8-11ea-8fcb-22ab4773d211.png)

If I set `forceNonDeterministicRendering`, the items have no spacing as they appear in a native ScrollView: 
![image](https://user-images.githubusercontent.com/6295083/82236110-429bb200-98f9-11ea-8784-14e143eabcfd.png)

You might be wondering why I want the items directly against each other.  Ultimately I will add a small margin between them, but the default behavior of RLV without `forceNonDeterministicRendering` adds too much space between.

Why does LayoutProvider introduce extra spacing when it's given the exact item dimensions?

**Comment by peacechen** [comment]
@naqvitalha 
Any tips on how to get LayoutProvider to use the exact dimensions provided?  `forceNonDeterministicRendering` causes undesirable jitter when scrolling through the list.

**Comment by batical** [comment]
how did you define the item component? did you set width and height ? Am new to recyclerView but fix lot of problems using inspector

**Comment by peacechen** [comment]
Thanks @batical .  I re-checked the rendered item and it's using the expected size, but the dimensions passed to LayoutProvider were wrong 🤦‍♂️
