### ISSUE TITLE
How to add color to scroll bar indicator ?

### ISSUE THREAD

**Issue by dkat15** [Flipkart/recyclerlistview#510]
I would like to know if we can provide our own color to the scroll indicator in the recycler list view?

I want to add my theme color to the scroll indicator.

**Comment by dkat15** [comment]
@naqvitalha, please help

**Comment by arunreddy10** [comment]
Hi,

The default react native scroll view accepts a `indicatorStyle` prop for indicator styling in iOS. To add your own custom styling, you can pass a custom external scroll view as a prop to be used inside recyclerlistview. Perhaps, this component may help in your use case - https://www.npmjs.com/package/react-native-scrollview-indicator
