### ISSUE TITLE
How to hide scroll bar of recylerlistview?

### ISSUE THREAD

**Issue by dkat15** [Flipkart/recyclerlistview#520]
Hello Team,

I want to hide the scroll bar of recyclerlistview. Can we achieve it? Is there any way to do it?

It is showing transparent on my android tv app. However, it clearly visible and white in my WebOS tv application.

Kindly help.

**Comment by paranoia5** [comment]
you can simply hide the scrollbar as follows:

```
<RecyclerListView 
      scrollViewProps={{
           ....
          showsVerticalScrollIndicator: false,
           ... 
        }}
/>
```
