### ISSUE TITLE
one blank frame when list initialize (mounting)

### ISSUE THREAD

**Issue by eyousefifar** [Flipkart/recyclerlistview#529]
Hi
On mounting point there's one blank frame, it's more obvious when there are other components on screen. Not a big problem but also not very satisfying
Is there a solution? Thanks

**Comment by Megha060199** [comment]
Any solution found? I'm facing the same issue

**Comment by cenaHara** [comment]
.

**Comment by eyousefifar** [comment]
@Megha060199 @cenaHara I used react dev tools on this, in the chart, creating an animated component took the most ( I think 4 ms ). I dove into code, it's so messy actually. but the algorithm is not that complicated, basically ( if I fully get it ) it translates created components into the correct position with new data. recycling components. I think a rewrite will solve this issue.
but expecting a rewrite is not a good expectation until someone (like myself) starts doing it.

**Comment by arunreddy10** [comment]
Hi,

The layoutSize prop can be used to specify an estimated size of RLV in order to remove the initial blank frame. RecyclerListView will use these dimensions to layout the child items upfront and not wait for the onLayout event to return the correct size of the view which causes the blank frame. Please refer to the readme for more details.

**Comment by eyousefifar** [comment]
@arunreddy10 I did test layoutSize prop with sample code, it has no effect 
do you have a working sample?

**Comment by eyousefifar** [comment]
I can confirm it's working now

**Comment by a845954** [comment]
Can we add a loader in place of blank screen before views are loaded?

**Comment by ed1son67** [comment]
> @arunreddy10 I did test layoutSize prop with sample code, it has no effect do you have a working sample?

Could you show me some code example?
