### ISSUE TITLE
[QUESTION] As of August 2020 (React-Native 0.63.2), is the RecyclerListView still faster than the default FlatList component?

### ISSUE THREAD

**Issue by mrousavy** [Flipkart/recyclerlistview#535]
As of August 2020 (React-Native version **0.63.2**), is the `<RecyclerListView>` still a better choice than the default `<FlatList>` component?

There has been a lot of development around the default react native FlatList component, especially performance wise, which left me thinking if I should swap out my FlatList component to use a RecyclerListView, or leave it as is. See: [Optimizing FlatList Configuration](https://reactnative.dev/docs/optimizing-flatlist-configuration)

For extra information: I'm not rendering thousands of items, I'm rendering relatively heavy items similar to Instagram's feed. See:

<div align="center">
<img src="https://user-images.githubusercontent.com/15199031/90135084-6b094000-dd72-11ea-95ac-e52511621b3f.png" width="40%">
</div>

**Comment by davx1992** [comment]
Hi, I think yes that still this package is better than Flat List, I have tried to switch to FlatList, unfortunately flat list is working much worse - consumes much more CPU and whole JS thread, when there is a big list.

**Comment by naqvitalha** [comment]
Unless `FlatList` changes their core idea it will remain slow. Also, RLV enables better layout managers like masonry so, depends on your usecas.
