### ISSUE TITLE
How to avoid delay while list's mounting

### ISSUE THREAD

**Issue by caiphaav** [Flipkart/recyclerlistview#539]
For the first time recyclerlistview loading with delay. Any suggestions how to avoid this delay? 
"react": "16.11.0",
"react-native": "0.62.2",
"recyclerlistview": "3.0.0",

![mounted](https://user-images.githubusercontent.com/53155258/91664485-3af2c880-eaf8-11ea-88b9-a4a2eb94828d.gif)

**Comment by adhip94** [comment]
@caiphaav Did you find a solution for this? Even I am facing this. Atleast is it possible to show a loading indicator while this is rendering?

**Comment by caiphaav** [comment]
> @caiphaav Did you find a solution for this? Even I am facing this. Atleast is it possible to show a loading indicator while this is rendering?

Hey, sorry for a long waiting

it seems that JS Thread dropped while the screen mount for the first time in react-navigation and block screen rendering. Therefore its more react-native architecture bridge issue. Try to use react-native-navigation from Wix instead - it can give you more native feelings and maybe can help you with this issue
