### ISSUE TITLE
Dynamic height for just some elements

### ISSUE THREAD

**Issue by natew** [Flipkart/recyclerlistview#553]
I know the height for all but the first two elements and the last element. But turning on `forceNonDeterministicRendering` causes everything to be pretty weird - things collapse down in width and I'm forced to hardcode widths everywhere, and performance is degraded.

It seems it would be better to have it set through LayoutProvider which could set `dim.height = 'auto'` for dynamic.

**Comment by natew** [comment]
Turns out I could use externalScrollView

**Comment by obiwankenoobi** [comment]
Can you please share the code you used? I have very similar issue and I can't find a solution, Thank you!
