### ISSUE TITLE
removeClippedSubviews={true} in scrollview - view not visible when changed tab

### ISSUE THREAD

**Issue by krunalbad** [Flipkart/recyclerlistview#578]
`removeClippedSubviews={true}` in scrollview - view not visible when changed tab

When launched an app for the first time the scroll view is visible
but when I change the tab i.e. perform any navigation the scroll view is not visible until it is scrolled

`removeClippedSubviews={true}` using this as `true` makes my scroll view perform faster the only issue is that the view gets hidden sometimes on the navigation

FYI: `removeClippedSubviews={false}` doesn't reproduce the hidden issue but degrades the performance

Any idea of how to fix the hidden issue while having `removeClippedSubviews={true}`?

![Screenshot 2021-01-02 at 12 46 32 PM](https://user-images.githubusercontent.com/45413622/103452773-e014ec00-4cf8-11eb-889d-7b6c47a46e9d.png)

**Comment by krunalbad** [comment]
This issue is something from the RN Scrollview. So if anyone has something to share then please do. Closing this for now!

**Comment by waheedakhtar694** [comment]
I added `removeClippedSubviews={false}` initially so it will not hide the records and as I have pagination implemented so I make that flag `true` once I am loading more records.
