### ISSUE TITLE
extended state depending on props

### ISSUE THREAD

**Issue by ingerable** [Flipkart/recyclerlistview#584]
How we are supposed to put props in extended state when we are not supposed to pass props directly in extended test ?
https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/performance#5-extendedstate-usage

Copying props into state is an anti pattern so what are we supposed to do if we want to refresh rows depending on props ?

**Comment by ardyfeb** [comment]
just pass the props directly to recycerlistview `extendedState={props.extended}`

**Comment by ingerable** [comment]
I did it, but as I said it's not recommended. I'm closing the issue since there is no answer
