### ISSUE TITLE
Is it possible to use local state in component

### ISSUE THREAD

**Issue by zoom2009** [Flipkart/recyclerlistview#592]
My problem is when state at ItemComponent change and then I scroll down, Some other ItemComponent in list has change too ```like={true}```.

```javascript
ItemComponent = () => {
    const [like, setLike] = useState(false)
    <Text onPress={() => setLike(!like)}> {like} </Text>
}
```

if not possible for some reason, do you have any solution for this. should I deep clone and reset value for ```dataProvider``` ?
thx

**Comment by zoom2009** [comment]
I got it! after try to learn from demo. Solution is using ```extendedState```

**xtendedState,stableIDs and ItemAnimator (Expo)**: https://snack.expo.io/@arunreddy10/19bb8e

**Comment by zyasir** [comment]
Thanks @zoom2009 for this topic. I don't understand why we can't use local state. Do you know why? I am having the same issue as you, selected issue. I store that state locally though, not at parent list level.
