### ISSUE TITLE
UseScrollToTop in react navigation v5

### ISSUE THREAD

**Issue by khunghang16** [Flipkart/recyclerlistview#612]
I use useScrollToTop in react navigation v5 with recyclerlistview, list scroll to top without animation. How I can scroll top with animation. 
I use packages:

- "react-native": "0.63.3"
- "recyclerlistview": "^3.0.5",

Tks!

**Comment by plus-** [comment]
I got it working like so:

```
useScrollToTop(
      React.useRef({
        scrollToTop: () => ref.current?.scrollToOffset(0, 0, true) // force animate to true
      })
    )

```

**Comment by khunghang16** [comment]
My problem is solved! Thanks

**Comment by siddharth-kt** [comment]
It did not worked for me (it scrolls to top without animation), any solution please ?
