### ISSUE TITLE
Cannot read property 'getLayoutDimension' of undefined

### ISSUE THREAD

**Issue by Fr1kki3** [Flipkart/recyclerlistview#62]
If I initially load a page before having data, returning an empty page(null/<Text>No Data</Text>) then fetch data from server after component mounted and set the data for data provider to my new data this error is produced at VirtualRenderer.getLayoutDimension. 

On IOS it imediatly displays the "'getLayoutDimension' of undefined" error while on android the red screen displays 'Node has not been attached to a view' and the getLayoutDimension goes as a warning in background and on Debug console.

Commenting out the onEndReached property makes the problem stop.

I have tried to reproduce the error on snack/expo, but it does not reproduce the same error. On snack/expo it sometimes just work and other times expo just crashes.

Link to example:  https://snack.expo.io/ryy4QxFRZ

**Comment by Fr1kki3** [comment]
after moving all the components out of node_modules and putting some console logs in I found that this._layoutManager in VirtualRenderer is in fact undefined at this point

**Comment by muskeinsingh** [comment]
Hey,

We are aware of the Null Pointer Exception here. We will be fixing it in a release soon. In the meanwhile, can you please make sure you mount the view after you have the data? It is being tracked [here](https://github.com/Flipkart/ReactEssentials/pull/43)

Let us know if this helps. Thanks for the feedback :)

**Comment by anshul1235** [comment]
+1

**Comment by anshul1235** [comment]
happened to me when the value of dataprovider was changing when my screen loads.. Not just with empty or no data, but happens when render is called multiple times in same time

**Comment by Fr1kki3** [comment]
Good to know that you are aware of this bug and are working on it. Mounting view after fetching needed data is not always possible. Please let us know when the fix is rolled out then I will update the package and start using the package again rather than just the components.

**Comment by naqvitalha** [comment]
Please try using version 1.2.0-beta.6 and see if solves the issue.

**Comment by naqvitalha** [comment]
Fixed in v1.2.0

**Comment by Fr1kki3** [comment]
seems to be fixed yes thank you
