### ISSUE TITLE
Recycler list view gets laggy at the half of the list

### ISSUE THREAD

**Issue by Wetsie** [Flipkart/recyclerlistview#620]
So, as you might see [on this vid](https://imgur.com/a/BcHJnu7), the performance is great at the first part of the list, thus slowing down at the second one. I've followed the performance guide pretty accurate, but the problem still exist. Here is the [expo snack](https://snack.expo.io/@tomphej/laggy-list) with an example. How can I fix that?

**Comment by siddharth-kt** [comment]
I also faced this problem, then i tried adding removeClippedSubviews, as below and it worked without any lag/jump. 
Note : i testied it only on android.

scrollViewProps={{
  refreshControl: (
    <RefreshControl
      refreshing={refreshing}
      onRefresh={this._handleRefresh}
    />
  ),
  removeClippedSubviews: true, 
}}

**Comment by Wetsie** [comment]
@siddharth-kt It actually helps. Thanks!

**Comment by MichalKrakow** [comment]
Yup, stipped down all app down to just recycler list. It started with notice that drawer on top of the list has super poor ui performance and couldnt get to get it back to performance i get really old devices. I figure this was on by default back in 2018. Maybe someone could offer some insight why this has such massive impact on rendering performance?
