### ISSUE TITLE
onEndReached called when initializing list

### ISSUE THREAD

**Issue by tafelito** [Flipkart/recyclerlistview#64]
Is there any reason why the _processOnEndReached is being called here?  https://github.com/Flipkart/ReactEssentials/blob/78203c98ad1caf6ec379687dc3842d29b77f4148/src/core/RecyclerListView.js#L258

The onEndReached callback is always called before loading the first items, so if I wanna add some logic to add more items when reaching the end, like an infinite loading, it will be called even if it's not needed. 

Is there any other reason to do that? Or maybe it could check if the dataProvided is not empty?

UPDATE: This only happens if `forceNonDeterministicRendering = true`

**Comment by naqvitalha** [comment]
This brings me back to the discussion I was having with @muskeinsingh the other day, the question was whether a list mounted with zero items is at its end or not? I think it is, height is zero and so is the offset.
Imagine a flow where you start fetching items with something called as `startIndex`, mounting a list with zero items can trigger load with `startIndex=0` and in the end update it as `startIndex+=10`. This will enable having just one flow to load items which is better than how people usually do it, they first load some items and then write an incremental load flow. Thoughts?

Also, incase of non deterministic flow if list has reached its end according to estimated heights it'll get called. Anyways, an expo sample might help to investigate this case.

**Comment by tafelito** [comment]
I think in terms of the flow you mention, I agree, only one flow would be better. The problem I see with that case is what happen when you want to preload data. Let's say I want to navigate to a screen, or come back and load the data at the same position I was. If you load the data on endReach, you will always see a blank screen ( or a loading indicator or any the footer if any). So I guess they way it works now it's should fine for those cases. I'm not sure why non deterministic should be different though. I'm using the sample demo you have to test this, but If it's necessary I could setup an example we could all take a look.

What about having a header and a footer? Look at slack for example, you have an infinite list where you can load older messages scrolling up, but you can load new messages scrolling dow, like an inverted pull to refresh. I know that's not a common case, but having a header and a footer could also help having only one flow. Like, load data when you get close to the footer. Make any sense?

**Comment by naqvitalha** [comment]
@tafelito But why would anyone mount the list without any data? If there is data onEndReached will not be triggered anyway. I see few people doing that but I don't really understand.

**Comment by tafelito** [comment]
First of all, when I set the` forceNonDeterministicRendering = true` the onEndReached callback is executed even if the list has any data before mounting. 

I'm not sure why you'd mount a list without any data (maybe no data at all?), but if I do that, I'd want to have the onEndReached callback to be called, but if the list does have data when 
mounting, the onEndReached should not be called, as it happens when using ` forceNonDeterministicRendering = true`

**Comment by naqvitalha** [comment]
`forceNonDeterministicRendering = true` should not trigger onEndReached if it does then it might be an issue. Provide a repro and I'll take a look.

**Comment by tafelito** [comment]
@naqvitalha sorry not to get back sooner. I have double checked this, and I guess I was wrong. If you initialize the dataProvider with some data before mounting, then the onEndReached is not called. But if you initialize it with an empty array, then it is called. And that's actually a good thing. It allows me to load data always in one place instead of having to fetch it on cDM and onEndReached in case of an infinite list.

I have a question tho. Not exactly related to the issue.

Why when using `forceNonDeterministicRendering` is it necessary to set a Layout provider if the dimension will be auto determined?

**Comment by naqvitalha** [comment]
Layout provider is necessary to provide estimates. Let's say if you want to do initial Render Index and stuff. It also helps in optimizing quick scrolls and in finding out approximate number of items to mount on initial render. Bottom line is it's being put to good use so it's worth the investment. Try to stay as close to the real dimensions as possible.
Regarding the second question.. in new versions you have getAllData() method as well in the data provider. However, when we built recyclerlistview we always envisioned stores to contain immutable collections and components to generate data providers so we never faced this issue.

**Comment by tafelito** [comment]
I understand that the closer you set the height the better is, but what if you don't really know or you there is no way of knowing what the size could be? 

Regarding the Data provider, why do you think having something like getAllData will break the immutability? Couldn't you get all data, and add some more in a new array without mutating the original data and setting the new data provider? Or am I looking it wrong?

Thanks for the answers

**Comment by naqvitalha** [comment]
I think when you have no clue some approximate average will help. Anything is better than a zero. Any value other than zero can work. Having layout provider there will encourage developers to it right IMO.

Regarding the second part, you are right immutability will still be preserved. It's just that we don't keep data providers in store as of now so we didn't encounter this case. Eventually, we want data provider to a collection itself which will allow us to track modified indexes. This info will help us get closer to native RecyclerView in terms of features.

**Comment by tafelito** [comment]
Thanks @naqvitalha! that'd e great

Let me know if I can be of any help

**Comment by naqvitalha** [comment]
@tafelito sure! Closing this.
