### ISSUE TITLE
Is there a react-native FlatList OnRefresh property?

### ISSUE THREAD

**Issue by yexianli** [Flipkart/recyclerlistview#663]
Is there a react-native FlatList OnRefresh property? I want to make sure, I don’t seem to see it

**Comment by siddharth-kt** [comment]
yeah its there, See code below typescript section.
Here : https://github.com/Flipkart/recyclerlistview#typescript

**Comment by yexianli** [comment]
> yeah its there, See code below typescript section. Here : https://github.com/Flipkart/recyclerlistview#typescript

thank you
