### ISSUE TITLE
[Android] RecyclerListView + Reanimated 2 onMomentumEnd not triggering

### ISSUE THREAD

**Issue by aklemen** [Flipkart/recyclerlistview#689]
Hi!
Is there a way to use RecyclerListView with [Reanimated 2](https://docs.swmansion.com/react-native-reanimated/) `useAnimatedScrollHandler()` hook?
Seems like RecyclerListView has a special `onScroll` event callback:
```typescript 
onScroll?: (rawEvent: ScrollEvent, offsetX: number, offsetY: number) => void;
```
The `onScroll`, `onBeginDrag` and `onEndDrag` events work as expected on Android and iOS.
But `onMomentumEnd` events are not triggering on Android.

```typescript
  const scrollHandler = useAnimatedScrollHandler({
    onScroll: event => {
      console.log("onScroll", event) // Triggering
    },
    onBeginDrag: event => {
      console.log("onBeginDrag", event) // Triggering
    },
    onEndDrag: event => {
      console.log("onEndDrag", event) // Triggering
    },
    onMomentumEnd: event => {
      console.log("onMomentumEnd", event) // Not triggering on Android
    },
  });
```

```typescript
  <AnimatedRecyclerListView
    layoutProvider={layoutProvider}
    dataProvider={dataProvider}
    rowRenderer={rowRenderer}
    onScroll={scrollHandler}
  />
```

**Comment by aklemen** [comment]
I tried adding `onMomentumScrollEnd` prop to `scrollViewProps` on `AnimatedRecyclerListView` and it seems to work.

But it now triggers both handlers - the one in `useAnimatedScrollHandler()` and the one passed in `scrollViewProps`.
However, that is not a problem (you can remove one of them).

```typescript
  const scrollHandler = useAnimatedScrollHandler({
    onScroll: event => {
      console.log("onScroll", event) // Triggering
    },
    onBeginDrag: event => {
      console.log("onBeginDrag", event) // Triggering
    },
    onEndDrag: event => {
      console.log("onEndDrag", event) // Triggering
    },
    onMomentumEnd: event => {
      console.log("onMomentumEnd", event) // Triggering 🎉
    },
  });
```
```typescript
  <AnimatedRecyclerListView
    layoutProvider={layoutProvider}
    dataProvider={dataProvider}
    rowRenderer={rowRenderer}
    onScroll={scrollHandler}
    scrollViewProps={{
        onMomentumScrollEnd: (event) => console.log("onMomentumScrollEnd", event), // Also triggering
    }}
  />
```

**Comment by aklemen** [comment]
Closing as this is a problem with [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/issues/2735).

**Comment by alexco2** [comment]
The upstream issue https://github.com/software-mansion/react-native-reanimated/issues/2735 seems to be low priority for software mansion. If everyone affected by this issue could upvote it, perhaps we will get some attention. Thanks
