### ISSUE TITLE
Sticky Headers with an External ScrollView

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/recyclerlistview#72]
I've been experimenting with the new `externalScrollView` prop trying to achieve a true sticky header experience. And this is what I came up with so far.

![sticky-header-demo](https://user-images.githubusercontent.com/10912145/32790017-824ef93e-c95d-11e7-9d06-85630a6e2499.gif)

My solution was replacing the normal `ScrollView` with an `Animated.ScrollView` and have its `onScroll` feed into an Animated value that I then use in the rowRenderer to stick some rows to the top.

This is my custom scrollview component.
```javascript
class AnimatedScrollView extends React.Component {
  render() {
    return (
      <Animated.ScrollView
        ref={ref => (this._scrollView = ref)}
        scrollEventThrottle={1}
        {...this.props}
        onScroll={Animated.event(
          [{ nativeEvent: { contentOffset: { y:animatedScrollViewOffsetY } } }],
          {
            useNativeDriver: true,
            listener: this.props.onScroll
          }
        )}
      />
    );
  }
}
```

I then use the `animatedScrollViewOffsetY` Animated Value in the `rowRenderer` and I calculate when the views should start sticking to the top like that:
```javascript
const stickyConfiguration = {
  startAt: 0,
  duration: -1 * HEADER_HEIGHT
};
_.forEach(this.state.dataProvider._data, (row, rowIndex) => {
  if (rowIndex < index) {
    stickyConfiguration.startAt += this.getRowHeight(row.viewType);
  } else {
    if (rowIndex > index && row.viewType === ViewTypes.DAY_HEADER) {
      return false;
    } else {
      stickyConfiguration.duration += this.getRowHeight(row.viewType);
    }
  }
});
```

I then pass the `y:animatedScrollViewOffsetY` to my component which positions itself with some transforms:
```javascript
const translateY = {
  transform: [
    {
      translateY: this.props.animatedScrollViewOffsetY.interpolate({
        inputRange: [
          0,
          stickyConfiguration.startAt,
          stickyConfiguration.startAt + stickyConfiguration.duration
        ],
        outputRange: [0, 0, stickyConfiguration.duration],
        extrapolate: 'clamp'
      })
    }
  ]
};
```

One of the challenges I faced was with `zIndex` values. I fixed it for iOS by changing the code for `ViewRenderer`, but couldn't fix it on Android. There's also the problem with the `onScroll` event that has to run both the `Animated.Event` and do `recyclerlistview`'s logic as well. I couldn't get around that myself.

I unfortunately can't just fork `recyclerlistview` and implement my solution since it doesn't work for Android yet, but that at least shows that the feature can be implemented. I'm thinking an additional property `stickyViewTypes` or something like that.

Please let me know if you need more clarification on how I made that demo work. Would love to have this added to recyclerlistview soon! 👍

**Comment by naqvitalha** [comment]
Looks great. Will take a look. Might take some time.

**Comment by AbdallaMohamed** [comment]
I'm interested in spending some of my free time on a PR. I'd appreciate it if you guys could help me with some tips on how to start with the PR. My assumption is that we could introduce a new prop `stickyHeaderType` or so, and for that type we calculate where it should start start sticking to the top and where it stops, using the same logic in my previous comment.

**Comment by naqvitalha** [comment]
That's awesome! I think the best way to go about it is to have a new scrollview with sticky header indices. Like FlatList does it. Thoughts?

**Comment by naqvitalha** [comment]
Any progress here?

**Comment by AbdallaMohamed** [comment]
Not yet. I'm going to work on it today and see what I can do

**Comment by rupamgho123** [comment]
I too have a use case for sticky header, any chance this will be implemented soon ?

**Comment by naqvitalha** [comment]
@AbdallaMohamed Any update on this, would be great to have this

**Comment by AbdallaMohamed** [comment]
@naqvitalha I'll get to this as soon as I can.

**Comment by AbdallaMohamed** [comment]
I've having trouble working on RLV and linking it to be used in another project where I'll be testing my changes. Any tips on how to set this up? @naqvitalha

**Comment by naqvitalha** [comment]
@AbdallaMohamed Just clone the project and make changes in TypeScript code. There are few scripts in the package.json. You need to run the setup script once  post that run build when you make changes. Build will generate a dist folder to which the package points by default. Let me know if this unblocks you.

**Comment by AbdallaMohamed** [comment]
@naqvitalha  I've been able to do that just fine. It's the `npm link` that's tricky though. Does the react native bundler respect npm links? I need to start another project and have my `import from recyclerlisview` point to my local project instead.

**Comment by alpamys-qanybet** [comment]
@AbdallaMohamed, I found your workaround very nice, can you share your code?

**Comment by AbdallaMohamed** [comment]
@naqvitalha

My solution fails because the sticky header might not be rendered if you have a long section. In a situation where we have:

1 header
100 rows
1 header 
More rows

The scroll position could be somewhere in the 100 rows, and the 1 header at the top isn't rendered.

What are your thoughts?

**Comment by naqvitalha** [comment]
Sticky implementation is now part of RLV. Closing this.
