### ISSUE TITLE
onVisibleIndexesChanged returns wrong values when initialRenderIndex is provided

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/recyclerlistview#73]
I've been trying to utilize both the `onVisibleIndexesChanged` and `initialRenderIndex` props at the same time, but I'm facing a weird behaviour that I'm not sure if it's intended to be that way.

When I provide an `initialRenderIndex` value of 10, `onVisibleIndexesChanged` is fired first with the values `[0, 1, 2, 3, ...]` and then it's fired again with the correct values `[9, 10, 11, 12, 13, ...]`

I've reproduced in this snack https://snack.expo.io/ByBPIAtyM

Has it been implemented that way on purpose? And if so, what workaround would you guys suggest?

**Comment by naqvitalha** [comment]
Thanks for reporting the issue. Definitely not what was intended. This is regression bug :(
I've fixed this in 1.2.0-beta.6. Will close once it is released.

**Comment by AbdallaMohamed** [comment]
Just switched to `1.2.0-beta.6` and it's fixed! 👍
