### ISSUE TITLE
Feature request FlatList syntax

### ISSUE THREAD

**Issue by Stevemoretz** [Flipkart/recyclerlistview#735]
It would be great to export another component from this having the same syntax as FlatList, then this can be dropped instead of a FlatList easily that would be great for migrating and also normal usage!

**Comment by kevin-kp** [comment]
Hi, I think that this is something that is being done by https://github.com/Shopify/flash-list which uses this library.

**Comment by Stevemoretz** [comment]
> Hi, I think that this is something that is being done by https://github.com/Shopify/flash-list which uses this library.

Thanks that's awesome!
Didn't know that uses this, why is the `pod install` for though?

>Add the package to your project via yarn add @shopify/flash-list and run pod install in the ios directory.

**Comment by kevin-kp** [comment]
Because it uses native code that needs to be installed with Cocoapods: https://github.com/Shopify/flash-list/blob/main/RNFlashList.podspec.

**Comment by Stevemoretz** [comment]
Sounds Great Thanks!
