### ISSUE TITLE
Getting error recyclerlistview needs to have a bounded size .currently height or width is 0

### ISSUE THREAD

**Issue by sam201401** [Flipkart/recyclerlistview#74]
I am trying to add fixed footer how can I solve this problem

**Comment by naqvitalha** [comment]
Try giving flex:1 to the listview. Make sure the parent view is also deterministic in height/width.

**Comment by SudoPlz** [comment]
@naqvitalha do we have to necessarily set a parent width **and** height to the `View` that contains the `RecyclerListView`?

Even though we do know the width of the content of the `RecyclerListView`  we have no idea of the height. (We're using `RecyclerListView` as a **horizontal** list) so setting a fixed height on the parent `View` hides the content.

Any ideas?

**Comment by naqvitalha** [comment]
@SudoPlz All you need is some inferable way to have determine dimensions to compute layouts. An example can help me understand better. If you can build whatever you're trying to with plain `ScrollView` then most likely it'll be possible with `RecyclerListView`. `RecyclerListView` can monitor `ScrollView` size changes if you set `canChangeSize` prop to `true`.

**Comment by SudoPlz** [comment]
Basically the problem is that if people use huge Accessibility font sizes, then the height of the content should change, and I have no way of knowing that upfront.

What I tried though was, I used `minHeight` instead of `height` and the error is gone now.
Not sure if that's ideal what do you think @naqvitalha ?

**Comment by naqvitalha** [comment]
It does sound like the solution for now. It will cause one set of layouts to get discarded but unless you have tens of thousands of items that shouldn't be noticeable. I'll get back if I can think of something better.

**Comment by lvstross** [comment]
My fix for this issue was to wrap my list in a `View` component and give that view a height and width.
```
      return <View style={{ width: '100%', height: this.props.dimensions.get('height') }}>
        <RecyclerListView
          keyboardShouldPersistTaps={true}
          dataProvider={data}
          layoutProvider={this.layoutProvider}
          rowRenderer={this.renderRow}
          canChangeSize={true}
        />
      </View>;
```
