### ISSUE TITLE
Cannot read property 'reLayoutFromIndex' of undefined

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/recyclerlistview#75]
I'm trying to change the content of the `recylcerlistview`, but I keep getting `Cannot read property 'reLayoutFromIndex' of undefined`. What could be causing that error?

I'm updating my data in the following way:
```javascript
this.setState(prevState => ({
   dataProvider: prevState.dataProvider.cloneWithRows(newRows)
}));
```

The error happens in `RecyclerListView.js:224` in the line
`this._virtualRenderer.getLayoutManager().reLayoutFromIndex(newProps.dataProvider._firstIndexToProcess, newProps.dataProvider.getSize());`

That was called from `componentWillReceiveProps` of `RecyclerListView` in the line `this._checkAndChangeLayouts(newProps);`

`_virtualRenderer` is getting set to null for some reason. Could you please explain what could be causing that problem

**Comment by naqvitalha** [comment]
Are you trying to do so before the mount has happened? Are you using React 16 by any chance?
Give version 1.2.0-beta.5 a try and let me know.

**Comment by AbdallaMohamed** [comment]
@naqvitalha  Yeah I'm using React 16.0.0-beta.5

I switched to `recyclerlistview@1.2.0-beta.5` and that problem seems to be fixed now! 👍 

Any specific date for when this one gets released along with the `onVisibleIndexesChanged` bug fix?

**Comment by naqvitalha** [comment]
In about two weeks. We are moving to typescript, thus the delay.
