### ISSUE TITLE
Version 4.2.0 increases blank views

### ISSUE THREAD

**Issue by ElicaInc** [Flipkart/recyclerlistview#755]
Update to [Version 4.2.0] causes increase of blank view. Downgrade to [Version 4.1.4] works fine.

**Comment by naqvitalha** [comment]
There aren't any changes that affect performance between those versions. Can you share a video of the difference that you're seeing?

**Comment by ElicaInc** [comment]
@naqvitalha thank you for your response. I looked over my code, then I found other factors slowed down the rendering.
