### ISSUE TITLE
Question: How to update initialRenderIndex when changing rows

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/recyclerlistview#77]
I'm trying to update the rows with `cloneWithRows`, but looks like updating `initialRenderIndex` at the same time as updating the `dataProvider` doesn't actually work. Maybe that's the way it was intended to work, but I also noticed that the `recyclerlistview` maintains scrollposition even if the overall height of it changes.

I made a quick snack of this case here: https://snack.expo.io/SJyh3xiyG

You can see that I have an **`initialRenderIndex` of 20**, and there are **100 rows** in total. Upon changing the rows to be **10**, the scroll position hasn't changed and you'd have to scroll the `recyclerlistview` a little bit and then the scroll position is fixed.

Changing the `initialRenderIndex` doesn't have an effect as well, as I mentioned before.

**Comment by naqvitalha** [comment]
`initialRenderIndex` only works with initial mount. That's the way it was designed. I think you can easily achieve your case by using `scrollToIndex`. `initialRenderIndex` is helpful in cases of initial mount where you don't want any flickers.

**Comment by AbdallaMohamed** [comment]
How about that other problem that I'm showing in my snack, where the scroll position is maintained when the over all height of the all rows is smaller?

**Comment by naqvitalha** [comment]
I'm not able to repro that. Any hints?

**Comment by AbdallaMohamed** [comment]
I just noticed that it's working on my android phone but not on the iPhone simulator.  Load the snack and you'll see that it loads a 100 rows with an initial render index of 20. Tap on "Change Rows" which change the content to 10 rows. You'll notice that the scroll position is way below the last item in the list.  If you touch the RecyclerListView, it will scroll up to the last item of the list.

**Comment by naqvitalha** [comment]
That explains why it wasn't happening for me on android. I really wouldn't want to put a hack to fix it for iOS. Btw does an extra setState fixes it? How about a programmatic one pixel scroll?

**Comment by AbdallaMohamed** [comment]
Programmatic scrolling doesn't work, I'm afraid. I even tried `getCurrentScrollOffset()` and it's returning the wrong offset. Looks like the height of the listview is being updated on scroll or something.

Another `setState` just update the rows, but the scroll position is never updated until you manually scroll inside of the listview.

Check out this example where I'm changing rows from 100 to 25, with an initialRenderIndex of 20.
https://snack.expo.io/HJc3h02kM

**Comment by naqvitalha** [comment]
Data Provider change immediately causes a change in height since a request layout immediately happens in the layout manager. This seems to be an iOS thing. I don't have time to look into this right now. Will appreciate if you can dig deep otherwise, I'll come back to this later.

**Comment by AbdallaMohamed** [comment]
A little bit of a late reply, but I've just had the same problem with the normal ScrollView on iOS. React native doesn't update the scroll position when the content of the scroll view change and it becomes smaller. Just thought I'd share this obvious observation.

**Comment by naqvitalha** [comment]
Thanks for the update! Did you raise an issue with RN? If you did reference it here.. I might ask our iOS team to look into the RN issue

**Comment by naqvitalha** [comment]
Closing dude to lack of activity.
