### ISSUE TITLE
Opacity = 0 VS Display = none

### ISSUE THREAD

**Issue by sm2017** [Flipkart/recyclerlistview#82]
Relative to https://github.com/Flipkart/recyclerlistview/issues/71

> A simple example, lets say we have a view that looks like this:
> Image + Text
> 
> And the Text is optional, while recycling if your component renders Text on the basis of whether text is there or not the Text component will see multiple unmounts/mounts. This might lead to drop in performance. A better way would be to simply hide Text (opacity = 0) and let it be there since it might get reused in future.

I want to know is there any difference between `Opacity = 0` and `Display = none` for hiding objects in recycle view

Is object with `Display = none` recyclable? I turn on `show layout bounds` and `Display = none` has no bounds but `Opacity = 0` has , So Is `Display = none` has inconvenient unmounts/mounts

**Comment by naqvitalha** [comment]
As per my understanding display:'none' would still create the item but not put it in the view hierarchy. The display:'none' should be better, but do experiment yourself. Also, it would be interesting to see what you're building if you can share.

**Comment by sm2017** [comment]
I will share my experience
Thanks a lot
