### ISSUE TITLE
view recycling and "prepare for reuse"

### ISSUE THREAD

**Issue by farfromrefug** [Flipkart/recyclerlistview#84]
On iOs and android we use "prepare for reuse" to make sure a view is ready to be reused.
The simplest example is ```Image``` if there were an image already loaded and you set a new image that wont load (network error or such), you end with a view with the image for another cell.

Is there any way in your lib to set the image to "null" before it is reused?

Thanks

**Comment by naqvitalha** [comment]
You can always call setNativeProps directly on the ref of the image in `componentWillReceiveProps`. That should do.

**Comment by farfromrefug** [comment]
@naqvitalha thanks i ll try!

**Comment by naqvitalha** [comment]
Close the issue if it worked.

**Comment by naqvitalha** [comment]
Inactive for a while. Closing.

**Comment by hovox** [comment]
Hey @naqvitalha . 
It's not working for me. It renders old image, then updates with new one. 
Here is a `componentWillReceiveProps ` code:
```
  componentWillReceiveProps() {
    this.img && this.img.setNativeProps({ source: null });

    // console.warn("componentWillReceiveProps img: " + this.img.source);
    // this.img && this.img.setNativeProps({ source: null });
  }
```

**Comment by hovox** [comment]
I wander if there is an example with images ?

**Comment by hovox** [comment]
@naqvitalha are you using with `disableRecycling={true}` ?

**Comment by farfromrefug** [comment]
@naqvitalha sorry for not responding. Dropped react-native as it was not good enough.
Sorry

**Comment by naqvitalha** [comment]
@hovox Try `this.img.setNativeProps({ opacity: 0 })`. Toggle opacity.
You can check this sample https://snack.expo.io/@naqvitalha/rlv-demo
