### ISSUE TITLE
Support custom data source like VirtualizedList does

### ISSUE THREAD

**Issue by punksta** [Flipkart/recyclerlistview#88]
Thanks for cool library. 
DataProvider supports only array as data source. I want to use it with Immutable.js data structures

**Comment by naqvitalha** [comment]
It is already possible. DataProvider can be extended into something custom. Check the following file: https://github.com/Flipkart/recyclerlistview/blob/master/src/core/dependencies/DataProvider.ts

Inherit DataProvider and override `getDataForIndex()`. Start using immutable collection instead of array. Let me know if you need further help.

**Comment by punksta** [comment]
Worked, thanks. 
this `data: any[]` stopped me. Maybe better to have an interface and then make existing DataProvider basic implementation.

**Comment by black7375** [comment]
@naqvitalha have one question.

I looked at the source to override.
https://github.com/Flipkart/recyclerlistview/blob/b7c23d222b046f3310a23d87805a0f38df3d277a/src/core/dependencies/DataProvider.ts#L30-L32

To redefine the function, need to access the `_data`, but it is private.
https://github.com/Flipkart/recyclerlistview/blob/b7c23d222b046f3310a23d87805a0f38df3d277a/src/core/dependencies/DataProvider.ts#L14

What about creating `any[]`, `any` types to interfaces in generics?

**Comment by wxsms** [comment]
@black7375 Use `getAllData` instead.

**Comment by black7375** [comment]
@wxsms 
I asked because I couldn't write a data type like `List<T>` because of the type of `_data`(`any[]`), but I solved the problem by creating it again without the interface.

Like this.
```
export abstract class GenericDataProvider<T, K = keyof T> extends BaseDataProvider{
  public rowHasChanged: (r1: T | any, r2: T | any) => boolean;

  // In JS context make sure stable id is a string
  public getStableId: (index: number) => string;
  protected m_firstIndexToProcess: number = 0;
  protected m_size: number = 0;
  protected m_data: K | any = List<T>([]);
  protected m_hasStableIds = false;
  protected m_requiresDataChangeHandling = false;

  constructor(rowHasChanged: (r1: T | any, r2: T | any) => boolean,
              getStableId?:  (index: number) => string) {
    super(rowHasChanged, getStableId);
    this.rowHasChanged = rowHasChanged;
    if (getStableId) {
      this.getStableId = getStableId;
      this.m_hasStableIds = true;
    } else {
      this.getStableId = (index) => index.toString();
    }
  }

  public abstract newInstance(
    rowHasChanged: (r1: T, r2: T) => boolean,
    getStableId?: (index: number) => string    ): GenericDataProvider<T, K>;
  public abstract getDataForIndex(index: number): T | undefined;
  public abstract cloneWithRows(newData: K | any,
                    firstModifiedIndex?: number): DataProvider;

  public getAllData(): K | any {
    return this.m_data;
  }
...
```

**Comment by wxsms** [comment]
@punksta Hi, could you pls show your solution here? I've tried the solution provided by @naqvitalha , by it doesn't work. It just show a blank screen without any errors. Thank you in advance!

**Comment by wxsms** [comment]
Never mind. found out that I have to override not only `getDataForIndex `, but also `newInstance` and `cloneWithRows`. and should extends `BaseDataProvider`, not `DataProvider`. This is not frinedly enough 😢 . But anyway, works now.
