### ISSUE TITLE
RecycleView needs to have a bounded size. currently height or, width is 0

### ISSUE THREAD

**Issue by hasanal1995** [Flipkart/recyclerlistview#89]
please help me ...!
when wrap recyclerlistview with react-native-pull-to-refresh give me that error !, and cannot accept flex:1,any one can help ??
any way to refresh ??

**Comment by naqvitalha** [comment]
I don't think that library ever handled listviews. ListViews need fixed bounds to compute item layouts. Good thing is that RecyclerListView is built on top on ScrollView so RefreshControl should work. Check this: https://facebook.github.io/react-native/docs/refreshcontrol.html

**Comment by hasanal1995** [comment]
really thank you :), its worked but not fetch data even when refreshing occur!!

**Comment by hasanal1995** [comment]
@naqvitalha its worked, thank very much pro

**Comment by naqvitalha** [comment]
Awesome, I'll close this one then.
