### ISSUE TITLE
One of the first rows is blank

### ISSUE THREAD

**Issue by itchingpixels** [Flipkart/recyclerlistview#95]
Hi!

Thanks for this, it looks really useful!
We're having this weird issue, where one of the first 3 rows always comes up blank.
Not even scrolling around can solve the issue - but that may be connected to us having `disableRecycling` as `true`. (we want the previous cells in memory).

Is this something others have experienced?

**Comment by itchingpixels** [comment]
![image](https://user-images.githubusercontent.com/5416288/34565459-e5294a9c-f152-11e7-84f6-1105b3621682.png)
This is what our LayoutProvider looks liek

**Comment by itchingpixels** [comment]
Sorry, this has been solved. A mistake on our end! Closing this.

**Comment by aureliopetrone** [comment]
@itchingpixels what was the problem? I'm facing a similar issue.

Thank you!
