### ISSUE TITLE
onVisibleIndexesChanged's now returns multiple children when only 1 is visible.

### ISSUE THREAD

**Issue by SudoPlz** [Flipkart/recyclerlistview#98]
Hey there,
I'm struggling to find why I receive more than 1 views being visible, when there's only 1 view visible, and I believe this line is the problem:

https://github.com/Flipkart/recyclerlistview/blob/61486a61eed4f59e3cd1948cbe573cbfa8cd4bef/src/core/ViewabilityTracker.ts#L243

The item will be in the bounds even if the `itemBound` is exactly the same as the `window.start` or the `window.end`.

But if one view ends in pixel 100 and the next one begins at pixel 100, they are not overlapping, so there's no need to include the results in the now, is there?

I believe changing this line to:

` return (window.start < itemBound && window.end > itemBound);`

would be the way to go.

Here's an example of output values I receive when I `console.log` the windows size and the children sizes:

`ViewabilityTracker.js:164`
```
9936 |-----| 10350 window intersects child: 9522|---|9936, index: 23
9936 |-----| 10350 window intersects child: 9936|---|10350, index: 24
9936 |-----| 10350 window intersects child: 10350|---|10764, index: 25
```

What do you think? If that is intended behaviour for some reason feel free to close the issue.

**Comment by naqvitalha** [comment]
Perfect timing, you are correct. I was actually working to fix https://github.com/Flipkart/recyclerlistview/issues/83. Issue with the same callback. Can you try `1.2.6-beta.4` to see if issue is resolved?

**Comment by naqvitalha** [comment]
Fixed.

**Comment by SudoPlz** [comment]
You're the man, thanks I'll try 1.2.6 today.
